OpenSCAP/openscap

src/OVAL/probes/unix/linux/systemdunitproperty.c
18. openscap-1.1.1/src/OVAL/probes/unix/linux/systemdunitproperty.c:107: alloc_fn: Storage is returned from allocation function "oscap_strdup".
21. openscap-1.1.1/src/common/util.c:65:2: alloc_fn: Storage is returned from allocation function "strdup".
22. openscap-1.1.1/src/common/util.c:65:2: var_assign: Assigning: "m" = "strdup(str)".
25. openscap-1.1.1/src/common/util.c:70:2: return_alloc: Returning allocated memory "m".
26. openscap-1.1.1/src/OVAL/probes/unix/linux/systemdunitproperty.c:107: var_assign: Assigning: "property_name" = storage returned from "oscap_strdup(value.str)".
33. openscap-1.1.1/src/OVAL/probes/unix/linux/systemdunitproperty.c:116: leaked_storage: Variable "property_name" going out of scope leaks the storage it points to.
=> Plug a memory leak.

tests/probes/systemdunitdependency/Makefile.am, tests/probes/systemdunitdependency/all.sh, tests/probes/systemdunitdependency/test_validation.sh
We need to test `oscap oval validate`
and `oscap oval validate --schematron` on OVAL 5.11 content
to avoid mistakes in OVAL 5.11 schematron.
=> Test oscap oval validate on OVAL 5.11 content.

schemas/oval/5.11/linux-definitions-schema.xsd
Previously, OVAL-5.10 allowed for missing epoch/version/release/arch.
The upstream OVAL-5.11 schema is now more strict and not backward
compatible.
We need to make OVAL-5.11 schema backward compatible to support
DataStream content that includes such OVAL-5.10 content. Note that
DataStream 1.2 schema imports fixed version of OVAL schemas.
Addressing:
File '/tmp/ssg-rhel6-ds.xml' line 8755: Element
'{http://oval.mitre.org/XMLSchema/oval-definitions-5#linux}filepath':
This element is not expected. Expected is (
{http://oval.mitre.org/XMLSchema/oval-definitions-5#linux}epoch ).
=> rhbz#1220262: Modify OVAL-5.11 schema files to be backward compatible

ac_probes/configure.ac.tpl, configure.ac, src/OVAL/oval_glob_to_regex.c, src/common/oscap_string.c, src/common/oscap_string.h, tests/Makefile.am, tests/oscap_string/Makefile.am, tests/oscap_string/test_oscap_string.c, tests/oscap_string/test_oscap_string.sh
We had oscap_string_free, but we didn't use it nowhere.
We hide the definition of struct oscap_string from other modules.
=> String improved

src/XCCDF_POLICY/xccdf_policy_substitute.c
Addressing:
at 0x4C2B946: calloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
by 0x4E7F818: __oscap_calloc (alloc.c:68)
by 0x4E80DC2: oscap_iterator_new (list.c:242)
by 0x4EE1D2D: _xccdf_text_substitution_cb (xccdf_policy_substitute.c:174)
by 0x4E84727: xml_element_dfs_callback (xml_iterate.c:31)
by 0x4E84775: xml_element_dfs_callback (xml_iterate.c:36)
by 0x4E8481E: xml_iterate_dfs (xml_iterate.c:70)
by 0x4EE2124: xccdf_policy_resolve_fix_substitution (xccdf_policy_substitute.c:201)
by 0x4EE1528: xccdf_policy_rule_result_remediate (xccdf_policy_remediate.c:387)
by 0x4EE1B44: xccdf_policy_remediate (xccdf_policy_remediate.c:439)
by 0x40B7B9: app_evaluate_xccdf (oscap-xccdf.c:513)
by 0x407BFC: oscap_module_call (oscap-tool.c:260)
by 0x407BFC: oscap_module_process …
=> trac#480: plug a memory leak

src/XCCDF/xccdf_session.c
session->tailoring.user_file is freed again in cleanup section.
if (from_sds == true) and (session->full_validation == true) on xccdf_session.c:851 there could be some unexpected behavior.
Used command: 
oscap xccdf eval --tailoring-file /tmp/empty ./test_xccdf_refine_rule_unchecked.xccdf.xml 
/tmp/empty ~ empty file = invalid file
./test_xccdf_refine_rule_unchecked.xccdf.xml ~ some valid xccdf
Segfault stacktrace:
#0  0x00007ffff513a78d in free () from /lib64/libc.so.6
#1  0x00007ffff7b3d6f2 in oscap_source_free (source=0x61dbf0) at oscap_source.c:126
#2  0x00007ffff7b93957 in xccdf_session_free (session=0x61bab0) at xccdf_session.c:223
#3  0x000000000040b5d5 in app_evaluate_xccdf (action=<optimized out>) at oscap-xccdf.c:540
#4  0x0000000000407bee in oscap_module_call …
=> Fix segfault after error during tailoring file loading

src/common/oscap_string.c
Every oscap_string_* function check if ptr is NULL, except oscap_string_free()
=> oscap_string fix oscap_string_free()

src/XCCDF_POLICY/Makefile.am, src/XCCDF_POLICY/xccdf_policy.c, src/XCCDF_POLICY/xccdf_policy_priv.h, src/XCCDF_POLICY/xccdf_policy_resolve.c, src/XCCDF_POLICY/xccdf_policy_resolve.h, tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/test_xccdf_refine_rule_refine.sh, tests/API/XCCDF/unittests/test_xccdf_refine_rule_refine.xccdf.xml
Should solve this ticket:
https://fedorahosted.org/openscap/ticket/439
Add support for  refine rule @weight, @severity @selector, but there are some unsolved issues with partially overriding refine-rules and refining @weight for groups.
=> Refine-rule

schemas/Makefile.am
This fixes the `make distcheck` when performing (not yet available, but soon proposed) tests with content in OVAL 5.11.1. This commit used to be part of pull request 107. That PR handles schema_version elements. However, this commit doesn't have any connection with schema_version elements. Since that PR is large and it would likely require some more time before it will be merged, I have decided to remove this commit from pull request 107 and introduce the commit as a separate pull request. Because there is a possibility that this would block something in future, I would like to make it easy to merge this fix.
=> Added OVAL 5.11.1 schemas to Makefile.am

src/OVAL/oval_varModel.c
It will prevent calling strcmp with NULL arguments.
See: https://fedorahosted.org/openscap/ticket/492
=> Use oscap_strcmp() instead of strcmp()

src/OVAL/probes/SEAP/sch_pipe.c, src/common/debug.c
It is easier to trace probe's logfile.
=> Add PID to error message when probe has been killed

src/common/list.c, tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/test_xccdf_results_arf_no_oval.sh, tests/API/XCCDF/unittests/test_xccdf_results_arf_no_oval.xccdf.xml
Fix issue from maint-1.2
(more info): https://github.com/OpenSCAP/openscap/pull/145
Fix issue with adding check to oscap_htable_iterator_has_more()
=> Maint 1.0 arf export segfault - add check  oscap_htable_iterator_has_more

src/source/oscap_source.c
Multiple calls cause that oscap tries to parse non-valid xml again and again
And stderr contains the same error messages many times
=> Don't print the same error messages multiple times

src/source/oscap_source.c, tests/API/XCCDF/unittests/test_unfinished.sh
Libxml (parsing) errors were leaking to stderr.
It catch them and pass them to oscap_seterr.
It has similar behavior than before for oscap. But it is important for workbench and other programs using the lib.
=> Push libxml parsing to oscap_seterr

src/common/oscap_string.h
Some functions were not visible from public API in 1.2.5 and we don't want to make them public now.
=> oscap_string fix visibility

src/common/oscap_acquire.c
oscap_string* functions are used, but oscap_buffer header file is included.
should be replaced in
- maint-1.0
- maint-1.1
- in maint-1.2 should be both - oscap_string.h and oscap_buffer.h
=> Fix bad #include in oscap_acquire

src/XCCDF_POLICY/xccdf_policy_resolve.c
Addressing:
11 bytes in 1 blocks are indirectly lost in loss record 1 of 5
at 0x4C29BFD: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
by 0x757E529: strdup (in /usr/lib64/libc-2.17.so)
by 0x4E84D9A: oscap_strdup (util.c:65)
by 0x4ED3DDF: xccdf_refine_rule_clone (profile.c:107)
by 0x4EE1780: xccdf_policy_add_profile_refine_rules (xccdf_policy_resolve.c:190)
by 0x4EE4676: xccdf_policy_new (xccdf_policy.c:1773)
by 0x4EE42AD: xccdf_policy_model_get_policy_by_id (xccdf_policy.c:1880)
by 0x4EDF7B4: xccdf_session_set_profile_id (xccdf_session.c:363)
by 0x40B91B: app_evaluate_xccdf (oscap-xccdf.c:482)
by 0x407E37: oscap_module_call (oscap-tool.c:260)
by 0x407E37: oscap_module_process (oscap-tool.c:345)
by 0x406D5E: main (oscap.c:80)
24 bytes in 1 blocks are indirectly lost in …
=> trac#505: Plug memory leaks

utils/oscap-oval.c
Functionality of this function was moved into the OVAL Sesssion during the
refactoring of app_evaluate_oval (see 42895cc157905036b0c7e11772fa9e9cbabb3f30)
and it's not used anymore. The function wasn't remove during the refactoring
because the warning complaining about it got lost among other warnings.
=> Remove unused oval_gen_report function

src/OVAL/probes/SEAP/seap.c, src/OVAL/probes/probe/icache.c, src/OVAL/probes/probe/input_handler.c, src/OVAL/probes/probe/main.c, src/common/debug.c
I was playing a bit with threads and processes. For my better understanding, I gave threads some names and I showed the process and thread names in debug logs. I thought that this might be useful also for other people, so I propose it as a pull request.
Debug log before:
`(22827:7f9815527700) [I:seap-packet.c:903:SEAP_packet_recv] Received packet`
And after:
`(lt-probe_file(22827):input_handler(7f9815527700)) [I:seap-packet.c:903:SEAP_packet_recv] Received packet`
=> Show process name and thread name in debug logs

utils/oscap_docker_python/get_cve_input.py, utils/oscap_docker_python/oscap_docker_util.py
Previously, we determined if new CVE data should be
fetched by specificying the max age of the files in
units of hours.
The new implementation uses the following to determine
if it should fetch the new file:
* If the file isn't in the local cache dir, fetch it
* If the file is local, check the mtime of the remote
file and compare it to the local file.  If they
differ by more than two seconds, fetch a new one.
* Else, do not fetch a new one.
We also now return the fully qualified file name in question
from _fetch_single.  And in the case of fetch_dist_data, we
return a list of all the filenames.  This is in preparation
of the files being compressed upstream as we will want to know
which file(s) we are dealing with.
And finally, debug was added to the time related functions so
they are …
=> Improve caching and fetching of CVE input data

tests/API/OVAL/glob_to_regex/test_glob_to_regex.c
solve linking errors "undefined reference to `__oscap_alloc_dbg'" with --enable-debug
=> test: glob-to-regex fix #include <config.h>

tests/oscap_string/test_oscap_string.c
Licence file is already in maint-1.2
absence of #include <config.h> caused linker errors
=> Maint 1.0 fix oscap string test

ac_probes/configure.ac.tpl, configure.ac, utils/Makefile.am, utils/oscap-vm, utils/oscap-vm.8
Offline SCAP scanning for VMs that are shutdown or running. Uses guestfs tools. My aim was to be as consistent as possible, the tool is similar to oscap-ssh and oscap-docker.
Example usage:
```
Mounting guestfs image '/var/lib/libvirt/images/rhel7.2.qcow2' to '/tmp/tmp.PgfWcB0R4g'...
Title   Encrypt Partitions
Rule    xccdf_org.ssgproject.content_rule_encrypt_partitions
Ident   CCE-27128-8
Result  notchecked
[snip]
Title   Enable SSH Warning Banner
Rule    xccdf_org.ssgproject.content_rule_sshd_enable_warning_banner
Ident   CCE-27314-4
Result  fail
Title   Create Warning Banners for All FTP Users
Rule    xccdf_org.ssgproject.content_rule_ftp_present_banner
Ident   CCE-RHEL7-CCE-TBD
Result  pass
Unmounting '/tmp/tmp.PgfWcB0R4g'...
```
```
Mounting guestfs domain 'rhel7.2' to …
```
=> oscap-vm - scan virtual machines and their images

src/XCCDF/xccdf_session.c, tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/oval/always-fail/oval.xml, tests/API/XCCDF/unittests/test_xccdf_oval_relative_path.sh, tests/API/XCCDF/unittests/test_xccdf_oval_relative_path.xccdf.xml
https://fedorahosted.org/openscap/ticket/504
When you want to create HTML report from XCCDF which references OVAL using relative path using --oval-details, oscap tries to create file e.g. ./my/path/file.oval.xml.result.xml
- when the folder "./my/path/" doesn't exist, it was causing segfault - the folder usually exists (because it is the same directory as directory of existing oval file) - but when your cwd is different from directory of xccdf, the relative directories won't match
This pull requst:
- add tests (other tests are in beakerlib format)
- fix path when generating of oval-results files
- add OVAL details to HTML report from (internally generated) ARF not from oval result.files - which fix problem with loading oval-details from escaped path.
=> Fix loading oval results from relative path

utils/oscap_docker_python/get_cve_input.py
Added HTTPSHandler in case other people want to use https for fetching
and they want to change the URL. This is useful for the custom URL feature in `atomic scan` and `oscapd`. It also makes sense to prefer https over http.
How to test easily:
```
$ mkdir /tmp/cve
$ python -i oscap_docker_python/get_cve_input.py 
>>> a = getInputCVE("/tmp/cve")
>>> a.fetch_dist_data()
['/tmp/cve/Red_Hat_Enterprise_Linux_5.xml', '/tmp/cve/Red_Hat_Enterprise_Linux_6.xml', '/tmp/cve/Red_Hat_Enterprise_Linux_7.xml']
>>> a.fetch_dist_data()
['/tmp/cve/Red_Hat_Enterprise_Linux_5.xml', '/tmp/cve/Red_Hat_Enterprise_Linux_6.xml', '/tmp/cve/Red_Hat_Enterprise_Linux_7.xml']
```
First run fetches everything from scratch, the second run finds the cached files and requests HEAD for each of them, checking …
=> Use HTTPS for fetching the CVE OVALs in oscap-docker

ac_probes/configure.ac.tpl, configure.ac, utils/oscap_docker_python/get_cve_input.py
Saves bandwidth and (at least in most cases) time.
We don't do any unbzip-ing because oscap does that on its own.
This change requires recent `oscap` tool with bzip support but I think it's not an issue since we ship both in closely related packages. The only issue I can think of is when somebody compiles openscap with oscap-docker but without bzip support. If we agree that this is a serious issue I suggest we blacklist that combination in `configure`.
=> Download bzipped variants of RHSA OVAL data in oscap-docker

src/OVAL/oval_session.c
When refactoring the code into the "OVAL session", we have probably
forgotten about the --skip-valid option.
=> Issue #203: oscap oval eval --skip-valid doesn't skip validating

cpe/openscap-cpe-oval.xml
This OVAL file was invalid. There were missing objects and states.
It was one of causes of issue #191 (segfault on oscap xccdf eval).
=> Fix invalid CPE content

src/OVAL/oval_definitions_impl.h, src/OVAL/oval_enumerations.c, src/OVAL/oval_object.c, src/OVAL/oval_state.c, src/OVAL/oval_sysItem.c, src/OVAL/oval_test.c
This code repeats 4 times in OpenSCAP. This commit refactors it out
to a single function. This functions converts oval family to a XML namespace.
=> Refactor + fix a segfault

ac_probes/configure.ac.tpl, configure.ac, cpe/openscap-cpe-oval.xml, tests/CPE/Makefile.am, tests/CPE/all.sh, tests/Makefile.am
This OVAL file did not pass validation by schematron.
A rpminfo_test should not reference a rpmverifyfile_object,
it can be referenced only from a rpmverifyfile_test.
We must change tests to rpmverifyfile_test and
also change respective states.
=> Fix and test openscap-cpe-oval.xml

src/OVAL/oval_probe_ext.c, src/OVAL/oval_probe_session.c, src/OVAL/probes/SEAP/generic/strbuf.c
These messages describe implementation details and can be ignored
by users who are interested in OVAL evaluation.
=> Change category of some debug messages to DEVEL verbosity level

src/common/debug_priv.h, src/common/util.h
The util.h doesn't depend on public/oscap_debug.h, so we should
remove the include from there. On the other hand, debug_priv.h
depends on public/oscap_debug.h, so we should add include there.
=> Issue #205: Fix header dependencies

utils/oscap-tool.c
This helps users who used incorrectly --verbose and --verbose-log-file
how to use those features right.
=> Issue #206: Improve error messages for verbose feature

src/common/debug.c
There was a serious issue in verbosing feature. Some messages were
missing in log file. It is fixed by opening log file in append mode
in both library and probes.
=> Fix opening a log file

src/OVAL/probes/SEAP/seap.c, src/OVAL/probes/probe/icache.c, src/OVAL/probes/probe/input_handler.c, src/OVAL/probes/probe/main.c, src/OVAL/probes/probe/signal_handler.c, src/OVAL/probes/probe/worker.c
Thread names should be set inside the thread routine.
This fixes a segfault which might happen when a thread terminates
sooner than its name could be set.
=> Move setting thread names to a right place

src/OVAL/oval_session.c
With those few messages we would slowly start to see
the "story of OVAL evaluation" in the log file.
=> Add new messages to OVAL session

src/OVAL/oval_probe_ext.c, src/source/oscap_source.c
This pull request brings two very small improvements to verbose output, This pull request contains two commits. First commit improves a message regarding URI probe that is going to be started. Second commit adds a message that a SCAP content validation will be proceeded. It can be quite useful when we would like to see in log which documents are evaluated and which schema version  is used.
=> Small message improvements

utils/scap-as-rpm
Chances are that the rpmbuild failure is not a problem in our source,
but in the inputs given to the tool.
Otherwise, we receive unneeded Abrt reports like
https://retrace.fedoraproject.org/faf/reports/723484/
=> Avoid traceback on rpmbuild errors

src/OVAL/probes/probe/input_handler.c
This will clean of a lot of unimportant mess from the log, if user sets `--verbose INFO`.
=> Change category of messages to DEVEL

src/XCCDF/xccdf_session.c
Basically, this adds a new information message to the XCCDF session which tells a reader that new XCCDF session was created.
When I looked into the code, I realized that we repeat some code there. See the commit messages. I have fixed it.
=> Add an info message + refactor

xsl/xccdf-report-impl.xsl
OpenSCAP was not able to show SCE results from external SCE results file
in the HTML report, because incorrect XPath expression was in our XSLT
template which is used to genarate the HTML report.
According to the XCCDF specification, the path to the external SCE results file
should be found in a "href" attribute of a "check-content-ref" element.
But we were trying to get it from a "check" element, where it shouldn't be.
This caused I/O warnings. In my opinion there must be some cases when
some information would be missing in a HTML report.
=> RHBZ#1275369: Fix retrieving SCE results from external results file

src/source/oscap_source.c
We should use here xmlSetGenericErrorFunc instead of initGenericErrorDefaultFunc
because initGenericErrorDefaultFunc resets only error handler, but we must
also reset the error context, which is possible only by xmlSetGenericErrorFunc.
=> Issue #231: Fix a segmentation fault

src/OVAL/probes/probe/worker.c
These messages are not important from OVAL content point of view.
We should put them to devel level to improve readability of log.
=> Change category of messages in worker routine to devel

src/OVAL/oval_sexp.c
For the evaluation process it is not useful to know that
an object was decoded from SEXP successfully. It seems
to be a message for a developer.
=> Change category of a message to devel

src/OVAL/oval_component.c, src/OVAL/oval_probe.c, src/OVAL/oval_variable.c
There is a very often used construction in the OVAL language: A state can reference a local variable, which can reference a object. This object needs to be evaluated and affects final result of currently evaluated definitions. This indirect references are often used in SCAP Security Guide, eg. in definition `gid_passwd_group_sane`. That's the reason it should be covered in the verbose log.
This pull request wants to introduce new information messages that will inform user about this process. Together with other messages already introduced in OpenSCAP, this pull request can help to better understand this indirect object referencing in OVAL.
=> Inform users about indirect references of objects

src/OVAL/oval_sexp.c
In OVAL objects, object components can have var_ref attribute,
using him it is possible to reference a variable. This variable
affects the final content of a collected object. This is one of
tricky things in OVAL, so it may be useful to report it in log.
=> Inform about referencing variable in a object component

tests/sce/Makefile.am, tests/sce/empty_stdout.sh, tests/sce/test_check_engine_results.sh, tests/sce/test_check_engine_results.xccdf.xml
This pull request proposes a test to test "--check-engine-results" together with "--report" options on SCE content. The test is performed with SCE check which doesn't produce any output. Such checks caused segfaults or warnings in past when OpenSCAP tried to use the empty output in reports.  See issue #231 and RHBZ #1275369. These issues are fixed now, but we should have a test to avoid regression in future.
=> Add a new test for SCE module

utils/oscap_docker_python/oscap_docker_util.py
We have started using packed .bz2 files instead of .xml and there was hard-coded path in code twice. 
So we download content somewhere, but we use different path as oscap argument.
I've probably tested it before with system /usr/lib/*/site-packages by mistake, so it passed the tests.
```
[ybznek@localhost openscap]$ sudo oscap-docker image-cve fedora
OpenSCAP Error: Unable to open file: '/tmp/Red_Hat_Enterprise_Linux_7.xml' [oscap_source.c:221]
Command: oscap oval eval /tmp/Red_Hat_Enterprise_Linux_7.xml failed!
Error was:
Command '['oscap', 'oval', 'eval', '/tmp/Red_Hat_Enterprise_Linux_7.xml']' returned non-zero exit status 1
```
=> oscap-docker: fix CVE path

tests/API/OVAL/unittests/Makefile.am, tests/API/OVAL/unittests/all.sh, tests/API/OVAL/unittests/test_skip_valid.oval.xml, tests/API/OVAL/unittests/test_skip_valid.sh
This test tests "oscap oval eval" with "--skip-valid" option
on invalid OVAL content. The tested content references a not
existent state. This situation was one of two reasons of
a segmentation fault, described in issue #191.
The issue #191 has been fixed already. This commit wants to
test it to avoid regressions in future.
=> Test behavior of OVAL module with invalid OVAL content

README.md
Add bzip2-devel build dependency to the 'README.md' file.
=> Fix issue #262: Docs: Missing build dependency in README.md

src/CCE/Makefile.am
When configuring OpenSCAP with the --enable-cce flag and building OpenSCAP, the following error message is produced: "cce.c:40:26: fatal error: oscap_source.h: No such file or directory".
Solution to this problem consists in adding the '-I$(top_srcdir)/src/source/public' to the 'libcce_la_CPPFLAGS' directive of the "src/CCE/Makefile.am" file.
=> Fix issue #264: Path to 'oscap_source.h' header file is missing

src/source/bz2.c
Coverity scan has reported NEGATIVE_RETURNS defect.
The "dup(fd)" was passed to a parameter that cannot be negative.
This commit fixes the issue by checking the value for possible -1.
=> Fix wrong check of return value

src/OVAL/probes/unix/sysctl.c
Variable "fp" going out of scope leaks the storage it points to.
We should close the file.
=> Fix a resource leak reported by coverity scan

src/OVAL/results/oval_status_counter.c
Coverity scan has reported this function may return unitialized value.
Although it is not likely to happen, it is easily to fix it.
=> Fix using uninitialized value

src/OVAL/probes/probe/worker.c
Fixing a resource leak reported by coverity scan.
SEXP_string_cstr allocates memory which was not freed.
Pay attention that SEXP_string_cstr is a confusing name,
because it returns "char *", not "const char *".
Therefore the return value must be freed after use.
=> Plug a memory leak

src/OVAL/oval_entity.c
When a variable is not found in OVAL document, then OpenSCAP should
write an error message and finish correctly.
=> Issue #277: Fix a segmentation fault

src/common/debug.c, src/common/debug_priv.h
Do not depend on an environment variable.
Now we will use behavior which used to be default.
Showing the full filepath is not as helpful to slow down the program
by reading an environment variable.
=> Always strip the source file path

src/OVAL/oval_test.c, src/OVAL/probes/SEAP/sexp-value.c, src/OVAL/probes/oval_fts.c, src/OVAL/probes/probe/entcmp.c, src/OVAL/probes/probe/input_handler.c, src/OVAL/probes/unix/xinetd.c, src/OVAL/results/oval_resultTest.c
All messages should not finish with '\n'.
=> Reviewed linebreaks in multiline calls of debugging macros

src/OVAL/oval_agent.c, src/OVAL/oval_component.c, src/OVAL/oval_probe.c, src/OVAL/oval_schema_version.c, src/OVAL/oval_session.c, src/OVAL/oval_sexp.c, src/OVAL/oval_variable.c, src/OVAL/probes/oval_fts.c, src/OVAL/probes/probe/entcmp.c, src/OVAL/probes/unix/file.c, src/OVAL/probes/unix/gconf.c, src/OVAL/probes/unix/linux/systemdshared.h, src/OVAL/probes/unix/linux/systemdunitdependency.c, src/OVAL/probes/unix/linux/systemdunitproperty.c, src/XCCDF/result_scoring.c, src/XCCDF/xccdf_session.c, src/XCCDF_POLICY/xccdf_policy.c, src/common/debug.c, src/source/doc_type.c, src/source/oscap_source.c
To allow to change or redesign the format of verbose log we have to remove
line breaks at the end of some messages. Then it will be possible to move
the message to the begining or middle of a line without any hacks.
The commit also enforces usage of dI, dE, dW macros instead of
ocassionaly appearing oscap_dlprintf macro. This change makes
codebase more consistent regarding the debugging.
This is a continuing of work done in PR#282, which has already removed
the line breaks from maint-1.0 branch.
=> Remove linebreaks from debug messages in maint-1.2

src/XCCDF_POLICY/xccdf_policy.c, tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/test_xccdf_role_unscored.sh, tests/API/XCCDF/unittests/test_xccdf_role_unscored.xccdf.xml
A rule with unscored role should not be counted in score.
XCCDF sepcification says about xccdf:Rule/@role="unscored":
if the rule is selected, then check it and include the results in
any report, but do not include the result in score computations.
This pull request fixes counting scores to be in line with specification.
This pull request also adds test tests counting scores of rules with role attribute set
to "unscored" on all 4 scoring models.
=>  Issue #272: XCCDF rule unscored role is not working

src/common/oscap_acquire.c
As from the libcurl API documentation,
http://curl.haxx.se/libcurl/c/curl_easy_init.html
we should call curl_global_init to initialize the libcurl library
and curl_global_cleanup to clean the memory.
We should not rely on the fact that it would be called automatically.
=> Use global functions to initialize libcurl

src/OVAL/oval_component.c, tests/API/OVAL/unittests/Makefile.am, tests/API/OVAL/unittests/all.sh, tests/API/OVAL/unittests/test_object_component_type.oval.xml, tests/API/OVAL/unittests/test_object_component_type.sh
This pull request wants to introduce two commits to improve experience of indirect referencing of OVAL object within an OVAL variable, which is often considered as difficult part of the OVAL language.
First commit removes TODOs in _oval_component_evaluate_OBJECTREF() function by implementing error reporting as required by OVAL specification:
> If an entity is not found with a name that matches the value of the item_field an error should be reported when determining the value of an variable.
Similar statement applies also for entities of the record data type.
Second commit implements a test for this feature.  It tests whether The ObjectComponentType complex type is processed correctly.  It contains one correct case and two cases which should lead to report an error. For details see …
=> Report errors on evaluation of object component of a variable + TEST

tests/suppressions.supp
Valgrind reports memory leaks when using curl_easy_init(),
but we clean the memory correctly.
=> Add libcurl leak to valgrind suppression file

src/OVAL/probes/SEAP/seap-packet.c, src/common/debug.c
From my observations, I think that the current format of verbose log is difficult to read and important information are lost in metadata.
Here are the major drawbacks of the current approach:
1) The message is at the end of the line, preceded by a lot of metadata.  User has to read the metadata before he can read information that interests him.
2) Moreover, if an user has a narrow terminal window, he has to scroll left and right, which is horribly annoying.
3) Information about verbosity level (in other words importance of the message) is shown in the middle of the line, which makes difficult to distinguish warnings from informational messagess etc.
4) Some metadata , eg. PID, thread id, line number, source file, are interesting only for a OpenSCAP developer. Content developer or final …
=> Improve format of verbose log

src/OVAL/oval_sexp.c
OVAL objects can contain optional filter element. The filter
references a state. The filter can exclude or include items
conforming to the state from the set of collected objects.
Since the filter can significantly affect the result of
object evaluation it would be nice to inform user about
processing the filter. This commit adds a short message to the
verbose log.
=> Add a message about filter used within an object

src/OVAL/oval_probe_ext.c, src/OVAL/probes/SEAP/seap-message.c, src/OVAL/probes/SEAP/seap-packet.c, src/OVAL/probes/SEAP/sexp-manip.c, src/OVAL/probes/probe-api.c, src/OVAL/probes/probe/signal_handler.c, src/OVAL/probes/probe/worker.c
These messages has not value from the OVAL evaluation point of view.
They may be interesting for OpenSCAP developers, so they should
have DEVEL category.
=> Change messages category to DEVEL

src/XCCDF_POLICY/xccdf_policy_remediate.c
Using just NULL is discouraged and nonportable, see `man 2 execve`.
This commit doesn't change behavior, just improves portability.
=> Use { NULL } instead of NULL as envp when executing remediations

src/XCCDF_POLICY/xccdf_policy_remediate.c
This makes content author's life a little bit easier. The change doesn't
break any existing remediations but new remediations relying on these
PATHs won't work with old openscap!
=> Use canonical PATH when executing remediations

src/common/debug.c
Static modifier made the pointer to log file unreachable
from other modules. It caused that some debug messages from some
functions (eg. SEXP_list_sort()) could not be printed into log.
This commit fixes the bug by removing the 'static' modifier.
=> Fix scope of a global variable

utils/oscap-vm
Hello,
these are more of cosmetic changes, self-explanatory I guess, except for the introduction of `fusermount -u`. Originally used `guestunmount` is wrapper of `fusermount -u`, which provides option to wait for unmounting. But usecase in `oscap-vm` does not necessitate this, thus both commands should be interchangeable.
And reasoning is, that some distributions, for example RHEL6, does not have `libguestfs` up-to-date enough to provide `guestunmount` command :)
=> oscap-vm cosmetic changes

tests/suppressions.supp
After merging c97417a328687ebf49f4da0ac54d6104d15297c7, we must suppress
the memory leak in curl_global_init directly, not via curl_easy_init.
=> Adjust the valgrind suppression file

src/OVAL/probes/SEAP/seap.c
These messages informs about some details in communication protocol
between library and probes. They are not interesting from point of
view of OVAL content.
=> Change category of two messages to DEVEL

tests/probes/process58/command_line.sh
Voodoo: Tell us where is zombie
We think she left dead, but the priest (ps) conceals where it is.
This is not a black magic really. We think the zombie process should be
listed in cemetery, but sometimes it is missing. Good thing is to put
more details into the log. Next time we need to record the moon phase.
See github issue #315 for more details.
=> Desperate grave digger

src/OVAL/results/oval_resultTest.c
This message informs that some item of a collected object has matched a state.
=> Add an info message

src/OVAL/results/oval_resultDefinition.c
Verbose log is missing the most basic information - final result of a definition.
=> Show definition result in verbose log

src/OVAL/oval_probe.c
We currently inform user that a definition will be evaluated,
but definition contains one or more tests, and we currently
don't show it in log, which complicates the understanding
of whole story.
=> Inform user in verbose log that a test will be evaluated

src/OVAL/oval_probe.c
In OVAL the definitions usually contain one or more tests,
but they can also be extended by referencing to other definitions.
The refrenced definitions are required to be evaluated to get
final result of the definition under the evaluation.
This construct is sometimes used in SSG.
Currently we don't show the information about extending definition
in verbose log. The log is very confusing for a reader if a
extended definition is evaluated.
This commit adds an info message when extend_definition is used.
=> Add message about extend definition

utils/oscap-docker.in
The oscap-docker utility failed with a traceback with Python 3
whe invoked with no argument.
It will print the help instead.
=> Issue #303: Fix oscap-docker traceback

src/OVAL/oval_probe.c
Currently we show only test id in log message.
However, if we show only id, user will need look
to the OVAL file to figure out which test is which.
We can easily improve it by adding object type and its comment
into the message.
=> Show type of test and test comment in verbose log

src/OVAL/oval_definitions_impl.h, src/OVAL/oval_enumerations.c, src/OVAL/oval_test.c, src/OVAL/public/oval_definitions.h, src/OVAL/results/oval_resultTest.c
In this pull request I would like to introduce some very basic informational messages that can help user of the verbose mode to figure out the reasons of OVAL test results.
(More will follow, but I think it will be in another pull request.)
=> Provide basic information about evaluating test results in verbose log

src/OVAL/probes/oval_fts.c
We can show a more understandable message
when a probe opens some file (eg. configuration file)
to collect data.
=> Improve a message about opening file

src/OVAL/probes/unix/linux/rpmverify.c, src/OVAL/probes/unix/linux/rpmverifyfile.c, src/OVAL/probes/unix/linux/rpmverifypackage.c, src/OVAL/probes/unix/symlink.c
I have done simple beaker test using oscap-docker for these probes, so these probes should really work.
=> Maint 1.2 offline scan tested probes

ac_probes/configure.ac.tpl, configure.ac, utils/Makefile.am, utils/oscap-chroot, utils/oscap-chroot.8
A very very small command-line tool with no dependencies outside `oscap`. The only thing it does is setup environment variables correctly for `oscap` for running it for a chroot.
I could do all of this inside the daemon but I'd prefer to have the logic neat and simple so I created it as a separate script. We could also decide we don't want this in OpenSCAP and just ship it with the daemon but I think that would be a shame. This makes a few use-cases simpler.
Let me know what you think!
=> Added the oscap-chroot tool - scan filesystems on arbitrary paths

utils/oscap_docker_python/oscap_docker_util.py
Oscap-docker gave a traceback when providing a wrong image ID
or wrong container ID.
This commit fixes the traceback by catching the exception
and writes an error message on stderr.
=> Issue #317: Fix oscap-docker traceback

ac_probes/configure.ac.tpl, configure.ac, src/OVAL/probes/SEAP/seap.c, src/OVAL/probes/probe/icache.c, src/OVAL/probes/probe/input_handler.c, src/OVAL/probes/probe/signal_handler.c, src/OVAL/probes/probe/worker.c, src/OVAL/probes/unix/linux/rpmverifypackage.c, src/common/debug.c
Functions pthread_getname_np and pthread_setname_np were introduced
in glibc 2.12. With older versions of glibc used on RHEL5 or SLES11
OpenSCAP failed to compile. This commit adds an autoconf rule
to detect the presence of these functions.
See mail thread on our mailing list https://www.redhat.com/archives/open-scap-list/2016-March/msg00000.html
=> Fix compiler errors on older systems

src/OVAL/probes/unix/file.c
I have found a logical error in file probe.
The offline mode in file probe is enabled on only when a mutex cannot be initialized,
which is not very likely and also it is definitely not what we want.
This commit enables the offline mode in file probe.
=> Fix offline mode in file probe

src/OVAL/probes/unix/linux/rpminfo.c, src/OVAL/probes/unix/linux/rpmverifyfile.c
If we chroot into filesystem where is not a RPM database,
we should not fail to init the probe.
=> Issue #348: Fix offline mode in rpmverifyfile probe

tests/API/XCCDF/applicability/test_platform_element.sh
When oscap finish successfully, $ret is not set and
we will get 'line 15: [: -eq: unary operator expected'
=> test: XCCDF/test_platform_element fix var

docs/manual/manual.adoc, src/OVAL/probes/SEAP/sch_pipe.c, src/common/debug.c, utils/oscap-tool.c, utils/oscap-xccdf.c
This pull request proposes a small enhancement in OpenSCAP verbose mode, based on feedback from developers team.
The `--verbose-log-file` will no longer be obligatory with verbose mode. When this option won't be specified, the messages will be written on stderr.
I hope this will make our developer's life a little easier.
Also edited the user manual to reflect this change.
=> If verbose log file is not specified, write messages on stderr

src/OVAL/oval_agent.c, src/OVAL/oval_probe.c, src/OVAL/oval_probe_impl.h, src/OVAL/results/oval_resModel.c, src/OVAL/results/oval_resultDefinition.c, src/OVAL/results/oval_resultTest.c, src/OVAL/results/oval_results_impl.h
Currently, we do two steps to get the results of a definition:
1) Querying probes for objects for all the definitions
2) After all items are collected, we compute results separately.
It causes some confusion in the verbose log in cases one definition contains multiple criteria,
the messages are not in logical order here.
I think that messages describing computing results of a test should be displayed just after messages describing evaluation of the same test, it should not be mixed as is now.
We can fix this by merging aforementioned steps into single step.
It would basically mean that each test is evaluated separately, no other querying starts before a result of single test is done.
Therefore we would have messages in verbose mode in expected order.
This pull request is a rework of #333. …
=> Query test and evaluate its results in one step

cpe/openscap-cpe-oval.xml
When we cannot get RPM database, we should return "NOT APPLICABLE".
Problem is so, that if we get
isUnix(TRUE) AND isFedora(not applicable) we get TRUE -> so for all systems we get TRUE
=> Fix openscap-cpe-oval.xml: Remove check to unix family

src/OVAL/probes/unix/linux/rpminfo.c, src/OVAL/probes/unix/linux/rpmverify.c, src/OVAL/probes/unix/linux/rpmverifyfile.c, src/OVAL/probes/unix/linux/rpmverifypackage.c
https://github.com/OpenSCAP/openscap/issues/348
Currently this fix breaks CPE results (problem should be in OVAL, not in this PR) -> Merge after https://github.com/OpenSCAP/openscap/pull/362
=> RPM probes: return "Not applicable" without valid db

src/OVAL/oval_probe.c, src/OVAL/results/oval_resultCriteriaNode.c
Since we have merged PR #360, we miss a message reporting extended
definition in our verbose mode. This commit moves a message from
function which is not used now to the right place.
=> Move a message from unused code

src/OVAL/oval_agent.c, src/OVAL/oval_probe.c, src/OVAL/results/oval_resultDefinition.c, src/OVAL/results/oval_resultTest.c
After we have involved probing for  definitions into results evaluation, we can move some of info messages to their proper place.
This pull request contains two very similar commits. First of them is related to OVAL definitions, second is related to OVAL tests. The commits just move messages "Evaluating .." nearer to  actual evaluation in source code.
=> Move messages to results model

src/OVAL/public/oval_probe.h
We have moved querying definitions into results model and
removed call of oval_probe_query_definition in
b8e8860fa362b37201f3f46cb6f3dc1da6863246 .
The only case where this function is called now (oval_probe.c:433)
is a recursive call.
We can deprecate the function and remove it in next major release,
because it is a dead code.
=> Deprecate function oval_probe_query_definition

src/OVAL/oval_session.c, src/OVAL/probes/unix/runlevel.c
This check-in implements the run-level probe for SUSE as was discussed on the mailing list.
If have implemented the function separate from get_runlevel_sysv because the file paths to init.d and the rc directories are different on SUSE and there was no GCC macros to distinguish between RHEL and SUSE.
Also included the linux/limits.h header file in oval_session.c to resolve PATH_MAX.
=> Adding implementation for runlevel probe on SUSE

src/OVAL/probes/unix/runlevel.c
Addressing:
unix/runlevel.c: In function ‘get_runlevel_redhat’:
unix/runlevel.c:227:13: warning: unused variable ‘runlevel_list’ [-Wunused-variable]
const char runlevel_list[] = {'0', '1', '2', '3', '4', '5', '6'};
=> Fix compiler warning: unused variable

src/OVAL/probes/Makefile.am, src/OVAL/probes/unix/linux/rpm-helper.c, src/OVAL/probes/unix/linux/rpm-helper.h, src/OVAL/probes/unix/linux/rpminfo.c, src/OVAL/probes/unix/linux/rpmverify.c, src/OVAL/probes/unix/linux/rpmverifyfile.c, src/OVAL/probes/unix/linux/rpmverifypackage.c
It is part of https://github.com/OpenSCAP/openscap/issues/379
Main reason to this pull request is - https://github.com/OpenSCAP/openscap/issues/368.
To add error handler to rpm functions I had to copy same function to all four probes - in rpm-helper.c file will be the callback function.
=> RPM probes - refactoring only

tests/API/XCCDF/applicability/all.sh, tests/API/XCCDF/tailoring/all.sh
The two modified script files explicitly parse the formatted file
by xpath command, which act the same as the assert_exists function
in tests/test_common.sh.
=> Reuse existing function during the check

src/OVAL/probes/unix/linux/rpm-helper.c, src/OVAL/probes/unix/linux/rpm-helper.h, src/OVAL/probes/unix/linux/rpminfo.c, src/OVAL/probes/unix/linux/rpmverify.c, src/OVAL/probes/unix/linux/rpmverifyfile.c, src/OVAL/probes/unix/linux/rpmverifypackage.c
Handle RPM error.
```dE()``` seems not to be very good solution for this, but when somebody tries to scan debian - it is valid to get error.
maint-1.2 result
```
E: probe_rpminfo: RPM: Failed to initialize NSS library
[probe_rpminfo(27732):probe_rpminfo(7f0108644800):rpm-helper.c:29:rpmErrorCb]
```
=> rpm error handler

src/OVAL/probes/unix/sysctl.c
/proc/sys/fs/binfmt_misc is on different device than rest of /proc/sys
(stat /proc/sys/fs/binfmt_misc). This commit enable to scan it too
More info https://github.com/OpenSCAP/openscap/issues/258
=> probes/sysctl: Enable scan 'files' through different devices

docs/manual/manual.adoc
The spec files are not present in maint-1.2 anymore.
They were removed in commits
3fe208f3caf1f3a46cd2ee2ea7baa88154600674
41fe1106a680885cd684313d306c12eb54d4353d
=> Remove information about spec files from user manual

tests/probes/sysctl/Makefile.am, tests/probes/sysctl/all.sh, tests/probes/sysctl/test_sysctl_probe_all.oval.xml, tests/probes/sysctl/test_sysctl_probe_all.sh
I've added check for deprecated parameters according to sysctl command.
Sysctl command check it in the same way since Mon Feb 13 21:21:43 - check only filename, not path.
https://github.com/OpenSCAP/openscap/issues/258
=> sysctl - test

src/OVAL/probes/probe/Makefile.am, src/OVAL/probes/probe/main.c, src/OVAL/probes/probe/preload.c, src/OVAL/probes/public/probe-api.h, src/OVAL/probes/unix/linux/rpm-helper.c, src/OVAL/probes/unix/linux/rpm-helper.h, src/OVAL/probes/unix/linux/rpminfo.c, src/OVAL/probes/unix/linux/rpmverify.c, src/OVAL/probes/unix/linux/rpmverifyfile.c, src/OVAL/probes/unix/linux/rpmverifypackage.c
Replaces https://github.com/OpenSCAP/openscap/pull/386
(It could be possible to divide it to more pull request, but it would delay merging.)
- I have deleted callback log function of rpm, because I didn't understand well function interface.
- libgcc_s is loaded before chroot due to call of pthread_cancel()
- rpm dynamic libraries are loaded from host, not from container as before
- ```disable_library_loading()``` I wasn't able so far to find right way how to implement it.
I've asked in mailing list and hope I will get some answer.
=> probes dynamic library preloading

src/DS/sds.c, src/common/public/oscap.h, src/source/doc_type.c, utils/oscap-info.c
Oscap ds sds-compose does not recognize OCIL file as SCAP-1.2
check system and places it into <ds:extended-components>
element (intended for non-SCAP content) rather into
<ds:checks> element (intended for SCAP-1.2 check systems)
That caused build problems in SSG - error message displayed
and invalid datastream created.
This commit adds basic support for including OCILs in data streams.
=> Issue #364: Fix OCIL in data streams

src/XCCDF/xccdf_session.c
Loading session for a DS file multiple times with different XCCDF IDs
didn't work. When a session for a data stream is created using Python API
and then it is loaded twice with different XCCDF IDs being set,
the session doesn't reflect the change of the XCCDF ID.
This commit fixes the regression by resetting the DS session
when a new XCCDF session is loaded. Therefore the IDs are resetted.
=> RHBZ#1250072: Fix regression in loading DS session

docs/manual/manual.adoc, lib/flock.c, lib/flock.h, src/OVAL/oval_agent.c, src/OVAL/oval_component.c, src/OVAL/oval_session.c, src/common/debug.c, src/common/public/oscap_debug.h
- Implement OSS version of flock and setenv that can be used only by MinGW.
- Use custom get_program_name function for WIN32.
- Fix various issues when using --disable-probes.
- Update Windows cross-compilation instructions.
- Update #195
=> Windows build fixes

utils/oscap-xccdf.c
- /r was creating weird output in Windows Command Prompt
- Windows Command Prompt does not use ANSI so use correct non-ANSI terminal colors
- Part of #195
=> [Bugfix][WIN] Fix terminal output and colors for Windows systems

src/XCCDF/benchmark.c
Related to https://github.com/OpenSCAP/scap-workbench/issues/63
Addressing:
```
Invalid free() / delete / delete[] / realloc()
at 0x4C29CF0: free (vg_replace_malloc.c:530)
by 0x4EC6DD5: xccdf_benchmark_import (benchmark.c:70)
by 0x40CD38: app_info (oscap-info.c:151)
by 0x4079BD: oscap_module_call (oscap-tool.c:261)
by 0x4079BD: oscap_module_process (oscap-tool.c:346)
by 0x4069BE: main (oscap.c:79)
Address 0xc84a6a0 is 0 bytes inside a block of size 312 free'd
at 0x4C29CF0: free (vg_replace_malloc.c:530)
by 0x4EC6C97: xccdf_benchmark_parse (benchmark.c:145)
by 0x4EC6D54: xccdf_benchmark_import (benchmark.c:65)
by 0x40CD38: app_info (oscap-info.c:151)
by 0x4079BD: oscap_module_call (oscap-tool.c:261)
by 0x4079BD: oscap_module_process (oscap-tool.c:346)
by 0x4069BE: main (oscap.c:79)
Block …
```
=> Fix a double free

README.md
This package is needed to build gconf probe.
=> Add GConf2-devel to build dependencies list

src/XCCDF/xccdf_session.c
Addressing:
```
oscap_source_free (source=0x13313d90) at oscap_source.c:129
0x00007ffff7b8ac5e in xccdf_session_free (session=0x61cb30) at xccdf_session.c:249
0x000000000040ba1f in app_evaluate_xccdf (action=<optimized out>) at oscap-xccdf.c:548
0x0000000000407f8e in oscap_module_call (action=0x7fffffffd7b0) at oscap-tool.c:261
oscap_module_process (module=0x6154c0 <XCCDF_EVAL>, module@entry=0x614a40 <OSCAP_ROOT_MODULE>,
argc=argc@entry=6, argv=argv@entry=0x7fffffffda48) at oscap-tool.c:346
0x000000000040702f in main (argc=6, argv=0x7fffffffda48) at oscap.c:80
```
=> Issue #370: Fix a segmentation fault

src/source/oscap_source.c
When oscap reports that the document is invalid, it reports
against which schema it is invalid. However if the generator
element is missing the schema version is unknown.
This commit handles a situation when schema version is missing.
=> Issue #345: Fix error message when <generator> is missing

tests/sce/Makefile.am, tests/sce/bash_list.sh, tests/sce/test_sce_in_report.sh, tests/sce/test_sce_in_report.xml, utils/oscap-xccdf.c, utils/oscap.8
This pull request tries to fix issues related to generating a HTML report form XCCDF with SCE checks.
This pull request contains three commits:
1) Add into man page a description for already existing, but undocumented option "--sce-template"
2) Add missing default template for SCE results
3) A new simple test checking whether SCE script stdout is shown in the HTML report
Thanks for review && comments.
=> Fix Issue #394 (SCE results aren't embedded in XCCDF reports) + test

utils/oscap_docker_python/oscap_docker_util.py
Fix:
https://github.com/OpenSCAP/openscap/issues/426
Changes:
- Print error message when target is not rhel based
- unmount container when exception error occur
=> oscap-docker: *-cve scan of non-rhel fix

src/OVAL/probes/independent/filehash.c, src/OVAL/probes/independent/filehash58.c
The option was enabled too late -> when probe initialization failed -> we got error message, that offline scan is not supported.
=> Offline scan option position

src/OVAL/probes/unix/fileextendedattribute.c
https://github.com/OpenSCAP/openscap/issues/424
Should fix:
- `while (i < xattr_buflen && xattr_buf[i] != '\0') ++i;`  - When loop was going through `\0` separeted buffer, one time index `i` started to point to character `\0` and it never went after that character
- attributes in results didn't contain trailing \0
- replace goto by do while
=> probe extended attribute fix

configure.ac, src/OVAL/probes/Makefile.am
Changes made recently in src/OVAL/probes/Makefile.am caused that
./confgen.sh removed check macros for header files that are needed
for rpm probes from configure.ac.
This commit fixes the syntax of respective Makefile.am and also
includes freshly generated configure.ac.
=> Fix autoconf issues

ac_probes/configure.ac.tpl, configure.ac, src/OVAL/probes/unix/linux/rpm-helper.c, src/OVAL/probes/unix/linux/rpm-helper.h, src/OVAL/probes/unix/linux/rpminfo.c, src/OVAL/probes/unix/linux/rpmverify.c, src/OVAL/probes/unix/linux/rpmverifyfile.c, src/OVAL/probes/unix/linux/rpmverifypackage.c
Function rpmLogSetCallback has changed its prototype in RPM 4.6 API.
Before it had only one parameter, now it has two parameters.
Older version (RPM 4.4.x) is shipped in RHEL5, therefore we must use
conditional compilation to get the rpm probes compiled on RHEL5.
=> Issue #408: Fix compilation on older systems

ac_probes/configure.ac.tpl, configure.ac, src/OVAL/probes/Makefile.am, src/OVAL/probes/probe/Makefile.am, src/OVAL/probes/probe/main.c, src/OVAL/probes/probe/offline_mode.c, src/OVAL/probes/probe/probe.h, src/OVAL/probes/public/probe-api.h, src/OVAL/probes/unix/linux/probe-chroot.c, src/OVAL/probes/unix/linux/probe-chroot.h, src/OVAL/probes/unix/linux/rpm-helper.c, src/OVAL/probes/unix/linux/rpm-helper.h, src/OVAL/probes/unix/linux/rpmverifypackage.c
- should fix rpmverify package offline scan issue - use chroot back to host root to load libraries
- some of commits are not part of the PR - I need them to passing tests - before merging they will be removed
Questions:
- what do you think about `probe_offline_mode()? - currently no other probe use it, I would like to use it in all probes
=> Fix offline scan of rpmverifypackage

tests/valgrind_test.sh
If we use memory in bad way, this should increase possibility of test fail during valgrind test. I hope it will helps us to find problems.
Memory after malloc and free will be set to "UUUU..."
=> Valgrind_test: Add free-fill, malloc-fill

src/OVAL/oval_probe.c, tests/API/OVAL/report_variable_values/report_variable_values.def.xml
This pull request:
1) fixes invalid OVAL file in our upstream test suite (fixes warnings reported by schemtaron validation)
2) introduces a check for this kind of invalid content into OpenSCAP to ensure that we do not process invalid content
This pull request fixes issue #401.
Replaces PR #446 .
=> Issue #401: OVAL tests can reference only objects of same type

src/OVAL/probes/unix/linux/rpm-helper.c, src/OVAL/probes/unix/linux/rpm-helper.h, src/OVAL/probes/unix/linux/rpminfo.c, src/OVAL/probes/unix/linux/rpmverify.c, src/OVAL/probes/unix/linux/rpmverifyfile.c, src/OVAL/probes/unix/linux/rpmverifypackage.c
Recently we have merged a fix to compile the rpm probes
on maint-1.0 on systems with older versions of rpmlib.
However, the reporting function  is not present there,
so it does not make any sense to set the logging callback,
because it has no effect. This commit removes the callback
on those systems.
=> Remove callback on RPM < 4.6

ac_probes/configure.ac.tpl, configure.ac, src/OVAL/probes/unix/linux/rpm-helper.h, src/OVAL/probes/unix/linux/rpmverifyfile.c
One missing include and some fallback definition of macros
will fix the issue.
=> Issue #393: Fix rpmverifyfile compilation on RHEL5

src/XCCDF/result.c, src/XCCDF_POLICY/xccdf_policy.c, tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/test_xccdf_test_system.sh, tests/API/XCCDF/unittests/test_xccdf_test_system.xccdf.xml
The xccdf:TestResult element should contain a test-system
attribute which is defined in specification as follows:
Name of the benchmark consumer program that generated this
<xccdf:TestResult> element; SHOULD be either a CPE name or a
CPE applicability language expression.
=> Issue #372: Add xccdf:TestResult@test-system attribute

src/XCCDF/result.c, tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/test_remediation_invalid_characters.sh, tests/API/XCCDF/unittests/test_remediation_invalid_characters.xccdf.xml
We include stdout of a remediation script to the XCCDF results.
But the output of the remediation script can contain characters
that are forbidden in XML documents, eg. most of the non-printable
characters. We need to escape or remove them from the string
before we include it to the XML document. Libxml provides a
function to get rid of those characters.
=> Issue #281: Fix invalid characters in remediation results

tests/test_common.sh
Should fix https://github.com/OpenSCAP/openscap/issues/461
If newer version of xpath is installed, wrapper will translate parameters from old format
Similar solution is in arch linux package https://aur.archlinux.org/packages/openscap
=> xpath wrapper

tests/probes/systemdunitproperty/Makefile.am, tests/probes/systemdunitproperty/all.sh, tests/probes/systemdunitproperty/test_probes_systemdunitproperty.xml, tests/probes/systemdunitproperty/test_probes_systemdunitproperty_mount_wants.sh, tests/probes/systemdunitproperty/test_probes_systemdunitproperty_mount_wants.xml
"-.mount Wants" isn't presented on Fedora24, so part of test
was separated and now it should be tested only on "supported systems"
mostly copy & paste
=> Fix systemd test on fedora24

lib/assure.h, lib/sys_file.in.h, m4/flock.m4, m4/sys_file_h.m4
I think, these files weren't added in https://github.com/OpenSCAP/openscap/commit/c2df217ccd334e739072d236d846ffa3e7be4277
should fix https://github.com/OpenSCAP/openscap/issues/471
Source of files:
```
git clone git://git.savannah.gnu.org/gnulib.git
gnulib-tool --update
```
=> gnulib: Add missing files (master branch)

src/OVAL/oval_agent.c, src/OVAL/oval_probe_session.c, src/OVAL/public/oval_probe_session.h
https://github.com/OpenSCAP/openscap/issues/478
probe_session were referenced from two places. 
- oval_agent_session
- oval_agent_session->res_model (https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/results/oval_resultTest.c#L933)
When we create new session in oval_agent_reset_session, res_model will still use old pointer to free'ed memory.
`oval_probe_session_reinit` could be in OSCAP_HIDDEN in maint-1.2oval_probe_session_reinit
---
Another solution is add setter to res_model to set probe_session, but IMHO, my solution is ~~clean~~ cleaner.
=> Fix usage of probe_session after free

src/OVAL/oval_sysEnt.c
https://github.com/OpenSCAP/openscap/issues/469
=> oval_sysEnt.c: fix invalid characters in oval results

src/OVAL/oval_sysEnt.c, src/XCCDF/result.c, tests/API/XCCDF/unittests/test_remediation_invalid_characters.sh, tests/API/XCCDF/unittests/test_remediation_invalid_characters.xccdf.xml
We have recently merged some changes to fix not escaped invalid characters.
But our solution was causing, that characters like <,>,.. were escaped twice
=> Fix double escape + test fix

README.md
The header file dbus.h provided by the dbus-devel package is required
to build systemd probes, we should list the package in our build
dependencies list.
=> Add a missing build dependency to README

src/OVAL/probes/independent/filehash.c, src/OVAL/probes/independent/filehash58.c, src/OVAL/probes/independent/filemd5.c, src/OVAL/probes/independent/textfilecontent.c, src/OVAL/probes/independent/textfilecontent54.c, src/OVAL/probes/independent/xmlfilecontent.c, src/OVAL/probes/oval_fts.c, src/OVAL/probes/oval_fts.h, src/OVAL/probes/unix/file.c, src/OVAL/probes/unix/fileextendedattribute.c, src/OVAL/probes/unix/gconf.c, src/OVAL/probes/unix/linux/selinuxsecuritycontext.c, src/OVAL/probes/unix/sysctl.c, tests/API/probes/oval_fts_list.c
When we cannot match filename by regex (due to non-utf8-characters) we used to ignore it, but now we will set result to error.
Maybe we could return `message` to oval result, but I haven't found any current probe what does it. So I don't know if it is a good idea. What do you think?
---
Error: `For example, if there was an error returned by an api when trying to determine if an object exists on a system.` https://oval.mitre.org/language/version5.6/ovalresults/documentation/oval-results-schema.html
=> probes/oval_fts: Return error if regex issue occurs

tests/valgrind_test.sh
This commit enables us to detect also other memory errors,
not only the memory leaks, but also invalid reads etc.
We will use --error-code to detect that valgrind failed.
This option is designed for usage in automated test suites (see man).
Parsing the log is not necessary to detect the fail.
Also valgrind has to generate a special logfile for each child process
to avoid undefined results (see man).
=> Adjust the valgrind test to detect all kinds of memory errors

tests/probes/file/Makefile.am, tests/probes/file/test_probes_file.sh, tests/probes/file/test_probes_file_filename.xml
Only test - without fix - should fail currently.
It should be test for https://github.com/OpenSCAP/openscap/issues/467, but it doesn't crash.
But I have found another problem; we don't escape correctly filenames in xml result
```
Entity: line 3457: parser error : PCDATA invalid Char value 27
<unix-sys:filepath>/tmp/tmp.5mogjwJMK2/filename_</unix-sys:filepa
^
```
=> test/file: Add test to strange filenames (missing fix)

src/DS/sds.c
I think it is misleading, because "+1" means automatically `+1 * size array element`, Previous code will not work e.g. with array of int.
Don't you think?
=> Refactoring: Remove misleading indexing

src/XCCDF/xccdf_session.c
https://bugzilla.redhat.com/show_bug.cgi?id=1367896
According to man page, dirname can return pointer to original
path. So we should not call free on returned value.
(But we should free result of oscap_strdup)
=> xccdf_session.c: Fix free of dirname

src/OVAL/oval_session.c, src/OVAL/oval_sysModel.c, src/OVAL/oval_system_characteristics_impl.h, src/OVAL/public/oval_results.h, src/OVAL/public/oval_session.h, src/OVAL/results/oval_resModel.c, src/OVAL/results/oval_resultSystem.c, tests/API/OVAL/unittests/Makefile.am, tests/API/OVAL/unittests/all.sh, tests/API/OVAL/unittests/test_without_syschars.sh, tests/API/OVAL/unittests/test_without_syschars.xml, utils/oscap-oval.c, utils/oscap-tool.h, utils/oscap.8
We can export full/thin results using OVAL directives, but we always export system characteristics, too.
Added support to not export system characteristics.
More info in commit message.
How it should work, you can see from attached test.
=> Added support to not to export system characteristics

src/common/text.c
This change allows attributes marked as overriders by
oscap_text_set_override() to be exported.
Exportation of an overrider attribute is conditioned by override_given.
But override_given is only set when an imported attribute has override
capability set. So, when an oscap_text was marked as overrider by
oscap_text_set_set_override() the attribute was never exported.
Related to RHBZ#1320194.
=> Fix export of overrided oscap_text

src/XCCDF_POLICY/xccdf_policy.c, tests/API/XCCDF/unittests/test_xccdf_role_unscored.sh
When a XCCDF rule has @role="unscored", perform all the checks but mark
the result as XCCDF_RESULT_INFORMATIONAL.
https://github.com/OpenSCAP/openscap/issues/525
=> Fix results of XCCDF rules with @role="unscored".

docs/manual/manual.adoc
cherry-picked from https://github.com/OpenSCAP/openscap/pull/518 (I will remove this commit from maint-1.0 PR)
Maybe it cause conflict, please check that the change will be located below "oval directives" paragraph
=> manual.adoc: OVAL: add --without-syschar paragraph

src/XCCDF/xccdf_session.c
SCAP Workbench is parsing this message as progress status and
showing errors, while actually this message is a warning.
Related to RHBZ#1367923
=> Consider suggestion to use "--fetch-remote-resources" a warning

src/DS/sds_index.c
Strings expected in format strings were not supplied.
Compiler was OK with that because it is a function with
variable count of parameters.
=> Issue #529: Fix a segmentation fault

src/DS/ds_sds_session.c, src/XCCDF/xccdf_session.c, tests/DS/Makefile.am, tests/DS/sds_tailoring/sds.ds.xml, tests/DS/test_ds.sh
This commit fixes processing of tailoring within datastreams.
It is now possible to have a datastream collection with multiple datastreams,
where XCCDF tailoring and XCCDF checklist are not both in the same datastream.
=> Support tailoring of a checklist located in a different datastream

xsl/xccdf-share.xsl
I forgot to check it in previous PR.
If these attributes are not provided we don't want to print empty table.
It should be part of https://github.com/OpenSCAP/openscap/pull/548
=> xccdf-share.xsl: HTML report - fix empty table

src/OVAL/oval_component.c
Code was not considering that one of the operands could be a string.
=> Fix a bug in Arithmetic complex function

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
Hello,
This PR is to update the SUSE 11 CPE to address issue 1469 raised in SSG based on the comment from @redhatrises . [https://github.com/OpenSCAP/scap-security-guide/issues/1469#issuecomment-248900441]
I have used the OVAL content from "installed_OS_is_sle11" in SSG's shared OVAL folder as reference.[https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/oval/installed_OS_is_sle11.xml]
If the changes look good, I will make them for SUSE 10 and 12 as well.
Thank you!
=> Update SUSE 11 CPE

src/XCCDF/benchmark.c, src/source/bz2.c, src/source/bz2_priv.h, src/source/oscap_source.c
oscap is able to recognize bz2 format even if it was compiled without bzip2 support.
If user with oscap(without bzip2 support) wanted to load bzip2 file, he got an ugly xml parsing error message. Now he will get less ugly error message.
https://github.com/OpenSCAP/scap-security-guide/issues/1509
=> Print error message if oscap loads bz2 files and doesn't support them

schemas/sce/1.0/sce-result-schema.xsd, src/SCE/public/sce_engine_api.h, src/SCE/sce_engine.c, xsl/xccdf-report-impl.xsl
We used to put both into interleaved output. This makes reuse of SCE results difficult for some of our users. This patch separates them.
Keep in mind that while this doesn't break API or ABI it does alter behavior! "stdout" is no longer stdout and stderr interleaved, it just has stdout in it now. I have added stderr into the HTML report so I think for the vast majority of use-cases this will improve the experience and not break it. However I see this as a gray area so I'd appreciate discussion.
I know we suggested stdout_only, stdout and stderr to keep current behavior but I thought that that was to confusing.
=> Separate stderr from stdout in SCE

utils/oscap_docker_python/oscap_docker_util.py
Compliance scan of a Docker image/container using oscap-docker reported
incorrectly that there had been an error even if scan had been successful
but incompliance of the assessed system had been found.
=> Issue#475: RHBZ#1387248: Fix oscap-docker reporting incompliance

src/XCCDF/xccdf_session.c
Memory allocated by oscap_source_new_from_xmlDoc() to tailoring_source was not freed.
The fix relies on the fact that freeing an oscap_source also frees the
xmlDoc used in its creation.
=> Fixing a resource leak reported by coverity scan

xsl/xccdf-guide-impl.xsl
That way users can right click the ref links, copy URL and use that URL to reference XCCDF groups and rules.
=> Add [ref] links to HTML guide

src/OVAL/probes/SEAP/generic/spb.c
position index points to end of the string.
This fix #310, which is the same bug in described in #447 comments, but was probably mistakenly related to #447 as it was an issue about not parsing a corner case which didn't lead to SIGSEGV.
=> Fixed spb_pick() to add 0 sized S-Expression even if our

src/OVAL/probes/SEAP/generic/spb.c
right away instead of getting inside of copy block.
=> Small refactor in spb_pick() fix when size == 0, just return

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
Reverts OpenSCAP/openscap#575
OpenSCAP detects RHEL6 CN system correctly when using oscap-shipped dictionary.
See https://bugzilla.redhat.com/show_bug.cgi?id=1392795
=> Revert "RHEL 6 ComputeNode CPE and RHEL 7 ComputeNode CPE"

src/DS/sds.c
See https://github.com/OpenSCAP/openscap/issues/383
=> Changed sds schematron-version attribute to the latest, 1.2

src/DS/rds.c, src/DS/rds_priv.h, src/XCCDF/xccdf_session.c
We don't pass validation performed by the SCAPVal tool.
```
ERROR: SCHEMATRON - [results.xml] If the <xccdf:result> value for a <xccdf:rule-result> is 'error', 'unknown', 'notapplicable', or 'notchecked', then the result of at least one OVAL definition referenced by that rule SHALL be 'error', 'unknown', 'not applicable', or 'not evaluated', respectively. If the <xccdf:result> value is 'fail' then the result of at least one of the OVAL definitions referenced SHALL match the fail category as defined in the SCAP table. If the <xccdf:result> value is 'pass' then the result of all of the OVAL definitions referenced SHALL match the pass category as defined in the SCAP table.
ERROR: SCHEMATRON - [results.xml] The @href attribute SHALL contain "#" + the @id of the <arf:report> containing the …
```
=> Fix invalid ARF results

src/DS/rds.c
This enables to reference OVAL results in arf:report
if the XCCDF rule contains xccdf:complex-check.
Previously xccdf:complex-check were ignored.
=> Fix injecting references to check-content-ref@href

src/XCCDF/xccdf_session.c
Resolves:
```
Program received signal SIGSEGV, Segmentation fault.
oscap_htable_lookup (htable=0x0, key=0x14c3470 "r3300-OCIL.xml") at list.c:441
0  oscap_htable_lookup (htable=0x0, key=0x14c3470 "r3300-OCIL.xml") at list.c:441
1  0x00007ffff7b285d9 in oscap_htable_get (htable=<optimized out>, key=<optimized out>) at list.c:495
2  0x00007ffff7b3206d in ds_rds_report_inject_check_content_ref (arf_report_mapping=0x0,
check_content_ref=0x14c05a0) at rds.c:460
3  ds_rds_report_inject_rule_result_check_refs (doc=<optimized out>, rule_result=0x14bfbc0,
arf_report_mapping=0x0) at rds.c:483
4  ds_rds_report_inject_rule_result_refs (doc=<optimized out>, test_result_node=<optimized out>,
arf_report_mapping=0x0) at rds.c:499
5  ds_rds_report_inject_refs (report=report@entry=0x14bcb10, …
```
=> Create XCCDf session result maps even when no oval agents are set

src/DS/rds.c, src/DS/rds_index.c
NIST SP800-126 errata unified 2 namespaces that used to be different. It is recommended the use the "http://scap.nist.gov/specifications/arf/vocabulary/relationships/1.0#" variant.
This PR prevents the following warning in SCAPVal:
```
WARN : SCHEMATRON - [G2.datastream1.profile11.rhel.results_arf.xml] NIST SP800-126 errata has updated the "arf-rel" namespace to http://scap.nist.gov/specifications/arf/vocabulary/relationships/1.0# The original namespace of http://scap.nist.gov/vocabulary/arf/relationships/1.0# has been detected.
```
=> Replace old arfrel ns

src/CVE/cve_priv.c
Skip assessment_check, scanner and discovered-datetime while parsing the
CVE entry in the XML file
=> Skip assessment_check, scanner and discovered-datetime while parsing the CVE entry

src/XCCDF_POLICY/xccdf_policy_remediate.c, tests/API/XCCDF/applicability/test_report_anaconda_fixes.sh, utils/oscap-xccdf.c
Added --verbose support in generate fix.
Removed a filter in generate fix that was filtering all fixes by current machine CPE, which makes no sense.
=> Maint 1.2 improve generate fix

src/OVAL/probes/independent/system_info.c
sysinfo hostname to 'Unknown' instead of an empty string.
=> Fixed a corner case when /etc/hostname is empty, now it sets

src/XCCDF_POLICY/xccdf_policy.c
Freeing a default policy, which has no profile assigned, was causing a segfault.
=> Only check ID of profile if profile exists

src/OVAL/probes/unix/runlevel.c
Fixed coverity warnings and other issues found in `parse_os_release` in `runlevel.c`. I found some logic errors in the code and many things were over-complicated.
Would be awesome if @radzy could review this.
I tested it using gdb.
```
./run cgdb src/OVAL/probes/.libs/probe_runlevel
```
Inside gdb do:
```
break main
run
print parse_os_release("whatever_you_wish");
```
Fixes #591
=> Runlevel probe fixes

src/XCCDF/public/xccdf_session.h, src/XCCDF/xccdf_session.c, utils/oscap-xccdf.c, utils/oscap.8
possible to generate OVAL and/or XCCDF results with or without
OVAL System Characteristics.
=> Added support for --without-syschar in XCCDF modules, now it is

src/CPE/cpe_session.c, src/CPE/cpe_session_priv.h, src/OVAL/oval_directives.c, src/OVAL/public/oval_directives.h, src/OVAL/public/oval_results.h, src/OVAL/results/oval_resModel.c, src/OVAL/results/oval_resultSystem.c, src/XCCDF/public/xccdf_session.h, src/XCCDF/xccdf_session.c, utils/oscap-tool.h, utils/oscap-xccdf.c, utils/oscap.8
Full Results is still the default option.
If the user needs both no syschars and thin results they can use `--without-syschar --thin --results-arf /tmp/arf.xml`.
=> Added --thin option to the XCCDF module, this enables thin results in OVAL and ARF files.

src/OVAL/oval_affected.c
This fixes a segfault when trying to convert OVAL_AFCFML_UNKNOWN to a string.
Also fixed a typo in the ODAFAMILY enum string mapping. Although keep in mind that that was not necessary to fix the segfault.
=> Use oscap_enum_to_string instead of just index lookup for OVAL affected family conversion

src/DS/ds_sds_session.c, src/DS/public/ds_sds_session.h, utils/oscap-ds.c
These dictionaries are auto-registered when doing xccdf eval so it only makes sense we split them all out when splitting datastreams.
=> Register CPE dictionaries when doing ds sds-split

ac_probes/ac_probes.sh, ac_probes/configure.ac.tpl, configure.ac, tests/probes/Makefile.am
Previously we were testing for headers and disabling the tests if they were missing. Not disabling the probe. That makes no sense, let's always build and always test system_info.
system_info deps are hard to check for because the probe has different implementations for BSD, Linux and Solaris.
=> We always build the system_info probe in OpenSCAP, mark it as such

ac_probes/ac_probes.sh, configure.ac
We check for PCRE OR POSIX regex.h globally, makes no sense to check again for all the probes.
We need pcre.h OR POSIX regex.h whereas in the probes we check that both are present. In rare circumstances this may disable probes even though all the necessary deps are present.
=> Stop checking pcre.h AND regex.h in all the probes

src/DS/ds_sds_session.c
ds_sds_session_register_component_source() when the component
has already been added before.
=> Changed the previous error message to a debug warning in

src/DS/rds.c
OpenSCAP can do it but the result won't be a valid ARF, only XCCDF 1.2
is allowed in ARFs.
Example:
```
oscap xccdf eval --verbose WARNING --results-arf /tmp/arf.xml ~/d/scap-security-guide/RHEL/7/output/ssg-rhel7-xccdf-1.2.xml 
WARNING: This content points out to the remote resources. Use `--fetch-remote-resources' option to download them.
WARNING: Skipping https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2 file which is referenced from XCCDF content
```
vs.
```
$ oscap xccdf eval --verbose WARNING --results-arf /tmp/arf.xml ~/d/scap-security-guide/RHEL/7/output/ssg-rhel7-xccdf.xml 
WARNING: This content points out to the remote resources. Use `--fetch-remote-resources' option to download them.
WARNING: Skipping …
```
=> Warn when injecting XCCDF 1.1 results into an ARF

src/XCCDF_POLICY/xccdf_policy_remediate.c, utils/oscap-xccdf.c, utils/oscap.8, xsl/legacy-fix.xsl
result-id, else it will fallback to profile-oriented fix
generation, which get fixes from all selected rules in
provided profile.
=> Added result-oriented 'generate fix' whenever an user pass a

src/XCCDF/xccdf_session.c, src/XCCDF_POLICY/public/xccdf_policy.h, src/XCCDF_POLICY/xccdf_policy.c, tests/API/XCCDF/unittests/test_remediation_amp_escaping.sh, tests/API/XCCDF/unittests/test_remediation_cdata.sh, tests/API/XCCDF/unittests/test_remediation_simple.sh, tests/API/XCCDF/unittests/test_remediation_subs_plain_text.sh, tests/API/XCCDF/unittests/test_remediation_subs_plain_text_empty.sh, tests/API/XCCDF/unittests/test_remediation_subs_value_refine_value.sh, tests/API/XCCDF/unittests/test_remediation_subs_value_take_first.sh, tests/API/XCCDF/unittests/test_remediation_subs_value_title.sh, tests/API/XCCDF/unittests/test_remediation_subs_value_without_selector.sh, tests/API/XCCDF/unittests/test_remediation_xml_comments.sh
This PR addresses the issue discussed in #617. 
I have introduced a new wrapper function `xccdf_policy_update_score` similar to `xccdf_policy_get_score`. This function calls the `xccdf_result_recalculate_scores` routine.
In `xccdf_session_remediate`, rather than returning `xccdf_policy_remediate`, on success, it returns `xccdf_policy_update_score`. Both `xccdf_policy_update_score` and `xccdf_policy_remediate` have status as the return value.
I have also updated some of the unit tests to check for the corrected compliance score after remediation.
Thank you!
=> Update compliance score after remediation.

src/common/assume.h, src/common/debug.c
Fixes required to make `./configure --enable-debug` build and work on Windows.
=> --enable-debug on windows

tests/API/CPE/dict/Makefile.am
=> Don't define TESTS_ENVIRONMENT multiple times in tests/API/CPE/dict

utils/oscap-xccdf.c
A lot of users use white background terminals and white on white is not visible. Instead let's use default color and bold.
I thought about applying this to `maint-1.0` but wasn't sure either way. I think it's an enhancement and not a bugfix so I decided to go with `maint-1.2`.
=> Don't use white colors in oscap xccdf eval output

utils/oscap-vm
Otherwise we would still run oscap on an empty dir and potentially provide misleading results.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1391754
=> Check for errors when mounting image or guestfs domain in oscap-vm

xsl/xccdf-report-impl.xsl
Avoids tedious scrolling back up to perhaps hide the rule result details. If you click that button you will be teleported back to the first rule result details. There it gets easy to just click `hide result details` if necessary.
I think this fixes #620 but it is not the solution suggested in that ticket.
Handcrafted for @shawndwells ! :-D
=> Added a button into rule details that allows you to scroll back up quickly

schemas/oval/5.11.1/oval-definitions-schema.xsd, schemas/oval/5.11/oval-definitions-schema.xsd
OVAL 5.11.1 and 5.11 have some additional OVAL definition namespaces we are not importing. Found and fixed by @GaryGapinski
=> Add missing oval xsd imports

src/OVAL/oval_probe.c, src/OVAL/public/oval_probe.h, utils/oscap.c
Fixes #650 
Example:
```
==== Supported OVAL objects and associated OpenSCAP probes ====
(null)        system_info                  probe_system_info           
independent   family                       probe_family                
independent   filehash                     probe_filehash              
independent   environmentvariable          probe_environmentvariable   
independent   textfilecontent54            probe_textfilecontent54     
independent   textfilecontent              probe_textfilecontent       
independent   variable                     probe_variable              
independent   xmlfilecontent               probe_xmlfilecontent        
independent   environmentvariable58        probe_environmentvariable58 
independent   filehash58                   probe_filehash58 …
```
=> Show the probe family in `oscap --v`

xsl/xccdf-guide-impl.xsl, xsl/xccdf-report-impl.xsl, xsl/xccdf-share.xsl
Ran into this today when demoing HTML guide in a meeting. No idea why we didn't show severity in HTML guide.
I also have to say that the HTML guide looks much worse than our HTML report. And the filtering, searching and grouping features are not there. Wish we could bring some of those features to the HTML guide in the future.
I also sneaked in a bugfix. In HTML report we just assume severity attribute is there. This is not guaranteed by the specification! If severity is missing we should assume it's "unknown". I have made changes so that that's what gets displayed in HTML report and HTML guide.
=> Show severity in HTML guide

src/OVAL/probes/unix/runlevel.c
Adressing:
Calling "fgetc(osrelease)" without checking return value. This library
function may fail and return an error code.
Fixes https://github.com/OpenSCAP/openscap/issues/634
=> Issue #634: Coverity: Check return value of fgetc

xsl/xccdf-guide-impl.xsl, xsl/xccdf-share.xsl
Just a cosmetic change. We were incosistent here. 
Fixes https://github.com/OpenSCAP/openscap/issues/655
=> Issue #655: Capitalize first letters in labels in HTML guide

docs/manual/manual.adoc
For `maint-1.2` mainly because of group-by and identifier/reference lookup. Both of these are `maint-1.2` only.
=> Manual more detailed idents

docs/manual/manual.adoc
It was not clear before that you can use `--results` or `--results-arf` when evaluation an XCCDF or SDS.
=> User manual: Mention --results-arf in the XCCDF/SDS evaluation section

docs/manual/manual.adoc
This pull request adds a new subsection into the section "Advanced oscap usage" about the multi-check feature and handling it in XCCDF older than 1.2.
=> Manual: Describe evaluating XCCDF rules with multiple checks

src/XCCDF/public/xccdf_session.h, src/XCCDF/xccdf_session.c, src/XCCDF_POLICY/xccdf_policy_substitute.c, src/source/oscap_source.c, src/source/public/oscap_source.h, tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/test_fix_arf.sh, tests/API/XCCDF/unittests/test_fix_arf.xccdf.xml, utils/oscap-xccdf.c
This pull request will enable:
1. Generating fix scripts from a profile in ARF file (profile-oriented fix)
This contains all the remediation scripts from a given profile.
Example:
```
oscap xccdf generate fix \
--profile xccdf_org.ssgproject.content_profile_common \
--output fix.sh \
arf.xml
```
2. Generating fix scripts based on scan results stored in ARF file (result-oriented fix)
This contains remediation only for failed rules.
Example:
```
oscap xccdf generate fix \
--result-id xccdf_org.open-scap_testresult_xccdf_org.ssgproject.content_profile_common \
--output fix.sh \
arf.xml
```
=> Add ARF support in "oscap xccdf generate fix"

docs/manual/manual.adoc
This commit covers using DataStreams and CPEs in section
"Evaluating XCCDF rules with multiple checks" of the OpenSCAP
user manual.
=> Improve user manual

docs/manual/manual.adoc
Better instructions for OVAL thin results in user manual.
The main improvement is the OVAL directives example.
=> Thin results OVAL steps in user manual

src/SCE/sce_engine.c, src/common/oscap_string.h, tests/sce/Makefile.am, tests/sce/streams_fill.sh, tests/sce/test_sce_streams_fill.sh, tests/sce/test_sce_streams_fill.xccdf.xml
We have been reading stdout and only then stderr. This caused stalls when stderr was filled up and stdout was still waiting for input. This PR changes the SCE stdout and stderr pipe reading to be interleaved. We do non-blocking reads from both pipes.
Thx goes to @dahaic for the test
Thx goes to @rsprudencio for the fcntl nonblock impl
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1420811
=> Fix SCE stderr stalling

src/DS/sds.c, src/XCCDF/xccdf_session.c, tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/test_xccdf_oval_absolute_path.sh, tests/API/XCCDF/unittests/test_xccdf_oval_absolute_path.xccdf.xml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1312831 and https://bugzilla.redhat.com/show_bug.cgi?id=1312824
CC @dahaic
=> Support absolute oval path - both simple and file:// prefixed

src/XCCDF/public/xccdf_session.h, src/XCCDF/tailoring.c, src/XCCDF/xccdf_session.c, src/XCCDF_POLICY/check_engine_plugin.c, src/XCCDF_POLICY/public/check_engine_plugin.h, src/common/debug.c, tests/API/OVAL/unittests/test_external_variable.sh, tests/API/OVAL/unittests/test_object_component_type.sh, tests/API/XCCDF/unittests/test_remediation_subs_unresolved.sh, tests/probes/sql57/unsupported_engine.sh, tests/probes/sysctl/test_sysctl_probe_all.sh, utils/oscap.c
~~DO NOT MERGE, up for discussion.~~
@jan-cerny I have noticed that your oscap_set_verbose code defaults to unknown verbosity and no output. Do you recall what was the reasoning behind that? I expected WARNING level by default and stderr output, which is what this PR does.
Does the UNKNOWN verbose level have any meaning? It seems it's just used to flag that `oscap_set_verbose` was never run with non-NULL verbosity level.
Perhaps I am missing something.
=> Make WARNING the default verbosity level

src/OVAL/probes/oval_fts.c, src/OVAL/probes/unix/file.c
After merging https://github.com/OpenSCAP/openscap/pull/630 some new messages have appeared on stderr. When scanning SSG Fedora common profile using the latest OpenSCAP from git I got stderr completely convoluted with warnings. Most of them were ```Getting extended ACL for file ```... and ``lstat() failed``. However these messages don't signalise anything harmful. I propose moving them to a lower verbosity level.
=> Recategorize some warning messages

src/XCCDF_POLICY/xccdf_policy_remediate.c
When we generate Ansible playbook from an entire profile
we include a header at the beginning of the generated playbook.
However, when we generate fixes only for failed rules based on
OpenSCAP scan result (so-called result-oriented fixes), we don't
include any header. This commit will cause including a header
in result-oriented fixes as well.
=> Fix missing header in result-oriented Ansible remediations

src/DS/sds.c
We recently moved to cmake in SSG and that exposed a couple new bugs, including this one.
When adding files into SDS we mangle the path to figure out a descriptive component ID. We correctly mangle the forward slashes but we don't mangle the @ (at symbol) at all. The at symbol is used in jenkins when building more tasks to separate workspaces. This leads to failures when validating SDS with components with the at symbol in them.
Check out end of https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/1168/label=node-fedora23/console for an example.
TODO: We should probably rework the whole mangle function and do a better job being really defensive and using oscap_string. But this will do for now, unless somebody wants to rewrite it.
=> Mangle the '@' symbol when adding components to datastream

docs/contribute/contribute.adoc
Contributors need to follow LGPLv2 for their contributions to be accepted. Spell that out in the contribute.adoc document.
=> Mention LGPLv2 license in contribute.adoc

tests/DS/eval_cpe/sds.xml, tests/DS/test_ds.sh
Test covers generation from profile or from results, when CPE
is defined. Expected outcome is that CPE is ignored for profile
generate fix.
=> Updated test coverage regarding CPE in generate fix scenario.

xsl/xccdf-share.xsl
I noticed that we don't show Anaconda snippets labeled properly and we use them quite a bit in SSG. This PR fixes that by introducing proper labels in HTML report and guide.
=> Show Anaconda snippets labeled properly in HTML report & guide

tests/API/XCCDF/unittests/test_xccdf_results_arf_no_oval.sh, utils/oscap-info.c
This commit will display additional information about an ARF file,
such as evaluation date, source benchmark and profile, platform CPEs,
result ID.
See the improvement:
Before:
```
[jcerny@thinkpad arf_info]$ oscap info arf.xml
Document type: Result Data Stream
Asset: asset0
- collection1 -> xccdf1
```
After:
```
[jcerny@thinkpad arf_info]$ oscap info arf.xml
Document type: Result Data Stream
Imported: 2017-03-02T12:05:07
Asset: asset0
ARF report: xccdf1
Result ID: xccdf_org.open-scap_testresult_xccdf_org.ssgproject.content_profile_common
Source benchmark: /usr/share/xml/scap/ssg/content/ssg-fedora-ds.xml
Source profile: xccdf_org.ssgproject.content_profile_common
Report request: collection1
Evaluation started: 2017-03-02T12:02:02
Evaluation finished: 2017-03-02T12:05:07
Platform CPEs: …
```
=> Issue #664: Show more information about ARF files in "oscap info"

src/OVAL/probes/unix/linux/dpkginfo.c, src/OVAL/probes/unix/linux/rpminfo.c, src/OVAL/probes/unix/linux/rpmverify.c, src/OVAL/probes/unix/linux/rpmverifyfile.c, src/OVAL/probes/unix/linux/rpmverifypackage.c
Function probe_init() can possibly fail and return NULL.
We should check if initialization has been done properly
before we start the function.
Now we don't check the return value, which can possibly lead
to synchronization errors between threads and causes
a segmentation fault in probe_fini().
=> RHBZ #1414303, #1414312: Fix a segfault in rpm probes

cpe/openscap-cpe-oval.xml
RHEVH is based on RHEL7, therefore RHEL7 profiles should be applicable
on this system. This commit enables evaluating RHEL7 profiles on RHEVH.
However the underlying RHEL version cannot be determined from
redhat-release RPM package version, because RHEVH obsoletes
the redhat-release RPM package. Instead we should check for presence
of redhat-release-virtualization-host and then we will parse the
RHEL version from /etc/redhat-release file. Note that
redhat-release-virtualization-host RPM version represents RHEVH
version (currently 4.0.6), not RHEL version, so it's not possible
to rely only on rpminfo tests.
=> RHBZ #1420038: Identify Red Hat Enterprise Virtualization Host as RHEL7

docs/manual/manual.adoc
In our examples, we referenced to old-style guides and reports
as generated by OpenSCAP 1.0.x. Instead we will show our new
nice reports and guides.
=> Issue #513: Provide better examples in user manual

tests/API/OVAL/unittests/test_object_component_type.sh
We fixed duplicate error messages (issue #707). But in this test,
we assumed that there are 6 lines on stderr. Actually two of them
were duplicated. We should not count number of lines on stderr
because we may add a new warning somewhere in our code and it will
break the test again. This commit stops testing stderr line count.
=> Do not rely on number of lines on stderr

src/OVAL/probes/unix/linux/systemdunitdependency.c, src/OVAL/probes/unix/linux/systemdunitproperty.c
Systemd probes are crashing during scanning Docker
containers. This probably happens because containers
do not have systemd running inside them by default.
Instead, we will report an error.
=> RHBZ #1431186: Fix crashing systemd probes

tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/test_fix_arf.playbook1.yml, tests/API/XCCDF/unittests/test_fix_arf.playbook2.yml, tests/API/XCCDF/unittests/test_fix_arf.sh
We shouldn't change the format of the output to ensure
the fix generated by oscap is consumable by Ansible.
=> Improve test of Ansible fixes

src/OVAL/oval_sexp.c
It is pretty common to have variables with no values, but
the warnings flood the stderr after we have enabled them by default.
Still, this will keep informing user if there was a problem.
=> Change category of a message, emit warning only if necessary

swig/python2/Makefile.am, swig/python3/Makefile.am, swig/src/openscap.i
Added a Vagrantfile with ansible provisioning for easy creation of a build environment.
Updated the swig files so all the public functions get exported to python
Changed enable python3 to default to yes
Added some extra accessor and mutator functions so we can export functioning XCCDF and OVAL files made from scratch in python.
=> Updates for Python 3 bindings

src/XCCDF_POLICY/xccdf_policy_remediate.c, tests/API/XCCDF/fix/all.sh
We have plans to generate remediation roles in SSG. Some of these scripts will be very large. It makes sense to add some more context information to the generate fixes, this commit does just that.
Right now it only adds comments but I want to improve this to print remediation status or even status bar in the future. Let me know what you think.
Example:
```
$ ./run ./utils/.libs/oscap xccdf generate fix --template urn:xccdf:fix:script:sh --profile pci-dss ~/d/scap-security-guide/build/ssg-rhel7-xccdf.xm
...
var_multiple_time_servers="0.rhel.pool.ntp.org,1.rhel.pool.ntp.org,2.rhel.pool.ntp.org,3.rhel.pool.ntp.org"
if ! `/usr/sbin/pidof ntpd`; then
if ! `grep -q ^server /etc/chrony.conf` ; then
if ! `grep -q '#[[:space:]]*server' /etc/chrony.conf` ; then
for i in `echo …
```
=> Comments in generated remedition bash snippets

src/XCCDF/public/xccdf_benchmark.h, src/XCCDF/xccdf_impl.h
Added a function to export a benchmark to a source object so I can put one into a datastream
=> Exposed xccdf_benchmark_export_source()

xsl/xccdf-report-oval-details.xsl
I am always confused when reading the OVAL details and have to read the lines several times to understand it. This PR aims to improve that. I use colors to highlight which condition passed and failed. I use simpler language - passed or failed - instead of satisfying and violating.
Before:
After:
I feel like this makes the report way easier to read, especially for users not familiar with OVAL and XCCDF. Let me know what you think.
=> Easier language and more colors in OVAL details

src/XCCDF_POLICY/xccdf_policy_remediate.c, tests/API/XCCDF/unittests/test_fix_arf.playbook1.yml, tests/API/XCCDF/unittests/test_fix_arf.playbook2.yml
Use thread-safe strchr instead of strtok that uses global state.
=> Do not remove consecutive newlines from ansible fixes when generating

src/OVAL/probes/unix/linux/rpminfo.c, src/OVAL/probes/unix/linux/rpmverify.c, src/OVAL/probes/unix/linux/rpmverifyfile.c, src/OVAL/probes/unix/linux/rpmverifypackage.c
These changes makes RPM probes return "not applicable" when RPM config files are not found.
They also fix possible undefined behaviours when destroying an uninitialised mutex.
I have changed order rpmFreeXXXX calls in probe_fini() functions, but I'm not sure if I can do it.
I will still look into writing checks for init and fini functions.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1447629
=> Change RPM probes to return "not applicable" when run on non-RPM environment

src/DS/ds_sds_session.c
In b8defed we moved to using `s->checklist_id` instead of hard coding `xccdf.xml`. However, this change was forgotten in `ds_sds_session_get_html_guide` which leads to the following error when trying to get the HTML guide:
Internal error: Could not acquire handle to xccdf.xml source.
This change migrates `ds_sds_session_get_html_guide` to also use `s->checklist_id` and thus fixes the issue.
Tests missing and are left to the more knowledgeable maintainer ;)
Fixes: #744
=> pass session->checklist_id to oscap_htable_get in get_html_guide

ac_probes/configure.ac.tpl, configure.ac
We use this ('devel support') and similar language as a pattern across the build pipeline.
🐟
=> Suggest users to install bzip2-devel instead of bzip2

src/OVAL/oval_variable.c, src/OVAL/public/oval_definitions.h
These functions were previously returning the generic oscap_iterators, which are not available publicly, and there are no python swig interfaces for them.
=> Type-specific oval variable iterators

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml, src/OVAL/probes/unix/runlevel.c, tests/API/XCCDF/default_cpe/all.sh
Added initial Oracle Linux cpe name support. 
On patch development I took into account "Initial Wind River Linux support" patch, for this reason src/OVAL/probes/unix/runlevel.c updated accordingly. As run level compatible to RHEL implementation I used get_runlevel_redhat for Oracle Linux in distro_tbl.
Due to Oracle Linux has 'redhat-release-server' package installed original test_api_xccdf_default_cpe_rhel<RELEASE> test fails on this system. Added workaround to test_rhel function in tests/API/XCCDF/default_cpe/all.sh based on package vendor name.
Please review this request and let me know if it is applicable for openscap project.
=> Oracle Linux cpe support

utils/oscap-xccdf.c, utils/oscap.8
This commit will allow to select a benchmark from which the fix
will be generated if there are multiple benchmarks in a single
datastream.
=> Issue #722: Support multiple benchmark datastreams in "xccdf generate fix"

docs/manual/manual.adoc, src/XCCDF/public/xccdf_session.h, src/XCCDF/xccdf_session.c, src/XCCDF_POLICY/xccdf_policy.c, src/XCCDF_POLICY/xccdf_policy_priv.h, tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/test_single_rule-tailoring.xml, tests/API/XCCDF/unittests/test_single_rule.ds.xml, tests/API/XCCDF/unittests/test_single_rule.oval.xml, tests/API/XCCDF/unittests/test_single_rule.sh, tests/API/XCCDF/unittests/test_single_rule.xccdf.xml, utils/oscap-tool.h, utils/oscap-xccdf.c, utils/oscap.8
* added '--rule' cmd option for xccdf eval
* usage:
oscap xccdf eval [--remediate] --profile PROFILE --rule RULE INPUT_FILE
=> Added functionality for single rule evaluation

src/OVAL/oval_component.c, src/OVAL/oval_variable.c, src/OVAL/results/oval_resultTest.c
RHBZ#1446451 has discovered that we are unable to find reasons of errors caused by missing external variables. There was no chance that user could magically figure out that he needs to provide some external variables.
This PR wants to add a way to inform user about missing external variables by introducing some error messages.
=> RHBZ#1446451: Allow to identify problems with external variables

docs/manual/manual.adoc
Changed "constains" to "contains", "debuging" to "debugging", and "immediatelly" to "immediately"
=> Fixed spelling errors in the manual.adoc

src/OVAL/probes/unix/linux/dpkginfo-helper.cxx
Hi openscap developers,
MMap *map will not be free https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/probes/unix/linux/dpkginfo-helper.cxx#L33
Please review my patch, thanks a lot!
Regards,
Leslie Zhai - https://reviews.llvm.org/p/xiangzhai/
=> Fix Memory leak for dpkginfo-helper found by clang analyzer

src/OVAL/probes/SEAP/generic/rbt/rbt_common.c, src/OVAL/probes/SEAP/generic/rbt/rbt_i32.c, src/OVAL/probes/SEAP/generic/rbt/rbt_i64.c
Fixes OpenSCAP/scap-workbench#129 and OpenSCAP/scap-workbench#61
Signed-off-by: Wesley Ceraso Prudencio <wcerasop@redhat.com>
=> Fixes crash when deallocating rbt_node in windows

src/XCCDF/benchmark.c, src/XCCDF/item.h, src/XCCDF/public/xccdf_session.h, src/XCCDF/xccdf_session.c, tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/test_fix_resultid_by_suffix.sh, tests/API/XCCDF/unittests/test_fix_resultid_by_suffix.xml, utils/oscap-xccdf.c
Allows for user to input suffix for the result id; i.e., common instead of xccdf_org.open-scap_testresult_xccdf_org.ssgproject.content_profile_common 
Works for xccdf generate fix --result-id and xccdf generate report --result-id
=> [WIP] Suffix/short id option for --result-id arguments 

src/XCCDF_POLICY/xccdf_policy_remediate.c, utils/oscap-info.c
Addressing:
openscap-1.2.14/utils/oscap-info.c:399: leaked_storage: Variable "report_it" going out of scope leaks the storage it points to.
openscap-1.2.14/utils/oscap-info.c:399: leaked_storage: Variable "asset_it" going out of scope leaks the storage it points to.
openscap-1.2.14/utils/oscap-info.c:394: leaked_storage: Variable "session" going out of scope leaks the storage it points to.
openscap-1.2.14/utils/oscap-info.c:394: leaked_storage: Variable "report_it" going out of scope leaks the storage it points to.
openscap-1.2.14/utils/oscap-info.c:394: leaked_storage: Variable "asset_it" going out of scope leaks the storage it points to.
openscap-1.2.14/src/XCCDF_POLICY/xccdf_policy_remediate.c:647: leaked_storage: Variable "rr_it" going out of scope leaks the storage it points to.
=> Issue #715: Fix resource leaks reported by Coverity

src/XCCDF/benchmark.c, src/XCCDF/public/xccdf_benchmark.h
Changed xccdf_find_target_htable to work with benchmarks too because benchmarks are definitely going through this code when they get renamed.
=>  Fix for dubious assert when renaming benchmarks

tests/API/XCCDF/fix/results-xccdf11.xml, tests/API/XCCDF/fix/results-xccdf12.xml, utils/oscap-tool.h, utils/oscap-xccdf.c, utils/oscap.8
Bash is a default language for remediation scripts. If we don't
provide a template explicitely, the result script shouldn't
contain Ansible or other snippets.
=> Issue #773: Ensure that bash fixes are always selected

src/XCCDF/public/xccdf_session.h, src/XCCDF/xccdf_session.c, utils/oscap-xccdf.c
Checks are not necessary to load OVAL because the remediation
scripts are stored in the XCCDF. This will remove the warning
for remote resources that are not needed.
=> Issue #723: Don't require other resources in "generate fix"

tests/mitre/test_mitre.sh
* added check if SELinux is enabled and if it is not the test
linux-def_selinuxsecuritycontext_test.xml is skipped
=> tests/mitre/test_mitre.sh: do not run SELinux test on systems without SELinux

utils/oscap-info.c
Along with profile IDs, profile names will be also displayed.
Releated to #685
=> Print profile names in "oscap info"

src/OVAL/probes/unix/sysctl.c
We will skip empty values to be consistent with "sysctl" tool.
If this behavior will be considered a bug in "sysctl" tool,
we will need to revert this commit. See RHBZ #1473207.
This should bring our broken tests working back.
=> Skip empty sysctl values

utils/oscap-docker.in
Class docker.Client was renamed to docker.APIClient in python-docker-py 2.0.0. See https://github.com/docker/docker-py/releases/tag/2.0.0
Unfortunately, this **doesn't fix** oscap-docker on Fedora 26. It just shows another, more serious issue:
See : https://github.com/OpenSCAP/openscap/issues/794
=> Fix oscap-docker with Docker newer than 2.0

src/OVAL/probes/independent/textfilecontent54.c, tests/probes/textfilecontent54/Makefile.am, tests/probes/textfilecontent54/all.sh, tests/probes/textfilecontent54/test_behavior_multiline.sh, tests/probes/textfilecontent54/test_behavior_multiline.xml.tpl
This PR attempts to fix issue #792 by changing the "reset filebehavior attributes if 'filepath' entity is used" block to only set attributes if they exist, allowing the defaults in the probe_tfc54behaviors_canonicalize() function to be effective.
Test cases are also added to check some permutations of behaviors.  The checks for oval:filepath:tst:5 fail without the changes to the textfilecontent54 probe.
I'm more confident in the bug than the fix; feel free to point out problems in the fix or better approaches.
=> OVAL Textfilecontent54 multiline behavior default bugfix

utils/oscap_docker_python/oscap_docker_util.py
If the container or image doesn't mount in 'rootfs' subdirectory, we will fallback to the original mount directory.
Partially fixes #794 .
=> Verify the container's filesystem location

src/XCCDF/value.c, src/common/util.c, src/common/util.h
I wanted to get rid of more of our reinvented builtins but in the end the best I could do was inline some of them. I was able to get rid of oscap_strtol though. Plus I discovered that oscap_find_file doesn't exist even though it's declared.
This is all just minor spring cleaning for fun, really. The performance gains are quite minimal.
=> Don't reinvent builtins in our codebase

src/OVAL/probes/unix/sysctl.c
This behavior is not a bug and respective BZ was closed as NOTABUG.
See https://bugzilla.redhat.com/show_bug.cgi?id=1473207
=> Remove resolved comment

libopenscap.pc.in
See #796
See https://bugzilla.redhat.com/show_bug.cgi?id=1414777
All the 3 "Requires" are not actually required when using openscap public API.
=> Remove requires from pkgconfig file

src/XCCDF/xccdf_session.c
The timestamp in result-oriented remediation script header
was wrong, it said that evaluation was started after
it was finished.
Fixes issue #772
Replaces PR #779
=> Issue #772: Fix timestamp in remediation script header

xsl/xccdf-report-impl.xsl
Notselected rules are never evaluated, so there is no need to include them in the Evaluation report.
This will remove the unwanted data from the HTML report, which will make the report smaller and possibly will make the searching and grouping functions faster.
See how size of the report is reduced:
```
[jcerny@thinkpad ~]$ ls -lh /tmp/report*.html        
-rw-rw-r--. 1 jcerny jcerny 723K Aug 14 12:50 /tmp/report-new.html                                        
-rw-rw-r--. 1 jcerny jcerny 1.4M Aug 14 12:50 /tmp/report-old.html
```
I also removed the `notselected` checkbox, because using it will have no effect.
=> Remove notselected rules and groups from HTML report

src/common/util.h
And should be to avoid coding errors.
This is a pretty minor thing I noticed while working on the CVRF code. The assumption is that the elements of the oscap_string_map are const. We can make that clear by the const keyword on the int value.
Note fore reviewer: oscap_string_map is a bad name for what this is, it's actually one line/element of that map.
=> The enum value in oscap_string_map elements can be const

src/OVAL/probes/unix/linux/rpminfo.c
The custom path to RPM database was set before config files
were loaded, so it was overwritten by value from config files,
therefore it usually scanned the host RPMs. This should be
fixed by calling the addMacro() function after calling
rpmReadConfigFiles().
Helps to fix #778.
=> Enable OFFLINE_RPMDB mode in rpminfo probe

README.md, tests/API/CCE/test_api_cce.sh, tests/API/CPE/dict/test_api_cpe_dict.sh, tests/API/CPE/lang/test_api_cpe_lang.sh, tests/API/CPE/name/test_api_cpe_uri.sh, tests/API/CVE/test_api_cve.sh, tests/API/CVSS/test_api_cvss.sh, tests/API/OVAL/glob_to_regex/test_glob_to_regex.sh, tests/API/OVAL/schema_version/test_schema_version.sh, tests/API/OVAL/test_api_oval.sh, tests/API/SEAP/test_api_seap.sh, tests/API/XCCDF/parser/test_api_xccdf.sh, tests/API/XCCDF/unittests/all.sh, tests/API/crypt/test_api_crypt.sh, tests/API/probes/all.sh, tests/DS/ds_sds_index/all.sh, tests/DS/signed/all.sh, tests/bindings/test_perl.sh, tests/bindings/test_python.sh, tests/codestyle/all.sh, tests/oscap_string/test_oscap_string.sh, tests/probes/sysinfo/test_probes_sysinfo.sh, tests/probes/xinetd/test_xinetd_probe.sh, tests/schemas/all.sh, tests/sources/all.sh, tests/test_common.sh.in
This commit allows us to use any oscap tool in the system with the make check by setting the variable OSCAP.
However, the following tests link against libopenscap_testing.la and don't use the oscap tool:
./tests/probes/xinetd
./tests/probes/sysinfo
./tests/oscap_string
./tests/bz2
./tests/API/CVSS
./tests/API/XCCDF/parser
./tests/API/XCCDF/unittests
./tests/API/CCE
./tests/API/SEAP
./tests/API/crypt
./tests/API/probes
./tests/API/CPE/lang
./tests/API/CPE/name
./tests/API/CPE/dict
./tests/API/CVE
./tests/API/OVAL/schema_version
./tests/API/OVAL/glob_to_regex
./tests/API/OVAL
./tests/DS/ds_sds_index
I could turn these tests off in case the OSCAP variable is defined, does it make sense or is there a better alternative?
=> Enables make check to use a different oscap binary

src/XCCDF_POLICY/xccdf_policy_remediate.c
In the exceptional case when the function oscap_textlist_get_preferred_plaintext returns NULL, we'd try to free a non-heap memory.
Signed-off-by: Wesley Ceraso Prudencio <wcerasop@redhat.com>
=> Fix freeing non-heap memory

src/OVAL/probes/SEAP/sch_pipe.c
Fix for AIX and for other platforms where WCOREDUMP is not defined.
Follow Linux Programmer's Manual (i.e. man waitpid) for WCOREDUMP: "This macro should be employed only if WIFSIGNALED returned true".
=> WCOREDUMP usage improvement in sch_pipe.c

src/OVAL/probes/fsdev.c
Also fix a couple of minor issues in __fsdev_init for Linux: potential FILE handle leak in case of malloc error - use endmntent instead of fclose.
Questions:
- Linux docs say that LSB deprecates the xyzmntent family of functions. So what should be used as a replacement?
- In match_fs function, why not just call bsearch?
=> Added support for AIX in fsdev.c

xsl/xccdf-share.xsl
If some elements are empty, we shouldn't try to populate them in the report,
because it looks very ugly.
Helps to fix issue #848.
=> Don't reserve space for empty elements in report

src/OVAL/probes/probe-api.c
AIX requires <sys/socket.h> for AF_INET.
=> Minor fix for AIX

src/OVAL/probes/probe/entcmp.c
AIX requires <sys/socket.h> for AF_INET and AF_INET6
=> Add support for AIX

schemas/Makefile.am
Automake doesn't understand the wildcard function which is evaluated
at install-time. Therefore, one has to make manually sure that the wildcard
argument corresponds to the intended filesystem location even when the build
happens outside the source tree.
This fixes #871 . The 100% clean solution would be to [remove the wildcards](https://www.gnu.org/software/automake/manual/html_node/Wildcards.html), but I can imagine we don't want to go for it.
=> Add path specification to wildcard function arguments.

utils/oscap-cvss.c
IBM XLC/C++: 1506-131 (W) Explicit dimension specification or initializer required for an auto or static array.
GCC -pedantic: error: array size missing in CVSS_SUBMODULES
=> Fix CVSS_SUBMODULES array declaration

src/OVAL/probes/crapi/digest.c
IBM XLC fails with the following error on "pragma omp parallel for" statement:
>"digest.c", line 153.33: 1506-814 (S) Branching in or out of structured block and parallel/work-sharing loop is not allowed."
=> Remove obsolete omp pragma

utils/oscap-cve.c, utils/oscap-ds.c, utils/oscap-oval.c, utils/oscap-xccdf.c
Get rid of warnings about missing array size reported by at least XLC and GCC compilers.
Also remove the use of magic numbers in a previous fix in ./utils/oscap-xccdf.c (#845).
=> Fix several arrays declaration

src/XCCDF_POLICY/xccdf_policy_remediate.c
"xccdf_policy_get_benchmark" can return NULL. It can cause a segfault
when we pass the returned value to "xccdf_benchmark_get_version".
I add should check if benchmark is not NULL. I move the statement
to the begining of the block because at original place I have to
free profile_title and profile_description.
Addressing:
src/XCCDF_POLICY/xccdf_policy_remediate.c:692: dereference:
Dereferencing a pointer that might be null "benchmark" when calling
"xccdf_benchmark_get_version".
=> Coverity fixes 2 - Fix possible NULL pointer dereferencing

src/XCCDF_POLICY/xccdf_policy_remediate.c, tests/API/XCCDF/unittests/test_fix_arf.playbook1.yml, tests/API/XCCDF/unittests/test_fix_arf.playbook2.yml
In ansible playbooks it is customary for variables to be specified in a list separate from tasks. That way Ansible users can tailor the playbooks without any external tools:
Playbook after this change:
```
---
###############################################################################
#
#
#
#
#
#
#
###############################################################################
- hosts: all
vars:
inactivity_timeout_value: 900
var_accounts_maximum_age_login_defs: 90
var_account_disable_post_pw_expiration: 90
var_password_pam_dcredit: -1
var_password_pam_minlen: 7
var_password_pam_ucredit: -1
var_password_pam_lcredit: -1
var_auditd_max_log_file: 6
var_auditd_max_log_file_action: rotate
var_auditd_space_left_action: email
var_auditd_admin_space_left_action: single …
```
=> Ansible variables to come first before tasks

utils/oscap-xccdf.c, utils/oscap.8
This PR makes tailoring options in "oscap xccdf generate fix" visible in help and man page.  I basically fixed issue #894 but I also tried to clarify tailoring in "oscap xccdf eval" when I touched it.
=> Improve documentation of --tailoring-file and --tailoring-id options

src/OVAL/oval_variable.c, src/OVAL/probes/SEAP/seap-command-backendS.c, tests/API/CVRF/Makefile.am, utils/oscap-cve.c, utils/oscap-cvss.c, utils/oscap-ds.c, utils/oscap-info.c, utils/oscap-tool.h
Addressing many warnings like
```
/home/jcerny/openscap/utils/oscap-tool.h:174:47: warning: ‘struct
xccdf_session’ declared inside parameter list will not be visible
outside of this definition or declaration
int xccdf_set_profile_or_report_bad_id(struct xccdf_session *session,
const char *profile_id, const char *source_file);
```
=> Add missing includes

tests/probes/sql57/CMakeLists.txt
The test should be skipped if the probe is not build.
=> Run sql57 probe tests only if sql57 probe is build

src/OVAL/probes/independent/system_info.c, src/XCCDF_POLICY/xccdf_policy_remediate.c
Support for posix regular expression in master branch was removed long
time ago in 8bcad0850db80d379ca70a3daf293108af78c91e.
Bbut some code appeared again in master, probably by merging maint-1.2
branch. We need to be more careful when we merge maint-1.2 into master.
=> Remove posix regex leftovers from master branch

utils/scap-as-rpm
The world is moving to python3 and using just python is confusing.
Fixes #903
See also: https://taskotron.fedoraproject.org/artifacts/all/3de20448-c945-11e7-bbd3-525400817a8f/task_output/output.log
=> Use the versioned shebang in scap-as-rpm

cmake/FindRPM.cmake, src/CMakeLists.txt, src/OVAL/probes/CMakeLists.txt, utils/CMakeLists.txt
For reasons I can't figure out we were linking to all sorts of libraries for every single probe. This seems weird and excessive. Why not link to the libraries in libopenscap.so? Maybe I am missing something?
=> Remove unnecessary linking

CMakeLists.txt
The include(CPack) must be at the end of the CMakeLists and we
shouldn't mix CPack with CTest.
=> Fix make package_source

tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/correct_stigw_result.xml, tests/API/XCCDF/unittests/stig-viewer-equivalence.py, tests/API/XCCDF/unittests/test_single_rule.xccdf.xml, tests/API/XCCDF/unittests/test_single_rule_stigw.sh
The `--stig-viewer` option got its test case - the output is compared to a known output that is OK by a Python script.
=> Added stig viewer tests

src/OVAL/probes/oval_fts.c, src/OVAL/probes/unix/symlink.c, src/common/oscap_acquire.c, src/common/util.c, src/common/util.h, utils/oscap-xccdf.c
Windows doesn't know `realpath()`. Instead they have a similar function `_fullpath()`. This patch introduces a wrapper function `oscap_realpath()` that wraps either `realpath()` or `_fullpath()` depending on the platform. The PR also replaces every `realpath()` by `oscap_realpath()`.
=> Introduce oscap_realpath to improve code portability

src/CPE/cpename.c, src/OVAL/oval_agent.c, src/OVAL/oval_defModel.c, src/OVAL/oval_probe_ext.c, src/OVAL/oval_state.c, src/SCE/sce_engine.c, src/XCCDF/elements.c, src/XCCDF/rule.c, src/XCCDF/xccdf_session.c, src/XCCDF_POLICY/xccdf_policy_substitute.c, src/common/list.c, src/common/oscap_acquire.c, src/source/oscap_source.c, src/source/xslt.c
strdup is not a C standard function, it is different on different platforms. On Windows you are supposed to use _strdup instead. Therefore we have a small wrapper called `oscap_strdup`. However we are not using that wrapper ocnsistently and in many cases we still use strdup directly. This causes a lot of issues with @jan-cerny 's work on the Windows port.
I will not be fixing strdup usage in probes in this PR. That will have to be done in a different PR.
=> Use oscap_strdup instead of just strdup

src/DS/sds.c, src/OVAL/oval_session.c, src/OVAL/probes/probe/main.c, src/SCE/sce_engine.c, src/XCCDF/xccdf_session.c, src/common/oscap_acquire.c, src/common/util.c, src/common/util.h, utils/oscap-ds.c
We use `basename()` on a few places across our codebase. However on Visual Studio there is no such function. Most similar functions are `_splitpath()` or `_splitpath_s()` that can break pathname into components. To avoid many `#ifdef` section introduce `oscap_basename()`.
Then it replaces all occurences of `basename()` by `oscap_basename()`.
=>  Introduce oscap_basename

CMakeLists.txt, src/OVAL/oval_component.c, src/OVAL/oval_enumerations.c, src/OVAL/oval_object.c, src/OVAL/oval_schema_version.c, src/OVAL/oval_state.c, src/OVAL/oval_sysItem.c, src/OVAL/oval_test.c, src/OVAL/probes/crapi/digest.c, src/OVAL/probes/unix/process58.c, src/XCCDF/result.c, src/XCCDF/xccdf_session.c, src/XCCDF_POLICY/xccdf_policy.c, src/source/xslt.c, tests/API/XCCDF/unittests/test_oscap_common.c, utils/oscap-tool.c
Variable length arrays are unfortunately unsupported by Microsoft Visual Studio. 
This PR removes variable length arrays from the whole codebase.
I also add a warning for GCC which will prevent future contributors to contribute code
with variable length arrays.
=> Remove variable length arrays

CMakeLists.txt, compat/CMakeLists.txt, compat/compat.h, compat/flock.c, compat/strptime.c, compat/strsep.c, config.h.in, docs/manual/manual.adoc, src/CMakeLists.txt, src/OVAL/CMakeLists.txt, src/OVAL/probes/CMakeLists.txt, src/OVAL/probes/SEAP/CMakeLists.txt, src/OVAL/probes/independent/family.c, src/OVAL/results/oval_cmp.c, src/OVAL/results/oval_cmp_evr_string.c, src/OVAL/results/oval_cmp_ip_address.c, src/XCCDF/result.c, src/XCCDF_POLICY/xccdf_policy_remediate.c, src/common/debug.c, src/common/elements.c, src/common/err_queue.c, src/common/oscap_acquire.c, src/common/public/oscap_error.h, src/common/util.c, utils/oscap-oval.c
This pull request brings a set of changes that enable us to cross compile OpenSCAP for Windows on Fedora. It uses MinGW together with CMake. The build is **without probes**.
Suddenly it turns out that autotools handled some portability issues. However we can't use it because it was strongly dependent  on automake, GNUlib, m4, AC_ macros and other stuff that we got rid of. Therefore I solved some of the portability issues again.
I created a new directory called `compat` where we will put implementations of functions that we use but are available only in Linux. I have seen a similar directory in famous projects Git (https://github.com/git/git/tree/master/compat) and VLC (https://github.com/videolan/vlc/tree/master/compat). I don't know if there can be a better solution. Any suggestions and …
=> Cross compilation for Windows using CMake and MinGW

docs/manual/manual.adoc
This adds a step-by-step manual on how to import OpenSCAP to Visual Studio.
Requires https://github.com/OpenSCAP/openscap/pull/925 This do not merge until #925 is merged into master.
With #925 project opening is successful.
Unfortunately, build doesn't work, it reports hundreds of errors. Fixing these errors will be content of future PRs.
=> Describe import to Visual Studio

README.md
The names of the packages given in this file do not work out of the box.
I suggest to add the command line that installs the packages.
I also included the autoconf automake libtool packages to have it all in one go.
=> Add command line to install packages on Ubuntu 16.04

tests/mitre/CMakeLists.txt, tests/mitre/test_mitre.sh, tests/mitre/test_mitre_common.sh, tests/mitre/test_mitre_ind_probes.sh, tests/mitre/test_mitre_linux_probes.sh, tests/mitre/test_mitre_oval.sh, tests/mitre/test_mitre_unix_probes.sh
Split the one test into 4:
- test linux probes
- test ind probes
- test unix probes
- test OVAL features
Unfortunately the linux probes test takes by far the most time on most machines because of rpmverifyfile. Still, I think this is a step in the right direction.
=> Split test_mitre.sh

tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/test_generate_fix_ansible_vars.sh, tests/API/XCCDF/unittests/test_generate_fix_ansible_vars_ds-tailoring.xml, tests/API/XCCDF/unittests/test_generate_fix_ansible_vars_ds.xml, tests/API/XCCDF/unittests/test_generate_fix_ansible_vars_golden.yml, tests/API/XCCDF/unittests/test_generate_fix_ansible_vars_golden_altered.yml, tests/API/XCCDF/unittests/test_generate_fix_ansible_vars_golden_tailoring.yml
* Test checks that generate fix produces Ansible variables correctly,
defined inline in a playbook in "vars" section.
=> tests/API/XCCDF/unittests: added test for Ansible variables

schemas/cve/cve_0.1.xsd
Reviewing the NVD feeds from
https://nvd.nist.gov/vuln/data-feeds#CVE_FEED reflects like
`CVE-2016-1000031`, `CVE-2017-18016` and `CVE-2017-1000439`.
I'm sure this xsd needs to be vetted in other places, but currently
`oscap cve validate ./nvdcve-2.0-modified.xml` fails with
```shell
File './nvdcve-2.0-modified.xml' line 65535: Element '{http://scap.nist.gov/schema/vulnerability/0.4}cve-id': [facet 'pattern'] The value 'CVE-2017-1000367' is not accepted by the pattern 'CVE-([1,2])\d{3}-\d{4}'.
File './nvdcve-2.0-modified.xml' line 65535: Element '{http://scap.nist.gov/schema/vulnerability/0.4}cve-id': 'CVE-2017-1000367' is not a valid value of the atomic type '{http://scap.nist.gov/schema/cve/0.1}cveNamePatternType'.
```
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
=> CVE: IDs are now 4-7 digits long

src/common/util.h
We will not remove this macro, because it can stay and we should keep
the prefixes. Instead, we can write docs.
This is a follow up of https://github.com/OpenSCAP/openscap/pull/940.
=> Comment OSCAP_GSYM macro

utils/oscap-ssh
With this switch, oscap-ssh will run oscap with --oval-results
and download all generated oval xmls to current directory, mimicking
behaviour of oscap tool itself.
Scan on remote machine is now triggered in temp directory to not
leave artifacts in $HOME.
Fixes #863
=> Update oscap-ssh to support --oval-results

utils/oscap_docker_python/oscap_docker_util.py
This fixes a known issue: https://bugzilla.redhat.com/show_bug.cgi?id=1454637
The code contained calls to cleanup functions, but they were not effective, because the entity that kept track of temp images was left out of the process. Specifically, the `DockerMount` instance was not passed to the `_cleanup_by_path` and a new one was constructed there instead.
I have modified the code so that the cleanup code path is preserved for the `oscap_chroot` method. The code path for `scan_cve` and `scan` has changed - creation of the new `DockerMount` was avoided by passing the existing instance. I have tested the `scan` path and it performs according to expectations.
=> Fix oscap-docker to clean up temp image.

src/XCCDF_POLICY/xccdf_policy_remediate.c, tests/API/XCCDF/unittests/test_generate_fix_ansible_vars_ds.xml, tests/API/XCCDF/unittests/test_generate_fix_ansible_vars_golden.yml, tests/API/XCCDF/unittests/test_generate_fix_ansible_vars_golden_altered.yml, tests/API/XCCDF/unittests/test_generate_fix_ansible_vars_golden_tailoring.yml
The previous code allocated wrong amount of memory for the remediation fix body.
If the second remediation body was longer than body of the first one, there was not enough of memory allocated. The first remediation was always handled correctly, and third, fourth etc. remediations usually got much more memory than they needed.
Fixes https://github.com/OpenSCAP/scap-security-guide/issues/2593
Update: The issue was caused by assuming that the "return value" of `pcre_exec` `ovector` is relative to `start_offset`. However, we have verified that it contains (absolute) indices of the `fix_text` string.
=> Fixed string length bug related to ansible remediations.

xsl/xccdf-report-impl.xsl
HTML report was missing human readable text for the new reference uris in SSG.
=> Add missing group-by-rule texts for new reference uris from SSG

xsl/Makefile.am, xsl/xccdf-references.xsl, xsl/xccdf-report-impl.xsl
- Makes it easier to update reference mapping rather than searching for them
- Allows references to also be consumed by xccdf-guide-impl.xsl
=> Move references to separate XSL file

ac_probes/configure.ac.tpl, configure.ac
When requiring `python2` bindings and no `python2` interpreter is available, the configure script will abort with an error message.
The `configure.ac` template section for `python3` has been slightly refactored.
=> Increased robustness of configure script regarding to Python.

src/OVAL/oval_enumerations.c
=> Fix unknown subtype handling in oval_subtype_parse

src/OVAL/probes/SEAP/sexp-manip.c
This makes oscap scans way way faster in debug mode. On my machine it makes it roughly 3 times faster.
This issue was found by @jan-cerny , see #981
=> Don't repeatedly call getenv in SEXP_VALIDATE

ac_probes/configure.ac.tpl, configure.ac, m4/python.m4, swig/python2/Makefile.am, tests/Makefile.am, tests/bindings/Makefile.am
This PR should fix the handling of different Python major versions in different environments for good (see discussion at the end of #990).
I have took the `python.m4` macro, refactored it and tested that it works. If conditions permit, I will try to push this to upstream Automake.
Highlights of this PR are:
* Correct and relatively easy handling of Python2 and Python3 interpreters and environments.
* Greedy build of Python bindings - if possible, they are built, if not possible, no fatal error is raised. The explicit choice to build or not to build them is preserved - in that case, if a binding can't be built for whatever reason, an error is raised.
* The "preferred_python" for oscap-docker is now selected by checking for the Atomic module availability, prioritizing Python3 over Python2. …
=> Refactored the Python handling in build scripts.

src/XCCDF/elements.h
While some platforms (e.g. Linux) accept stuff like printf("%s\n", NULL) others (e.g. Solaris) don't like this and raise a SIGSEGV.
=> Avoid passing NULL parameters to oscap_seterr

src/OVAL/probes/independent/filehash.c, src/OVAL/probes/independent/filehash58.c, src/OVAL/probes/independent/filemd5.c, src/OVAL/probes/independent/textfilecontent.c, src/OVAL/probes/independent/textfilecontent54.c, src/OVAL/probes/independent/xmlfilecontent.c, src/OVAL/probes/oval_fts.c, src/OVAL/probes/oval_fts.h, src/OVAL/probes/unix/file.c, src/OVAL/probes/unix/fileextendedattribute.c, src/OVAL/probes/unix/gconf.c, src/OVAL/probes/unix/linux/selinuxsecuritycontext.c, src/OVAL/probes/unix/sysctl.c, src/common/util.c, src/common/util.h, tests/API/probes/oval_fts_list.c, tests/offline_mode/Makefile.am, tests/offline_mode/test_offline_mode_system_info.sh, tests/offline_mode/test_offline_mode_textfilecontent54.sh, tests/offline_mode/test_textfilecontent54.sh, tests/offline_mode/textfilecontent54.oval.xml
The textfilecontent(54) probes were not able to read from file in the guest filesystem if a file with the same name doesn't exist on host filesystem.
Fixes #1001.
This PR first reverts commit 908d002c68e43a3d3c3bede128c535fbee815a10 and then it adds new commits that change the offline mode in the probes, namely: 
* textfilecontent
* textfilecontent54
* filehash
* filehash58
* xmlfilecontent
* file
* fileexetendedattribute
* selinuxsecuritycontext
The problem with the commit  908d002c68e43a3d3c3bede128c535fbee815a10 is that it ignores how oval_fts functions work. They traverse the host filesystem, handle OVAL file behaviors, check if the filesystem is remote, check recurse directions, ... 
The revert commit will revert us back to use `chroot()`.
I tried to find some way how to enable …
=> Fix offline scan in probes

docs/manual/manual.adoc
It is already possible to build family and system info probe using Microsoft Visual Studio 2017. We don't need to tell developers contributing on Windows that they have to build OpenSCAP without probes.
=> Update "Build OpenSCAP Using Visual Studio" section in User Manual

src/common/util.c
oscap_dirname must work same as dirname(). However on Windows
it works different. We need to fix it according to 'man 3 dirname':
If path is a null pointer or points to an empty string, then both
dirname() and basename() return the string ".".
If path does not contain a slash, dirname() returns the string ".".
=> Fix oscap_dirname on Windows

src/OVAL/probes/unix/linux/rpminfo.c, src/OVAL/probes/unix/linux/rpmverify.c, src/OVAL/probes/unix/linux/rpmverifyfile.c, src/OVAL/probes/unix/linux/rpmverifypackage.c
We thought the OWN mode would work because rpmtsSetRootDir seems well
suited for it. However rpmtsSetRootDir is not 100% supported by librpm
so it causes false-positives and false-negatives. Let's switch back to
chroot mode until this is fixed in librpm.
=> Use chroot offline mode for rpm probes

src/OVAL/oval_sexp.c, src/OVAL/oval_sysEnt.c
This PR provides 2 fixes in the `record` element in OVAL System Characteristics Schema.
When we will add WMI57 Windows probe in future, these fixes will enable us to produce valid XML OVAL results.
Also, it should fix ldap57, sql57 and sql probes, but I haven't tested ldap57, sql57 and sql probes.
**1) Fix namespace of OVAL record field element**
The field element should not have same namespace as its parent element. It should have oval-system-characteristics namespace instead. This bug is caused by wrong usage of xmlSearchNsByHref function, which should have the current mode, not the root node, as argument.
Addressing:
```
File 'results.xml' line 113: Element
'{http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows}field':
This element is not expected. Expected is ( …
```
=> OVAL record fixes

utils/oscap-cvrf.c, utils/oscap-ds.c, utils/oscap-info.c, utils/oscap-oval.c, utils/oscap-tool.c, utils/oscap-xccdf.c, utils/oscap.c
Instead of a hack with '\r\t\t\t\t' we will indent the help options manually.
Fixes #1023.
=> Remove '\r' characters from help output

src/OVAL/results/oval_resultTest.c
Some probes can produce an OVAL item that contains a record element. In
some OVAL tests the OVAL state contains record element. To evaluate the
OVAL test, we need to compare OVAL state with OVAL item. Therefore we
need to compare the record element in the OVAL state with the record
element in the OVAL item produced by probe. Unfortunately, the 2 record
elements comparison have not been implemented in OpenSCAP yet, so I have
done a basic implementation of the 2 record comparison in this commit.
See
https://oval.mitre.org/language/version5.11/ovaldefinition/documentation/oval-definitions-schema.html#EntityStateRecordType
I have checked this code with Windows WMI57 probe.
Addressing:
```
Definition oval:mil.disa.stig.windows:def:165: error
OpenSCAP Error: OVAL internal error: found NULL …
```
=> Support comparing state record elements with item

src/XCCDF/result.c
I found this code in my `git stash`, so I think it would be useful
to create a commit from it and share it on Github.
There is a second place where we collect IP addresses of the
scanned machine. These are saved to XCCDF results and are shown
in HTML report. So this change is very visible.
I understand that XCCDF and OVAL are different things, however
I don't like that this copies a lot of code from the system info
probe.
=> Add IP addresses in XCCDF results on Windows

ac_probes/configure.ac.tpl, configure.ac, src/common/oscap_acquire.c
When configure is run with --enable-sce, add a new parameter --with-sce-script-dir to set the directory path for SCE to store and execute script files (default /tmp). Configure will append -DSCE_SCRIPT_DIR to CFLAGS (P_tmpdir is always defined by stdio.h, which is included by curl.h. Therefore we added SCE_SCRIPT_DIR to prevent the provided cflag from being overwritten.)
=> Adding with-sce-script-dir flag to configure.ac. Fixes #1016

README.md
- The build fails without `gcc-c++` installed on the system:
```
$ cmake ..
-- The C compiler identification is GNU 8.1.1
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:3 (project):
No CMAKE_CXX_COMPILER could be found.
Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.
-- Configuring incomplete, errors occurred!
See also …
```
=> Add gcc-c++ to dependencies

CMakeLists.txt
Without this change it will report UNIX probes enabled even though ENABLE_PROBES is OFF.
```
-- OVAL:
-- base probe support: FALSE
-- SEAP msgid bit-size: 32
-- independent probes: ON
-- unix probes: ON
-- linux probes: ON
-- solaris probes: OFF
```
After this change:
```
-- OVAL:
-- base probe support: FALSE
-- SEAP msgid bit-size: 32
-- independent probes: OFF
-- unix probes: OFF
-- linux probes: OFF
-- solaris probes: OFF
```
=> The probes compile options all depend on ENABLE_PROBES

.gitignore
Definitely not necessary, but helpful.
=> Hide Makefiles, /Testing in gitignore

swig/perl/CMakeLists.txt, swig/python2/CMakeLists.txt, swig/python3/CMakeLists.txt
CMake Deprecation Warning at /usr/share/cmake/Modules/UseSWIG.cmake:272 (message):
SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
swig/python2/CMakeLists.txt:9 (swig_add_module)
=> Avoid cmake swig deprecation warnings

.github/issue_template.md
Largely similar to the one in [scap-security-guide](https://github.com/OpenSCAP/scap-security-guide/blob/master/.github/issue_template.md), but includes directions of where to report issues at the top.
=> Added GitHub issue template

README.md, docs/contribute/contribute.adoc, docs/contribute/testing.adoc, docs/contribute/versioning.adoc, tests/test_common.sh.in
We are missing a guide on how to write tests and where to put them which makes it hard for contributors to add tests for their PRs.
WIP progress:
* updated `docs/contribute/contribute.adoc`
* updated `README.md` to ling to `docs/contribute/contribute.adoc`
* updated `docs/contribute/versioning.adoc`
=> Add a guide for writing and running tests

src/XCCDF_POLICY/xccdf_policy.c, tests/API/XCCDF/parser/Makefile.am, tests/API/XCCDF/parser/test_extensions.sh, tests/API/XCCDF/parser/test_known_extensions.xml, tests/API/XCCDF/parser/test_malformed_extensions.xml, tests/API/XCCDF/parser/test_proprietary_extensions.xml
When evaluating XCCDF, if a check uses a system that is not registered (and no other checks can be selected), emit a warning. (Targets maint-1.2 versus master)
Closes: #768 
Replaces: #1054 
Per @mpreisler's comment on #1054:
@shawndwells what do you think about the wording?
=> Warn about non-registered check systems

docs/contribute/testing.adoc, tests/sce/test_sce_streams_fill.sh, tests/test_common.sh.in
Update of the testing guide added through https://github.com/OpenSCAP/openscap/pull/1065 for master CMake buildsystem.
=>  CMake related update of testing guide in the master branch

src/OVAL/oval_component.c, src/OVAL/probes/SEAP/public/strbuf.h, src/OVAL/probes/crapi/digest.c, src/XCCDF_POLICY/xccdf_policy_remediate.c
Helps with #1085 probably... (no macOS to test on).
Add `#include <sys/types.h>` to a bunch of files that are missing it for `ssize_t`. According to [here](https://opensource.apple.com/source/xnu/xnu-344/bsd/sys/types.h) -- a really out of date source -- it should have that header, and `ssize_t` is defined in that header.
=> Add ssize_t header for macOS build

swig/openscap.i
If probes are not enabled but building with python3 is, SWIG fails due to probe bindings. This fixes that.
=> Disable probes in SWIG

CMakeLists.txt
- When CMAKE_BUILD_TYPE is not specified, it is set to none which causes problems for
builds on different operating systems.
=> Set CMAKE_BUILD_TYPE

CMakeLists.txt
Similarly to build directory, the build-win32 directory contains
build binaries and therefore it shouldn't be a part of source
tarball.
=> Do not include build-win32 directory in the source tarball

swig/perl/CMakeLists.txt
A correct file name should be openscap_pm.pm, according to
the target name. Addressing:
```
CMake Error at swig/perl/cmake_install.cmake:61 (file):
file INSTALL cannot find
"/home/jcerny/openscap/build/swig/perl/openscap.pm".
Call Stack (most recent call first):
swig/cmake_install.cmake:42 (include)
cmake_install.cmake:54 (include)
```
=> Fix broken file name in install command in SWIG Perl bindings

appveyor.yml
This runs `cpack` and adds an AppVeyor Artifact.
See https://www.appveyor.com/docs/packaging-artifacts/
=> Build Windows Installer in AppVeyor

dist/CMakeLists.txt, src/SCE/CMakeLists.txt
1) Install sce_engine_api.h
We have forgotten to add an install command for SCE public header.
2) Install Bash completion to a right directory
It should be usually installed to '/etc', not to '/prefix/etc'.
=> Fix install commands in CMake

appveyor.yml
After we have made a default build type Release in da92c1b8a3
we don't need this in AppVeyor anymore.
=> Remove CMAKE_BUILD_TYPE=Release

release_tools/README.adoc
As we have discussed in Issue #434, providing Windows binaries
can be achieved by including the Windows build in the release
process. Also, the build is already described in Developers
Manual, so we need to link it and describe only how to build
the Installer package.
Fixes #434.
=> Add Windows build to the upstream release guide

tests/probes/filehash58/Makefile.am, tests/probes/filehash58/check_filehash_simple.xml, tests/probes/filehash58/test_probes_filehash58.sh
This PR adds a test that tests expected pass and failiure of the `filehash58` probe when doing offline scanning.
=> Add test for filehash58 offline mode.

CMakeLists.txt, docs/CMakeLists.txt, docs/contribute/testing.adoc, docs/developer/developer.adoc, docs/manual/manual.adoc
We need to be able to generate HTML documentation using Asciidoc instead of Asciidoctor, because on some systems Asciidoctor is not available.
The asciidoc command does not support certain syntax that is
supported by asciidoctor command. Fortunately, we can use syntax
that is compatible with both programs. Most notable changes are:
- Do not use triple backquotes for monospaced text, use single
backquotes that work in both programs.
- Use ---- for source code listing everywhere because they
are rendered differently in asciidoc than indented blocks,
whereas in asciidoctor they looked the same as indented blocks.
- Use explicit wrapping in source code listing because asciidoc
doesn't wrap long lines implicitly in source code listings,
which causes ugly overlows and extremely long lines that …
=> Using AsciiDoc instead of Asciidoctor to generate HTML documentation

dist/bash_completion.d/oscap, utils/oscap-chroot, utils/oscap-chroot.8, utils/oscap-ssh, utils/oscap-vm, utils/oscap-vm.8, utils/oscap-xccdf.c
This option has been deprecated and has been replaced by --check-engine-results,
which is more generic. With upcoming major release we can remove it.
=> Remove deprecated option --sce-results

utils/oscap-oval.c, utils/oscap.8
Users can get a list of probes using `oscap --version` instead.
The extra submodule is not needed in the TUI.
Also, the options of this submodule stopped to be useful after
probes have become part of main oscap process.
=> Remove 'oscap oval list-probes' submodule

src/OVAL/probes/SEAP/generic/strto.c, src/OVAL/probes/SEAP/generic/strto.h, src/OVAL/probes/SEAP/sexp-parser.c, tests/API/SEAP/test_api_seap_parser.c
Because `strtoll`/`strtoull` take a null-terminated
C-string, keep the `strto_` functions as wrappers,
but explicitly null-terminate inputs. This is useful
in the parser, where inputs to `strto_`* are length
terminated substrs of the input.
Fixes the SEAP parser test case failure on gcc 8.1.1
by removing the internal implementation and using `strtoll`
instead.
Signed-off-by: Alexander Scheel <ascheel@redhat.com>
I can redo this PR against `maint-1.2` if you prefer, but I removed a number of unimplemented functions in the header (I'm not sure if it is public or not), so I proposed it against `master`.
=> Clean up implementation of strto_ functions

src/OVAL/probes/SEAP/sexp-parser.c
Fixes error discovered by fuzzing:
./tests/API/SEAP/test_api_seap_parser '"\x'
will segfault due to out of bounds access, expecting more
characters due to \x denoting the start of a hexadecimal
encoding of a character. Because this is unused/unimplemented
(as referenced by the `abort()`), remove this functionality.
Signed-off-by: Alexander Scheel <ascheel@redhat.com>
This should be ported to `master` afterwards.
=> Remove unused hexadecimal logic in SEXP double quote parsing

dist/bash_completion.d/oscap, utils/oscap-tool.h, utils/oscap-xccdf.c
This option has been replaced by a possibility to hide/show selected
XCCDF result types by clicking on checkboxes in the HTML report.
Moreover, this option does not work now. I think it is a leftover
from the old style report, which was kept due to backwards compatibility.
With upcoming major release we can remove it.
=> Remove option '--show' from 'oscap xccdf generate report'

src/CVRF/cvrf_priv.c
```
[37/323] Building C object src/CVRF/CMakeFiles/cvrf_object.dir/cvrf_priv.c.o
../src/CVRF/cvrf_priv.c: In function ‘cvrf_score_set_to_dom’:
../src/CVRF/cvrf_priv.c:1684:7: warning: passing argument 1 of ‘free’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
free(base);
^~~~
```
=> The function was freeing unowned memory using const pointers

src/CVRF/cvrf_eval.c
```
[36/323] Building C object src/CVRF/CMakeFiles/cvrf_object.dir/cvrf_eval.c.o
../src/CVRF/cvrf_eval.c:278:20: warning: ‘get_rpm_name_from_cvrf_product_id’ defined but not used [-Wunused-function]
static const char *get_rpm_name_from_cvrf_product_id(struct cvrf_session *session, const char *product_id) {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Removed an unused static fn from CVRF

src/OVAL/oval_session.c, src/OVAL/public/oval_session.h, utils/oscap-chroot, utils/oscap-chroot.8, utils/oscap-oval.c, utils/oscap-ssh, utils/oscap-ssh.8, utils/oscap-tool.h, utils/oscap-vm, utils/oscap-vm.8
Dropping `--probe-root` option from `oscap oval eval`. It only sets
an environment variable which users can set themselves. Moreover,
it clashes with utilities like oscap-chroot or oscap-docker.
=> Remove --probe-root option

src/XCCDF_POLICY/xccdf_policy_remediate.c
This helps if someone uses <fix></fix> without a terminating newline
=> add a safety \n before the end script comment.

docs/CMakeLists.txt
Makes the 'docs' an independent target, which does not depend on
'ALL' pseudotarget. This brings us back fast incremental rebuilds,
which is useful for developing and debugging. Users can still build
the documentations easily using 'make docs'.
=> Do not build the documentation on every build

tests/probes/runlevel/test_probes_runlevel.sh
If the list of services returned by `chkconfig --list` is empty,
then the generated OVAL file would be invalid. Since there would
not be anything to test in that situation, it would be better
to skip the test instead. This situation can happen on modern
Linux distributions that have only native systemd services.
=> Skip sysctl probe test if no SysV services are found

.travis.yml, docs/developer/developer.adoc
A few Travis improvements copied from #1156. Install dependencies via the `apt` addon seems less error prone than the previous method.
Also includes a documentation fix.
=> Travis improvements

src/common/public/oscap_error.h
These occurences were inside a comment. Again, we see that
it was not a good idea to perform this change automatically.
=> Remove suspicious occurences of OSCAP_API in oscap_error.h

src/CPE/cpedict.c, src/CPE/cpedict_priv.c, src/CPE/cpedict_priv.h, src/CPE/cpelang_priv.h, src/CPE/public/cpe_dict.h, src/CPE/public/cpe_lang.h, src/XCCDF_POLICY/xccdf_policy.c
Move accessors functions for `cpe_lang_model.origin_file` and `cpe_dict_model.origin_file` to private headers.
They are used to set references files of CPE dictionary files in OVAL check references.
=> Set CPE lang and dict origin_file accessors as private

src/CPE/cpedict.c, src/CPE/cpelang.c, src/CPE/cpename.c, src/CPE/public/cpe_dict.h, src/CPE/public/cpe_lang.h, src/CPE/public/cpe_name.h, tests/API/CPE/dict/test_api_cpe_dict.c, tests/API/CPE/lang/test_api_cpe_lang.c, tests/API/CPE/lang/test_api_cpe_lang.sh, tests/API/CPE/name/test_api_cpe_uri.c
This removes CPE evaluator functions not used within openscap.
=> Cleanup CPE API Evaluators

tests/check_public_api.py
This commit introduces a new short Python script that compares the exported
symbols in libopenscap.so with symbols marked as OSCAP_API in public header
files. The script prints out 2 lists:
* a list of symbols that are exported in binary, but are not marked as public
* a list of symbols that are marked as public, but are not exported in binary
=> Introduce a script for comparison of symbols in SO and public headers

src/CVRF/cvrf_priv.c, src/CVRF/public/cvrf.h
These functions had prototypes in header file, but they had
no implementation. Also, there was an incosistent naming of
cwe member of cvrf_vulnerability structure. These functions
are not defined normally, but they are defined using
OSCAP_IGETINS_GEN. I don't like this approach at all.
=> Add unimplemented functions from CVRF public API

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
F29 has been branched from Rawhide. Rawhide becomes future F30.
See https://fedoraproject.org/wiki/Releases/29/Schedule
=> Add Fedora 30 CPE

CMakeLists.txt, docs/CMakeLists.txt
Closes: #1161
`Signed-off-by: Alexander Scheel <ascheel@redhat.com>`
I'm not entirely sure why the diff is so ugly, but I guess that's fine.
Tested with:
```
BUILD_CMAKE_ARGS="-DENABLE_DOCS=ON -DCMAKE_INSTALL_PREFIX=/tmp/cmake_test" build clean prep build nopop && ninja install
BUILD_CMAKE_ARGS="-DCMAKE_INSTALL_PREFIX=/tmp/cmake_test_2" build clean prep build nopop && ninja install
```
Results:
```bash
$ find /tmp/cmake_test -type f | grep 'doc/openscap/html'
/tmp/cmake_test/share/doc/openscap/html/structprobe__icache__t.html
/tmp/cmake_test/share/doc/openscap/html/structxiconf__attr.html
/tmp/cmake_test/share/doc/openscap/html/sysctl__probe_8h_source.html
/tmp/cmake_test/share/doc/openscap/html/structxccdf__group__item.html
/tmp/cmake_test/share/doc/openscap/html/structxccdf__refine__rule …
```
=> Add ENABLE_DOCS to control building documentation

tests/check_public_api.py
This PR wants to make 3 small improvements in `check_public_api.py`:
* Remove standard symbols from the set
* Match global variables, not only functions
* Print only if the difference is nonempty
=> Improve check_public_api.py script

configure.ac
The same target of the check (`rpm`) screwed up other checks.
Checks for different `librpm` versions have `rpm4`, `rpm5`, ... targets
that are then transferred to the `rpm_...` env variables.
Fixes #453
=> Made the rpm-related pkg-config configuration more robust.

src/common/debug.c, src/common/public/oscap_debug.h, utils/oscap-ds.c, utils/oscap-info.c, utils/oscap-oval.c, utils/oscap-tool.c, utils/oscap-vm.8, utils/oscap-xccdf.c, utils/oscap.8
Verbose mode was originally introduced first to `oscap oval` module, because the feature was focused to debugging OVAL evaluation. Later, it was extended to `xccdf eval` and then to various other modules.
To be able to extend the verbose mode, we will make the `--verbose` and `--verbose-log-file` global options. In other words, those 2 options will be applicable to all the modules.
A drawback of this approach could be that many parts of our code are not covered by any verbose messages, which means the verbose mode produces often (almost) empty output.
This PR also reflects this CLI change in manual pages.
=> Make verbose mode a common option for all modules

src/CVRF/cvrf_priv.c, src/OVAL/oval_message.c, src/OVAL/oval_sysEnt.c, src/OVAL/probes/fsdev.c, src/OVAL/probes/independent/textfilecontent.c, src/OVAL/probes/independent/textfilecontent54.c
Fix some defects, which could lead to memory leaks.
There are some variables which have allocated memory but they aren't free before 'return' from function.
=> Add some missing free calls to prevent possible memory leaks

utils/oscap-docker.in, utils/oscap_docker_python/oscap_docker_util.py
* Streamlined the code.
* Propagate the oscap return code as script's return code.
Before, the command returned 1 if `oscap` returned other than 0 or 2. The return value of the scanning routine was the `oscap`'s `stdout`.
Now, both the `stdout` and `stderr` are forwarded to the console, and the `oscap`'s return code is propagated.
As this changes return code backwards-compatibility, I am not sure whether this fix is feasible.
=> Refactored the oscap-docker script.

utils/oscap-ssh, utils/oscap-ssh.8
This PR allows the caller to pass SSH connection options.
The use case for this is the SSG test suite - as containers or VMs have the same IP address but different SSH server certificates, one would be bothered by the `known_hosts` records that would cause false alarms.
This PR consists of some refactoring and backwards-compatible usage of the `SSH_ADDITIONAL_OPTIONS` environment variables for a list of SSH options.
=> Allow oscap-ssh to use custom SSH options

src/OVAL/oval_probe_ext.c
openscap-1.3.0_alpha1/src/OVAL/oval_probe_ext.c:725: va_init:
Initializing va_list "ap".
openscap-1.3.0_alpha1/src/OVAL/oval_probe_ext.c:747: missing_va_end:
va_end was not called for "ap".
745|
746|   		if (pd == NULL) {
747|-> 			return -1;
748|   		}
749|   		ret = oval_probe_sys_eval(pext->pdtbl->ctx, pd,
*(pext->model), inf);
=> Add missing va_end

src/OVAL/probes/crapi/digest.c
Plug a memory leak
openscap-1.3.0_alpha1/src/OVAL/probes/crapi/digest.c:78: alloc_fn:
Storage is returned from allocation function "malloc".
openscap-1.3.0_alpha1/src/OVAL/probes/crapi/digest.c:78: var_assign:
Assigning: "ctbl" = storage returned from "malloc(num * 40UL)".
openscap-1.3.0_alpha1/src/OVAL/probes/crapi/digest.c:89: leaked_storage:
Variable "ctbl" going out of scope leaks the storage it points to.
87|   	if (num <= 0 || fd <= 0) {
88|   		errno = EINVAL;
89|-> 		return -1;
90|   	}
91|           for (i = 0; i < num; ++i)
Plug a memory leak
openscap-1.3.0_alpha1/src/OVAL/probes/crapi/digest.c:78: alloc_fn:
Storage is returned from allocation function "malloc".
openscap-1.3.0_alpha1/src/OVAL/probes/crapi/digest.c:78: var_assign:
Assigning: "ctbl" = storage returned from …
=> Plug  memory leaks in digest.c

src/OVAL/probes/independent/textfilecontent54.c
Error: RESOURCE_LEAK (CWE-772): [#def28]
openscap-1.3.0_alpha1/src/OVAL/probes/independent/textfilecontent54_probe.c:144:
alloc_fn: Storage is returned from allocation function
"SEXP_string_newf".
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/sexp-manip.c:616:9: alloc_fn:
Storage is returned from allocation function "SEXP_new".
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/sexp-manip.c:1587:16:
alloc_fn: Storage is returned from allocation function "malloc".
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/sexp-manip.c:1587:16:
var_assign: Assigning: "s_exp" = "malloc(16UL)".
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/sexp-manip.c:1596:9:
return_alloc: Returning allocated memory "s_exp".
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/sexp-manip.c:616:9:
var_assign: Assigning: "sexp" = "SEXP_new()". …
=> Plug memory leaks

src/OVAL/probes/independent/textfilecontent_probe.c
The leak was found after assume_d macro was replace by if code.
- Move the free for line_ent and ent_val before check for error condition,
they should be freed anyway.
- Add free for other leaking SEXP variables.
=> Fix leak in textfilecontent_probe

src/OVAL/probes/probe/ncache.c
Free newly created SEXP `ref` before returning.
The leak was found after assume_d macro was replace by if code.
=> Fix leak in OVAL/probes/probe/ncache.c

src/OVAL/probes/unix/linux/rpmverifypackage_probe.c
Free `g_rpm` structure - free `probe_chroot` (close fd + free scan_path)  and free memory.
Only for master branch, because `g_rpm` is static variable in maint-1.2.
=> Free "g_rpm" variable in src/OVAL/probes/unix/linux/rpmverifypackage_probe.c

src/OVAL/probes/probe/worker.c
Add `mask` variable to `SEXP_vfree` call which frees all parameters.
=> Add missing 'free' calls to src/OVAL/probes/probe/worker.c (maint-1.2 branch)

CMakeLists.txt
This policy was introduced in CMake 3.3.
Fixes #1188.
=> Check if CMake policy CMP0063 is defined

src/OVAL/probes/unix/process.c, src/SCE/sce_engine.c, src/XCCDF_POLICY/xccdf_policy_remediate.c
* Refactored cleanup section of `_xccdf_fix_execute`:
`fix_text` is allocated in `_xccdf_fix_decode_xml` and was possibly freed in `_write_text_to_fd_and_free`, but in meantime could have been be jumped over free, causing a memory leak.
* Improved freeing process of the env_values array: 
Extracted the process into a function and called it where it was missing.
* Freed a se_ruid sexp that is deep-copied by probe_item_create.
=> Fixed some Coverity issues

src/XCCDF/xccdf_session.c, src/common/oscap_acquire.c
* Added free of `dir_name` in `oscap_acquire_guess_realpath`: Unlike `dirname`, `oscap_dirname` allocates space for the result on the heap.
* Removed redundant `oscap_strdup`: Unlike `basename`, `oscap_basename` already allocates space for the result on the heap.
=> Coverity fixes related to oscap_...name

src/OVAL/probes/SEAP/seap-command-backendS.c
`Stable_free` complements `Stable_new`.
Original Coverity finding:
```
Error: RESOURCE_LEAK (CWE-772): [#def18]
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/seap-command-backendS.c:137: alloc_fn: Storage is returned from allocation function "Stable_new".
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/seap-command-backendS.c:78:2: alloc_fn: Storage is returned from allocation function "malloc".
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/seap-command-backendS.c:78:2: var_assign: Assigning: "t" = "malloc(16UL)".
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/seap-command-backendS.c:85:9: return_alloc: Returning allocated memory "t".
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/seap-command-backendS.c:137: var_assign: Assigning: "n" = storage returned from "Stable_new(32UL)". …
```
=> Fixed a memory leak, introduced Stable_free.

src/OVAL/probes/SEAP/seap-command.c
Fixed memory leaks in `OVAL/probes/SEAP/seap-command.c` caused by not freeing the allocated memory before returning from the function `SEAP_cmd_exec`.
```
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/seap-command.c:308: alloc_fn: Storage is returned from allocation function "SEAP_packet_new".
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/seap-packet.c:46:19: alloc_fn: Storage is returned from allocation function "malloc".
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/seap-packet.c:46:19: var_assign: Assigning: "p" = "malloc(40UL)".
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/seap-packet.c:47:9: noescape: Resource "p" is not freed or pointed-to in function "memset". [Note: The source code implementation of the function has been overridden by a builtin model.] …
```
=> OVAL/probes/SEAP/seap-command.c: fixed memory leaks

src/CVRF/cvrf_priv.c, utils/oscap-cvrf.c
Do not free oscap_source when parsing cvrf_xml for index.
It should not be the duty of cvrf xml parsing function to free its
source of input.
Plus, cvrf_index_import is also called in function
cvrf_session_new_from_source. In cvrf_session structure,
the import source is part of the strucutre along with cvrf index, it
make no sense to free it.
=> Don't free oscap_source when parsing cvrf_xml

src/OVAL/probes/probe-api.c, src/OVAL/probes/unix/linux/selinuxsecuritycontext.c
Also extracted non-trivial generation of probe items to functions.
Original Coverity report (applies to the `master` branch:
```
Error: RESOURCE_LEAK (CWE-772): [#def70]
openscap-1.3.0_alpha1/src/OVAL/probes/unix/linux/selinuxsecuritycontext_probe.c:147: alloc_arg: "split_range" allocates memory that is stored into "h_category".
openscap-1.3.0_alpha1/src/OVAL/probes/unix/linux/selinuxsecuritycontext_probe.c:102:3: alloc_arg: "split_level" allocates memory that is stored into "*h_c".
openscap-1.3.0_alpha1/src/OVAL/probes/unix/linux/selinuxsecuritycontext_probe.c:71:3: alloc_fn: Storage is returned from allocation function "strdup".
openscap-1.3.0_alpha1/src/OVAL/probes/unix/linux/selinuxsecuritycontext_probe.c:71:3: var_assign: Assigning: "*category" = "strdup(level_split + 1)". …
```
=> Make sure that intermediate results are freed.

src/OVAL/probes/SEAP/sexp-manip.c
Coverity reports 2 false positives:
```
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/sexp-manip.c:934: overwrite_var: Overwriting "list" in "list = SEXP_list_new_rv(list, memb, ap)" leaks the storage that "list" points to.
```
and
```
openscap-1.3.0_alpha1/src/OVAL/probes/SEAP/sexp-manip.c:1037: overwrite_var: Overwriting "sexp" in "sexp = SEXP_list_rest_r(sexp, list)" leaks the storage that "sexp" points to.
```
In both cases pointer variable is passed as an argument to a function which only accesses that pointer but does not modify it.
=> OVAL/probes/SEAP/sexp-manip.c: fixed false positives reported by coverity

src/CVRF/cvrf_priv.c, src/OVAL/probes/SEAP/seap-command-backendS.c, src/OVAL/probes/SEAP/seap-command.c, src/OVAL/probes/SEAP/sexp-manip.c, src/OVAL/probes/independent/textfilecontent54_probe.c, src/OVAL/probes/probe-api.c, src/OVAL/probes/unix/linux/selinuxsecuritycontext_probe.c, src/OVAL/probes/unix/process_probe.c, src/SCE/sce_engine.c, src/XCCDF_POLICY/xccdf_policy_remediate.c, utils/oscap-cvrf.c
This PR merges maint-1.2 to master.
=> Merge maint-1.2

src/OVAL/probes/unix/linux/selinuxsecuritycontext.c
This message is annoying because it pollutes the output.
It is an usual situation.
=> Change category of message

src/OVAL/oval_sexp.c, src/OVAL/probes/probe-api.c, src/SCE/sce_engine.c
Fix:
- free `key` from `src/OVAL/oval_sexp.c`
- `elm_name` and `elm_res` from `src/OVAL/probes/probe-api.c`
- `free_env_values` from `src/SCE/sce_engine.c`
=> Fix some coverity issues for maint-1.2

docs/modules, src/OVAL/probes/fsdev.c, src/OVAL/probes/fsdev.h, tests/API/probes/CMakeLists.txt
This is a low level implementation detail which we probably
shouldn't publish in our public API.
=> Move "fsdev" out of public API

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml, src/XCCDF/benchmark.c, src/XCCDF/item.c, src/XCCDF/item.h
This commit adds CPEs for Windows systems (Windows 7, 8, 8.1, 10,
Server 2008, Server 2012) to OpenSCAP CPE dictionary.
The PR doesn't fix #1181 though, because according to NVD the CPE for Windows 7 is `cpe:/o:microsoft:windows_7`, not `cpe:/o:microsoft:windows7`
=> Add Windows CPEs

src/CVRF/cvrf_priv.c, src/OVAL/probes/unix/linux/iflisteners.c
* Plug a memory leak in CVRF
If there is 0 iterations of the outer while loop, the 'filtered_ids'
variable isn't freed. Fortunately, we can allocate it inside
the while loop. If it's not free'd in this function, it is free'd
in cvrf_product_status_free.
* Specify size of the buffer in fscanf
The terminating null byte is not included in the length.
=> Fix 2 Coverity problems

src/OVAL/probes/independent/textfilecontent54.c
The variable substrs is not allocated if want_substrs is false.
=> Supress a coverity false positive

swig/src/openscap.i
The free is not needed after PR #1238 was merged and the memory is freed in the `fail` section.
=> Removed redundant free.

tests/API/probes/oval_fts_list.c
The Coverity reported only one omission, but IMO there were much more:
```
Error: RESOURCE_LEAK (CWE-772): [#def4]
openscap-1.3.0/tests/API/probes/oval_fts_list.c:69: alloc_fn: Storage is returned from allocation function "SEXP_string_new".
openscap-1.3.0/src/OVAL/probes/SEAP/sexp-manip.c:605:9: alloc_fn: Storage is returned from allocation function "SEXP_new".
openscap-1.3.0/src/OVAL/probes/SEAP/sexp-manip.c:1593:16: alloc_fn: Storage is returned from allocation function "malloc".
openscap-1.3.0/src/OVAL/probes/SEAP/sexp-manip.c:1593:16: var_assign: Assigning: "s_exp" = "malloc(16UL)".
openscap-1.3.0/src/OVAL/probes/SEAP/sexp-manip.c:1602:9: return_alloc: Returning allocated memory "s_exp".
openscap-1.3.0/src/OVAL/probes/SEAP/sexp-manip.c:605:9: var_assign: Assigning: "sexp" = …
```
=> Fixed memory leaks in a test.

appveyor.yml
Adds maint-1.3 to the list because AppVeyor CI only builds branches
specified in `appveyor.yml`.
=> Add maint-1.3 to Appveyor

utils/oscap-ssh
A call to `shift` is necessarry outside of any function, because one can't use `shift` to shift script's arguments from a function.
=> Fixed a bug with sudo as the first argument.

src/SCE/CMakeLists.txt
After installing the library to /usr/lib64/ oscap wasn't able to find
SCE plugin and SCE was not shown in list of plugins in `oscap -V`. That
was because the `libopenscap_sce.so` library could not be loaded because
it contained unresolved symbol `__oscap_seterr`. We need to add
`error.c` and its dependencies to make sure `ldd` doesn't report any
unresolved symbols.
=> Ensure there are no unresolved symbols in libopenscap_sce.so

src/CVRF/cvrf_eval.c, utils/oscap-cvrf.c
Addressing:
```
#0  0x00007ffff4b486e9 in cvrf_model_filter_by_cpe (model=0x0,
cpe=0x600c0000bde0 "Red Hat Enterprise Linux Desktop Supplementary
(v. 6)")
at cvrf_priv.c:1293
#1  0x00007ffff4b4d35e in find_all_cvrf_product_ids_from_cpe (
session=session@entry=0x60080000a4d0) at cvrf_eval.c:172
#2  0x00007ffff4b4debe in cvrf_model_get_results_source
(import_source=<optimized out>,
os_name=os_name@entry=0x555555584660 "Red Hat Enterprise Linux
Desktop Supplementary (v. 6)") at cvrf_eval.c:230
#3  0x0000555555574c58 in app_cvrf_evaluate (action=0x7fffffffe2c0) at
oscap-cvrf.c:102
#4  0x0000555555566e16 in oscap_module_call (action=0x7fffffffe2c0) at
oscap-tool.c:261
#5  oscap_module_process (module=0x55555578ffc0 <CVRF_EVALUATE_MODULE>,
module@entry=0x55555578a120 <OSCAP_ROOT_MODULE>, …
```
=> RHBZ#1642283: Segmentation fault in CVRF

src/OVAL/probes/unix/xinetd_probe.c
This fixes issues with the test_probe_xinetd_duplicates unit test should
there be no /etc/services for whatever reason.
=> Fix issues with trailing whitespaces in op_assign_str()

src/XCCDF_POLICY/xccdf_policy_remediate.c
If "current" is empty string, then end = current - 1 which is
invalid address.
Unfortunately discovered after I merged #1268
=> Fix possible invalid read

src/OVAL/probes/unix/linux/dpkginfo.c
It may happen that 'Dir::Cache::pkgcache' is set to an empty string
to save some space (e.g. Ubuntu Xenial docker image does that), and in
such case calling dpkginfo_probe_main will end up in a SEGFAULT.
This commit checks if dpkg initialization has succeded before performing
any check.
This issue affects 1.2 and 1.3 versions of OpenSCAP.
Fix for 1.3 - https://github.com/OpenSCAP/openscap/pull/1270
=> dpkginfo_init doesn't check if dpkg cache initialization has succeeded.

configure.ac, m4/python.m4, src/XCCDF_POLICY/xccdf_policy_remediate.c, tests/API/XCCDF/unittests/test_remediate_python.xccdf.xml, tests/API/XCCDF/unittests/test_remediate_python_subs.xccdf.xml
* Added possibility to specify Python interpreter for `urn:xccdf:fix:script:python` using `--with-preferred-python` configure argument.
* Added support for explicit `urn:xccdf:fix:script:python2` and `urn:xccdf:fix:script:python3`.
* Fixed tests that were broken for Python3.
=> Increased flexibility of the Python remediation script runner.

tests/probes/sysctl/test_sysctl_probe_all.sh
- add blacklist for confidential kernel params
- set PATH explicitly to make sure sysctl is found
fix for #1263
=> Change test_sysctl_probe_all to succeed for non-root users

tests/probes/sysctl/test_sysctl_probe_all.sh
Complements #1265, fixes #1263.
=> Expand the sysctl test blacklist so it passes.

tests/nist/nist_test.sh, tests/test_common.sh.in
1. Use preferred python for NIST test
Recently we have realized that we want to run gating CI of PRs
of maint-1.2 branch on Python3-only operating systems. Therefore
we need to use the Python version found by configure script.
=> fix pull request gating on Python3-only systems

src/XCCDF_POLICY/xccdf_policy_remediate.c
The same XCCDF value can appear in multiple rules, which means
there can be same variable in multiple Ansible task. But when
we generate a Playbook we should put the variable only once.
Ansible produces a warning if there are multiple definitions
of the same variable.
See https://github.com/OpenSCAP/openscap/pull/896 for further context if you are interested.
=> Prevent duplicate variables in Ansible Playbooks

tests/probes/rpmverifypackage/test_probes_rpmverifypackage.sh
Suse does not use epoch for rpms, therefor the test will always fail.
fix for #1264
=> Disable test_probes_rpmverifypackage_epoch for Suse based systems

src/XCCDF/xccdf_session.c
This commit changes the `oscap` behavior in the following way:
If `oscap xccdf eval` is called with both `--results-arf` and
`--report` the HTML report will contain `OVAL details` section
even if `--oval-results` is not given by the user.
I think we can do it because the ARF file already contains OVAL
results anyway. I think it's not convenient to type `--oval-results`
explicitly.
=> Show details in HTML report by default if --results-arf is given

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
Fedora 30 has been branched from Rawhide. Rawhide becomes future
Fedora 31. See https://fedoraproject.org/wiki/Releases/30/Schedule
=> Add Fedora 31 CPE

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
Extends openscap built-in CPE dictionary with Oracle Linux 8 support.
Checked patch to work on Oracle Linux 8 OS.
=> Add OL8 CPE name to OpenSCAP dictionary

src/OVAL/results/oval_resultSystem.c, src/XCCDF/xccdf_session.c, tests/oval_details/test_oval_details.sh, utils/oscap.8
Users will no longer need to specify `--oval-results` to get the OVAL details in HTML report. The OVAL details will be shown always.
I know this change is highly controversial, but it has been requested multiple times, for example in #1262.
Moreover, I have discovered that it isn't true that you have to specify `--results` together with report. Probably this statement has been forgotten in the man page during the HTML report redesign.
=> Always show OVAL details in HTML report

.travis.yml
- The --graphviz brew install option seems to be broken for doxygen.
This removes the option from the Travis configuration.
=> Remove --graphviz from TRAVIS CI for MacOS

src/OVAL/probes/independent/textfilecontent54.c
The effect of the code removed by this patch is that the max_depth, recurse, recurse_direction and recurse_file_system attributes of the behaviors element are completely ignored and reset to their default values if filepath element is specified in the textfilecontent54_object. This is against OVAL specification
and it is inconsistent with file probe, from where a similar code has been removed in 93d5f1416f232d6fa21fe8f2ad771d003749ea7b.
=> Don't ignore file behaviors if filepath is specified

utils/oscap-podman
The `oscap-podman` script should make it possible to perform the SCAP evaluation of podman images and containers. The script complements `oscap-docker` script which does the same for docker images and containers.
Currently, there are multiple issues with offline scanning in RPM probes (for example https://github.com/OpenSCAP/openscap/issues/1173) which prevent this script to work without issues (the same applies also for the `oscap-docker` script).
=> Added utils/oscap-podman for SCAP evaluation of podman images and containers

src/XCCDF/result.c, src/XCCDF/xccdf_impl.h
There can both be rules covering multiple STIG IDs (easy to handle: just
output the same result multiple times), and STIG IDs covered by more
than one rule. The DISA Stig Viewer seems to only consider the last
result for a given rule when it imports results, so when that last rule
happens to pass, that means the whole STIG will be marked as 'not a
finding'. To counteract that, this commit attempts to merge the results
in a sensible way - only if all tests passed, the STIG should be
marked as 'not a finding' in the way.
I'm not attempting to merge anything besides the result state, because the STIG Viewer seems to ignore all that information anyways.
(Note that currently, [ComplianceAsCode/content](https://github.com/ComplianceAsCode/content) doesn't handle these N:N connections very well …
=> improve --stig-viewer output when there is no 1:1 connection between rules

src/OVAL/probes/probe/worker.c
In chroot mode, sometimes we'll get `fchdir failed: Bad file descriptor` error and the oscap will be aborted. 
This PR is to reset the file descriptor variables when the descriptors are already closed. so it won't go to the `if` condition again and try to do `fchdir` with invalid descriptor parameter.
=> Reset chroot file descriptor after closed

src/DS/sds.c
When loading a DS session, there can remote components.
If `--fetch-remote-resources` option is not provided, the resources pointed by the components won't be downloaded.
```shell
$ oscap xccdf eval --profile pci-dss ~/git/scap-security-guide/build/ssg-fedora-ds.xml 
WARNING: Datastream component 'scap_org.open-scap_cref_security-data-oval-com.redhat.rhsa-RHEL7.xml.bz2' points out to the remote 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2'. Use '--fetch-remote-resources' option to download it.
WARNING: Skipping 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2' file which is referenced from datastream
OpenSCAP Error: Could not extract scap_org.open-scap_cref_ssg-fedora-xccdf-1.2.xml with all dependencies from datastream. …
```
=> Allow DS session to continue without remote resources

tests/DS/Makefile.am, tests/DS/ds_continue_without_remote_resources/remote_content_1.2.ds.xml, tests/DS/ds_continue_without_remote_resources/remote_content_1.3.ds.xml, tests/DS/test_ds.sh
* Test for PR #1324 which verifies that DS session does not quit
when SCAP 1.3 content contains remote component but
`--fetch-remote-resources` option is not provided. The test is
also extended to verify that scans utilizing SCAP 1.2 and 1.3
datastreams produce the same results.
=> Add test for DS session and SCAP 1.3 remote resources

src/OVAL/probes/fsdev.c, src/OVAL/probes/public/fsdev.h, tests/API/probes/Makefile.am, tests/API/probes/all.sh, tests/API/probes/test_fsdev_is_local_fs.c
Some file systems can be mounted using autofs, which should be
considered during analysis of /etc/mtab. For more details,
please see the comment introduced in this patch.
=> Handle autofs entries in /etc/mtab

tests/DS/ds_continue_without_remote_resources/remote_content_1.2.ds.xml, tests/DS/ds_continue_without_remote_resources/remote_content_1.3.ds.xml
Addressing:
```
$ oscap ds sds-split remote_content_1.2.ds.xml /tmp/xxx
$ oscap oval validate --schematron /tmp/xxx/test_single_rule.oval.xml
<?xml version="1.0"?>
oval:x:obj:1 - referenced variable oval:x:var:1 not found. The var_ref entity must hold a variable id that exists in the document.
```
=> Fix invalid OVAL in test ds_continue_without_remote_resources

schemas/oval/5.11.2/oval-definitions-schema.xsd, schemas/oval/5.11.2/oval-system-characteristics-schema.xsd
Similar to 8ba623120fc9f479285f9d6032cb925db420011d but for OVAL 5.11.2.
The missing namespace imports have already been fixed in
32d4d9be295084f95bfbaec07ea84373b3b4aeb7. Addressing:
```
File '/root/openscap/schemas/oval/5.11.2/oval-definitions-schema.xsd'
line 1446: local union type: A type, derived by list or union, must have
the simple ur-type definition as base type, not
'{http://oval.mitre.org/XMLSchema/oval-definitions-5}(NULL)'.
File '/root/openscap/schemas/oval/5.11.2/oval-definitions-schema.xsd'
line 1459: local union type: A type, derived by list or union, must have
the simple ur-type definition as base type, not
'{http://oval.mitre.org/XMLSchema/oval-definitions-5}(NULL)'.
File '/root/openscap/schemas/oval/5.11.2/oval-definitions-schema.xsd'
line 1472: local union type: A …
```
=> Resolve parsing issues with OVAL 5.11.2 schemas

tests/API/probes/Makefile.am, tests/API/probes/fake_mtab, tests/API/probes/test_fsdev_is_local_fs.c
The test uses a fake `mtab` file which contains 4 entries for a local filesystem, 1 entry for a direct autofs map, 1 entry for a NFS system mounted using autofs and 1 entry for a mounted cifs system. By parsing the `mtab` file only 4 local filesystems should be found. It will help us to test https://github.com/OpenSCAP/openscap/pull/1329
=> Extend unit test for is_local_fs from fsdev.h

tests/DS/test_ds.sh
* `--oval-results` option is not default in `maint-1.2` branch
=> Add --oval-results to the ds_continue_without_remote_resources test

src/OVAL/probes/unix/sysctl.c
Directory /proc/sys/fs/binfmt_misc is a separate file system,
mounted by systemd-automout and is represented by an autofs
entry in /etc/mtab. /proc/sys/fs/binfmt_misc is mounted
on demand when accessed. If accessed the first time, we don't
have a way to determine the if the autofs is remote or local.
See 309f8230d67f229b6091876c3ace62370fb3d451.
However, we don't see a reason why not to traverse the whole
/proc/sys regardless the type of file systems mounted there.
=> Do not skip 'fs.binfmt_misc.status' by sysctl probe

tests/probes/sysctl/test_sysctl_probe_all.sh
The `net.core.bpf_jit_limit` kernel parameter cannot be set by
non root users and so add it to blacklist in the test.
=> Update blacklist of kernel params with net.core.bpf_jit_limit

cpe/openscap-cpe-oval.xml
Since Fedora 30 there is no more a single fedora-release RPM
package. There is fedora-release-common and then the specific
package for the type of realease, for example
fedora-release-workstation. Similar to:
https://github.com/ComplianceAsCode/content/pull/4372
=> Update Fedora CPE OVAL

src/OVAL/probes/fsdev.c, src/OVAL/probes/public/fsdev.h, tests/API/probes/Makefile.am, tests/API/probes/test_fsdev_is_local_fs.c
It isn't necessary to expose this function in public API.
The function has been accidentaly introduced to public API
in fff58197d9747a08d0fc23914a31fefbe44f07ea which hasn't
been released yet, so it can be safe to remove it.
=> Make is_local_fs static again

docs/developer/developer.adoc
[tests/bz2/test_bz2_datastream.sh](https://github.com/OpenSCAP/openscap/blob/maint-1.3/tests/bz2/test_bz2_datastream.sh) uses `bzip2`. This tool is in `bzip2` package (not in `bzip2-devel` mentioned in build dependencies).
=> Mention bzip2 dependency for tests in documentation

CMakeLists.txt, oscap_wrapper.in, run.in
* ~Renamed run to oscap_wrapper.~
* ~Make the compiled oscap invocation part of the scipt.~
* Introduced the oscap_wrapper script that contains the compiled oscap invocation.
* Improved comments of the run script, to make it's usage more explicit.
Making this 1.3-only as this heavily depends on the build system.
=> Improved UX of executing oscap right after compilation.

release_tools/versions.sh
Future version of OpenSCAP is 1.2.18. Latest released version is 1.2.17.
Latest supported Fedora is 31 (current Rawhide). Latest RHEL is 8.
=> Update versions.sh in maint-1.2

src/OVAL/probes/SEAP/MurmurHash3.c
Build produces a lot of warnings about fallthrough, e.g.
```
MurmurHash3.c:132:14: warning: this statement may fall through [-Wimplicit-fallthrough=]
case 3: k1 ^= tail[2] << 16;
~~~^~~~~~~~~~~~~~~~
```
but it is intended. `#pragma GCC diagnostic` disables these warning messages.
=> Disable fallthrough warnings in switch

tests/probes/process58/command_line.sh
The old creating zombie process did not work properly (seems like there were some changes in planning/stopping processes) and it caused problems with running tests (it was randomly passing/failing/waiting because of the test).
The commit also changes waiting for process, because the name of created zombie process isn't `stopped_process.sh`, but `command_line.sh` (line [98](https://github.com/mildas/openscap/blob/a923e01a29df6e051d9b8a0dfa2336084adb1829/tests/probes/process58/command_line.sh#L98)), so it was waiting 30 seconds for `stopped_process.sh` zombie, but it never appears.
=> Change creating of zombie process and waiting for processes at process58 test

src/SCE/sce_engine.c
Similar to 793475c2dfddf4d122722f097b99b5e0d0ca48ce assign an
emtpy string to XCCDF value if xccdf_value_binding_get_value
returns NULL.
=> Fix (null) string when XCCDF value not set

src/OVAL/probes/unix/linux/dpkginfo-helper.cxx
apt 1.9 cleans up the header includes a bit, causing the build
to fail, so add the additional headers we are missing.
=> Include additional headers in dkpginfo-helper for apt 1.9

utils/oscap-ssh
Fixes e.g. the problem of `oscap` arguments `-p (all)`.
Now, `(all)` is escaped, so it not intercepted by the shell.
=> Made oscap-ssh to work with shell-sensitive args.

run.in, utils/CMakeLists.txt, utils/oscap-docker.in, utils/oscap_docker_python/oscap_docker_util.py
added option to choose `oscap` executable for `oscap-docker` invocation;
`oscap-docker` is now executable in build/utils;
extended PYTHONPATH with \<SRC\>/utils in `run`;
added PYTHONDONTWRITEBYTECODE to `run`.
This will allow execution of commands like:
`sudo ./run utils/oscap-docker --oscap=utils/oscap image registry.access.redhat.com/rhel7 oval eval probe_test_rpm.oval.xml`
=> Add ability to run uninstalled oscap-docker

docs/manual/manual.adoc
Users don't know what the results of rule evaluation mean. Although
it's specified in XCCDF specification, it's easier to find it
described in user's manual. I have mostly copied the table 26 from
https://csrc.nist.gov/CSRC/media/Publications/nistir/7275/rev-4/final/documents/nistir-7275r4_updated-march-2012_clean.pdf
and have added some OpenSCAP specific examples.
=> Add XCCDF results into user manual

src/OVAL/oval_probe.c
When a probe that can evaluate the given OVAL object isn't present
it will tell user which specific type of OVAL object isn't supported
Related to:
https://bugzilla.redhat.com/show_bug.cgi?id=1640889
=> Show which OVAL object isn't supported

src/OVAL/oval_probe.c
Addressing:
```
openscap/src/OVAL/oval_probe.c: In function ‘oval_probe_query_object’:
openscap/src/OVAL/oval_probe.c:145:15: warning: implicit declaration of function ‘oscap_sprintf’; did you mean ‘oscap_vsprintf’? [-Wimplicit-function-declaration]
char *msg = oscap_sprintf("OVAL object '%s_object' is not supported.", type_name);
^~~~~~~~~~~~~
oscap_vsprintf
openscap/src/OVAL/oval_probe.c:145:15: warning: initialization of ‘char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
```
=> Fix build warning

src/OVAL/probes/unix/linux/rpmverifypackage_probe.c
The probe is using chroot in the init function, where all the packages
information is being collected. So, the comment is actually misleading
everybody and the probe should be switched to the custom offline mode
right away.
This will fix #1173, [RHBZ#1603347](https://bugzilla.redhat.com/show_bug.cgi?id=1603347).
I used the content attached to the RHBZ ticket to check this patch. I ran all the test from this file (not just 6, as in example) and all where successful (except for 8, but that is expected I suppose).
=> Fix #1173, RHBZ#1603347: Double chdir/chroot in probe rpmverifypackage

src/XCCDF_POLICY/xccdf_policy.c, tests/API/XCCDF/unittests/test_xccdf_check_processing_selector_empty.sh, tests/API/XCCDF/unittests/test_xccdf_check_unsupported_check_system.sh, tests/API/XCCDF/unittests/test_xccdf_check_without_content_refs.sh, tests/API/XCCDF/unittests/test_xccdf_multiple_testresults.sh, tests/API/XCCDF/unittests/test_xccdf_notchecked_has_check.sh, utils/oscap-xccdf.c
In "--progress" mode we print out the rule id and ': ' before the rule
evaluation starts and the rest of the line after the rule evaluation
finishes. If any warning occurs during the evaluation, it's printed in
the middle, which looks ugly. We can fix this by printing the
whole line at the same moment, after the rule evaluation finishes.
Also, the warnings should use dW macros in order to be able to turn them
on/off using `--verbose` option.
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1640889
=> Prevent broken output in "--progress" mode

src/OVAL/probes/unix/linux/rpminfo.c
When the queried RPM package has null epoch (or "(none)" as returned by "rpm -q --qf '%{EPOCH}\n'" command), the rpminfo_item produced by the probe didn't contain any filepath element. To use the null epoch as a parameter of rpmdbSetIteratorRE, the "(none)" string should be replaced by "0".
I have a reproducer on Fedora 30: [rpminfo_reproducer.zip](https://github.com/OpenSCAP/openscap/files/3421607/rpminfo_reproducer.zip) The rpminfo_item in OVAL results doesn't contain any filepath.
=> Fix missing filepaths in rpminfo items

src/OVAL/probes/unix/linux/selinuxsecuritycontext_probe.c
The probe is supposed to check security context (extended attrs.)
of objects in question. The fact that SELinux is enabled or
disabled is irrelevant to this check.
Fixes #1332
=> OVAL/selinuxsecuritycontext: Remove the is_selinux_enabled check.

utils/oscap-xccdf.c
`oscap xccdf generate fix --fix-type anaconda` was failing, because of wrong template associated with the fix type.
=> Fix --fix-type anaconda

utils/oscap-oval.c, utils/oscap.8
- Fix typo in oscap manpage.
- Add missing option from oval eval help usage documentation (--fetch-remote-resources)
=> Fix typo in manpage and add missing option help usage documentation.

utils/oscap-oval.c
Similarly to oval-id and datastream-id.
=> fetch-remote-resources can be used only together with datastreams

xsl/oval-to-xccdf.xsl, xsl/xccdf-share.xsl
Previously, public description of each erratum was available under
https://rhn.redhat.com/errata/
at some point in time this has changed to
https://access.redhat.com/errata/
and since not all links redirect properly from old to new, we have to fix
OpenSCAP end as well.
This enables people reviewing XCCDF policy guide or XCCDF result report to click
on RH[SBE]A-YYYY-ABCD acronym and be redirected to public description of the
given erratum.
=> Fix URL link mechanism for Red Hat Errata

src/XCCDF/result.c
As described over at ComplianceAsCode/content [issue#4846](https://github.com/ComplianceAsCode/content/issues/4846) the STIG Viewer URI change is causing problems with newly created security benchmarks and the ```--stig-viewer``` output.
This PR adds the new URI ```https://public.cyber.mil/stigs/srg-stig-tools/``` as an additional identifier. The olf URI is still in place to be backward compatible with existing security benchmarks.
=> Add new STIG Viewer URI public.cyber.mil and be backward compatible

src/XCCDF/result.c
As described in [PR#1401](https://github.com/OpenSCAP/openscap/pull/1401) the STIG Viewer URI change is causing problems with newly created security benchmarks and the ```--stig-viewer``` output.
This PR is addressing the issue for the 1.2 branch.
=> Add new STIG Viewer URI public.cyber.mil and be backward compatible in maint-1.2

src/DS/sds.c, src/OVAL/oval_agent.c, src/OVAL/oval_component.c, src/OVAL/oval_probe_ext.c, src/OVAL/probes/SEAP/seap-packet.c, src/OVAL/probes/SEAP/sexp-manip_r.c, src/OVAL/probes/oval_fts.c, src/OVAL/probes/unix/linux/rpmverifypackage_probe.c, src/OVAL/probes/unix/process_probe.c, src/source/oscap_source.c
This fixes some memory leaks in sds.c, printf format string mistakes, and
a possible NULL ptr dereference.
=> Cleanup some warnings reported by Coverity and cppcheck.

swig/openscap_api.py
Lets use `__repr__()` to infer object structure, instead of `__str__()`.
`__str__()` returns different strings on different python versions
On python2, it returns something like
`'_e016160100000000_p_xccdf_result_iterator'`
On python3, it returns something like
`'<Swig Object of type 'struct xccdf_result_iterator *' at 0x7fc81474adb0>'`
`__repr__()` returns the second format on both python versions.
Fixes traceback where it tried to use a strange function:
```
Traceback (most recent call last):
File "get_results.py", line 17, in <module>
results = benchmark.get_results()
File "/usr/lib64/python3.6/site-packages/openscap_api.py", line 196, in __getter_wrapper
list.generate(OSCAP_Object.new(retobj))
File "/usr/lib64/python3.6/site-packages/openscap_api.py", line 89, in generate
while …
```
=> SWIG openscap_api: Use __repr__() to get consistent string output

swig/openscap_api.py
When running for instance this : sess = oscap.oval.agent_new_session(oval_def, "...."), the returned object representation is like this : <Swig Object of type 'oval_agent_session_t *' at 0x7f9aa2cdf360> 
However, the regex modified some days ago is [commit 149785d](https://github.com/DominiqueDevinci/openscap/commit/149785de3ec374c3eb395fa14a1c68add9ac6f8e) always expects a struct object (which isn't the case of oval_agent_session_t);
It produce something like this:
`Traceback (most recent call last):
File "test.py", line 48, in <module>
sess = oscap.oval.agent_new_session(oval_def, "oval_is_quadcore");
File "/usr/local/lib/python3.6/dist-packages/openscap_api.py", line 203, in __getter_wrapper
return OSCAP_Object.new(retobj)
File "/usr/local/lib/python3.6/dist-packages/openscap_api.py", …
=> SWIG Python : bug fixes related to the internal object type

src/SCE/sce_engine.c, utils/CMakeLists.txt, utils/oscap-run-sce-script
Hello,
I experienced recently an error already signalled in issue #528 . As suggested by Martin Presiler, i've used a wrapper (so it's easy to fix a problem linked to the wrapper for everyone). My wrapper parse the shebang (or use bash by default if there is no shebang).
I use the wrapper only if there is no posssibility to acquire +x rights on the extracted .sh file, so the legacy code is not affected (and the wrapper is less reliable than a direct execution, so it's better to only use in when needed).
Result:
With a /tmp partition with noexec mode: 
```oscap xccdf eval --verbose INFO test_sce_in_ds.xml
I: oscap: Identified document type: data-stream-collection
I: oscap: Created a new XCCDF session from a SCAP Source Datastream 'test_sce_in_ds.xml'.
I: oscap: Identified document type: …
```
=> Fix #528 - Eval SCE script when /tmp is in mode noexec

src/OVAL/probes/probe/input_handler.c, src/OVAL/probes/probe/probe.h, src/OVAL/probes/probe/probe_main.c, src/OVAL/probes/probe/worker.c
We have discovered a problem when testing offline mode in the symlink
probe. When the probe main function needs to be executed multiple times,
function `probe_common_main`, where the chroot is entered, is called
only once, but function `probe_worker`, which leaves the chroot, is called
many times. This leads to a situation that the first OVAL test is
evaluated in chroot, but all further tests have retrieved data from the
host. Therefore the collected data were wrong. We try to address this
problem by moving the code.
EDIT:
* I have checked that the symlink probe test proposed without that #1428 fails without my patch and passes with the patch applied. Actually it's vice-versa due to  `PROPERTIES WILL_FAIL true` in CMakeLists.txt
* tests of RPM probes from #1430 started to pass when I …
=> Move the chroot call to probe_worker

docs/developer/developer.adoc, tests/probes/symlink/CMakeLists.txt, tests/probes/symlink/test_offline_mode_symlink.sh, tests/test_common.sh.in, utils/CMakeLists.txt
Some offline-mode tests require chroot syscalls during execution.
The build system and test suite are now aware of this and support build/usage of oscap "buddy binary" that is oscap with setcap chroot blessing.
The person who builds may either decide to run `sudo make oscap-chrootable`, or `make oscap-chrootable-nocap` followed by manual `setcap` call.
=> Modified test suite to make use of setcap-blessed oscap binary.

src/OVAL/probes/probe/probe.h, src/OVAL/probes/probe/worker.c, src/OVAL/probes/unix/linux/rpminfo_probe.c
The env variable OSCAP_PROBE_RPMDB_PATH isn't set anywhere,
therefore this mode isn't used anywhere.
=> Remove unused PROBE_OFFLINE_RPMDB mode

src/OVAL/probes/probe-table.c, src/OVAL/probes/unix/linux/dpkginfo-helper.cxx, src/OVAL/probes/unix/linux/dpkginfo-helper.h, src/OVAL/probes/unix/linux/dpkginfo_probe.c, src/OVAL/probes/unix/linux/dpkginfo_probe.h
Adding PROBE_OFFLINE_OWN support was very easy. But still there is a problem here: I'm unable to check any pkgcache.bin, be it a mounted file from VM or local file without any chroot shenanigans. The `new pkgCache (dpkg_mmap);` call always returns error 'The package cache file is corrupted'.
I'll just leave it here in case someone could shed some light on the matters.
This PR will also fix #1367
=> Dpkg info offline mode, fixes

utils/oscap-chroot, utils/oscap-podman, utils/oscap-vm, utils/oscap_docker_python/oscap_docker_common.py
Removes these environment variables: OSCAP_PROBE_OS_NAME,
OSCAP_PROBE_OS_VERSION, OSCAP_PROBE_ARCHITECTURE. They are not
read anywhere since 1c18a7b22ef50d0687e52cadb547e05eb29d5159,
so we don't have to set them.
Fixes #1427.
=> Remove unused environment variables

tests/API/OVAL/unittests/test_object_component_type.oval.xml, tests/DS/test_ds_misc.sh, tests/DS/test_sds_eval.sh, tests/probes/rpm/rpmverifyfile/test_probes_rpmverifyfile.sh, tests/probes/rpm/rpmverifyfile/test_probes_rpmverifyfile_older.sh, tests/probes/runlevel/test_probes_runlevel.sh, tests/probes/sysctl/test_sysctl_probe_all.sh, tests/probes/uname/test_probes_uname.xml.sh, tests/test_common.sh.in
Added minimal patches to handle skip tests that depend specifically on rpm or chkconfig, or to use dpkg-query as an alternative when possible.  I don't know if this is the best solution but I can get past most of `make test` with these changes, except for one outstanding test related to `uname`.
=> Adjusting unittests for building on Debian10

src/OVAL/probes/SEAP/MurmurHash3.c, tests/API/SEAP/test_api_seap_spb.c, tests/API/probes/test_fsdev_is_local_fs.c
test_api_seap_spb.c:204:25: warning: variable ‘b’ set but not used [-Wunused-but-set-variable]
test_fsdev_is_local_fs.c:37:12: warning: ‘ment’ is used uninitialized in this function [-Wuninitialized]
MurmurHash3.c:82:30: warning: always_inline function might not be inlinable [-Wattributes] (x4)
=> Fix warnings

swig/perl/CMakeLists.txt, swig/python3/CMakeLists.txt
The suppression is already there, but it is not really effective for all of the warnings
=> Suppress SWIG-related warnings

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
Fedora 31 has already been released and the current Rawhide
(as of 2020-01-02) is F32.
=> Add Fedora 32 CPE

src/OVAL/oval_agent.c, src/XCCDF_POLICY/public/xccdf_policy.h, src/XCCDF_POLICY/xccdf_policy.c, src/XCCDF_POLICY/xccdf_policy_engine.c, src/XCCDF_POLICY/xccdf_policy_engine_priv.h, src/XCCDF_POLICY/xccdf_policy_model_priv.h, tests/API/XCCDF/unittests/test_xccdf_check_content_ref_without_name_attr.oval.xml, tests/API/XCCDF/unittests/test_xccdf_check_multi_check2.sh, tests/API/XCCDF/unittests/test_xccdf_check_multi_check2.xccdf.xml, utils/oscap-xccdf.c, xsl/xccdf-report-impl.xsl
Shows OVAL Definition ID and Title when an XCCDF rule uses
multi-check='true'. The multi-check is used in rule
security_patches_up_to_date in SCAP 1.3 datastreams. It wasn't possible
to see which vulnerabilities have been found because all the checks have
the same XCCDF rule ID.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1771438
Fixes: #1320
=> Show check identifiers at multi-check rules

.travis.yml
I think this will fix the broken Travis build on OSX. Python is present there in asuitable version, see the CMake output:
```
-- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.7.5", minimum required is "3") 
-- Found PythonLibs: /usr/local/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib (found suitable version "3.7.5", minimum required is "3")
```
So it looks that we don't have to upgrade Python.
=> Remove python upgrade

xsl/xccdf-share.xsl
Links showing and hiding remediation snippets in HTML guides generated by Openscap were not accessible to screenreader users. This is now fixed by adding appropriate parameters to the <a> tag in the XSLT template.
=> make links showing remediation snippets in guides accessible

utils/oscap-podman
It makes sure that /run/.containerenv gets created.
Tested with ubi8-init from redhat and the output is:
```
$ oscap-podman registry.access.redhat.com/ubi8-init oval eval --id oval:ssg-installed_env_is_a_container:def:1 --oval-id scap_org.open-scap_cref_ssg-rhel8-oval.xml /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml 
Definition oval:ssg-installed_env_is_a_container:def:1: true
Evaluation done.
```
=> oscap-podman: add podman init to every scanned image/container.

src/OVAL/probes/probe/worker.c
When the probe doesn't implement offline mode function it means
the probe doesn't support offline mode, therefore it should
set the supported_offline_mode flag to PROBE_OFFLINE_NONE.
This omission caused that the probe was run and scanned the host.
=> Do not run probes if they don't support offline mode

tests/probes/password/CMakeLists.txt, tests/probes/password/test_probes_password_offline.sh, tests/probes/password/test_probes_password_offline.xml
The probe does not support any of offline modes,
thus it should return "not applicable" response.
=> Add "offline" mode test for the password OVAL probe

src/OVAL/public/oval_definitions.h
This fixes SCAP Workbench build.
Addressing:
```
[ 37%] Building CXX object CMakeFiles/scap-workbench.dir/scap-workbench_autogen/mocs_compilation.cpp.o
In file included from /usr/local/include/openscap/xccdf_policy.h:39,
from /home/jcerny/work/git/scap-workbench/include/TailoringDockWidgets.h:31,
from /home/jcerny/work/git/scap-workbench/build/scap-workbench_autogen/6YEA5652QU/moc_TailoringDockWidgets.cpp:10,
from /home/jcerny/work/git/scap-workbench/build/scap-workbench_autogen/mocs_compilation.cpp:18:
/usr/local/include/openscap/oval_definitions.h:1676:117: error: declaration of ‘operator,’ as parameter
1676 | restriction *oval_variable_possible_restriction_new(oval_operator_t operator, const char *hint);
|                                                                             ^ …
```
=> Do not use C++ keyword operator as a function parameter name

tests/API/XCCDF/unittests/test_report_anaconda_fixes.sh
There should be 2 equal ways of generating Anaconda remediations:
"oscap xccdf generate fix --fix-type anaconda" and
"oscap xccdf generate fix --template urn:redhat:anaconda:pre"
Both commands should give the same output.
This tests a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1736850
introduced by b1448ec95a957a76eb8be6d439531c532d97ff3c
=> Add a test to check --fix-type anaconda

CMakeLists.txt, cmake/FindACL.cmake
This might be a Fedora 31ism or a later version of CMake but found some issues where CMake wasn't finding some of the installed libraries.
=> Fix case where CMake couldn't find libacl or xattr.h

utils/oscap-podman
In case that a container image and a running container have the same
name, `oscap-podman` scans container image and a running container is
skipped. This might be unexpected and might cause a confusion for user.
Therefore, this commit adds a code which detects such situation and
rather informs user about ambiguous scan target and terminates.
In such cases the unique container image/container ID should be used
for specifying the target of the scan.
=> utils/oscap-podman: Detect ambiguous scan target

cmake/FindACL.cmake
find_path parameter `NAMES` values should be separated. According to
https://cmake.org/cmake/help/latest/command/find_path.html it should be:
`NAMES name1 [name2 ...]`
find_library parameter `NAMES` either should not contain `lib` or should
contain both `lib` and `.so.` The documentation at
https://cmake.org/cmake/help/latest/command/find_library.html says: Each
library name given to the `NAMES` option is first considered as a
library file name and then considered with platform-specific prefixes
(e.g. `lib`) and suffixes (e.g. `.so`).
This bug caused that even if cmake reported that libacl was found, the
library wasn't linked to the built `libopenscap.so`. Also,
`HAVE_ACL_EXTENDED_FILE`, `HAVE_ACL_LIBACL_H` and `HAVE_SYS_ACL_H` were
undefined in `config.h`, which caused some guarded …
=> Fix FindACL.cmake

src/XCCDF_POLICY/xccdf_policy_remediate.c, utils/oscap-xccdf.c, utils/oscap.8
Given a DS has Rules `<fix>` elements with `@system=urn:xccdf:fix:script:machineconfig`, allow `oscap` to generate `machineconfig` for a Profile, or based on scan results.
Example usage:
- Profile:
`oscap xccdf generate fix --profile hipaa --fix-type machineconfig --output machineconfig_hipaa.yml jhorozek-ssg-rhel8-ds.xml`
- When `resuts.xml` is available: 
`oscap xccdf generate fix --result-id xccdf_org.open-scap_testresult_xccdf_org.ssgproject.content_profile_hipaa --fix-type machineconfig --output machineconfig_hipaa.yml ../results.xml`
This is a very simple MVP implementation. It will simply take any remediation text in element 
`<xccdf:fix id="*" system="urn:xccdf:fix:script:ignition">` and concatenate them in the output.
At this moment it is not known if any kind of processing will …
=> Allow oscap to generate machineconfig fix

src/XCCDF/result.c
We add timezone information to the evaluation start date
and time using the format defined in XML specification
https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dateTime
We can't use strftime as strftime's %z modifier doesn't
put ':' (colon) between hours and minutes in timeshift
which is required by XML specification.
Fixes: #1449
=> Add timezone to XCCDF TestResult start/end time

src/OVAL/probes/unix/process58_probe.c, src/OVAL/probes/unix/process_probe.c, src/OVAL/probes/unix/shadow_probe.c
This should fix failed builds with GCC 10 on Rawhide.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1793914
=> Fix duplicate global variables

src/OVAL/probes/unix/linux/systemdunitdependency_probe.c
Systemd units trees can contain cycles in them, which causes infinite recursion in our probe.
We will save processed units in a hash table and if we meet an unit that is already processed we won't process it again.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1478285
See comment 11 in this BZ for a reproducer.
This PR also contains some refactoring to make the bug fix easier. For more details about specific changes please read the commit messages of respective commits.
=> Prevent infinite recursion in systemdunitdependency probe

src/XCCDF_POLICY/xccdf_policy_remediate.c, tests/API/XCCDF/unittests/CMakeLists.txt, tests/API/XCCDF/unittests/test_ansible_yaml_block_scalar.playbook.yml, tests/API/XCCDF/unittests/test_ansible_yaml_block_scalar.sh, tests/API/XCCDF/unittests/test_ansible_yaml_block_scalar.xccdf.xml
We are removing empty lines from generated Ansible Playbook.  It looks
nice, but there is a catch.
Ansible tasks are a YAML snippets. So they contain YAML block scalars,
indicated by a pipe (|). Within these block scalars, the newlines should
be preserved.  By removing the empty lines from the scalars we are
actually changing the meaning of the scalars.
Unfortunately, OpenSCAP doesn't understand YAML, but only reads the
Ansible fix line-by-line as s string. That means it doesn't know when it
reads a block scalar. Therefore we need to stop removing the empty lines
anywhere.
This commit also adds a small test.
Resolves: RHBZ#1795563
=> Do not drop empty lines from Ansible remediations

utils/oscap-ssh
Depending on the umask configuration of the target system, "sudo oscap"
may create the result files in temporary directory with 600 permissions,
which makes retrieving the log (as the regular user that ssh'ed to the
system) impossible:
~~~
$ oscap-ssh --sudo user@system 22 xccdf eval ...
[...]
oscap exit code: 0
Copying back requested files...
scp: /tmp/tmp.0kfbPWEy6u/report.html: Permission denied
Failed to copy the HTML report back to local machine!
~~~
Scenario to reproduce the failure: set a default umask in /etc/sudoers:
~~~
Defaults	umask = 0077
~~~
The fix consists in changing the result files' ownership from "root" to
user's back, all while in the single sudo (using two sudo commands
wouldn't be nice since the user may get the password prompt twice,
depending on the sudo's …
=> Fixed oscap-ssh failing to retrieve the result files when executing with --sudo

src/OVAL/probes/public/probe-api.h
These warnings give zero value to the user, because they don't specify
what went wrong. Moreover, the severity of the message depends on the
parameters of the macro. For example, in environemntvariable58 probe the
macro is used in a way that "Entity has no value" is a valid and
expected situation, because if the pid element is set to xsi:nil the PID
should be set to the PID of the calling process.
Resolves: RHBZ#1764139
=> Remove useless warnings

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
Fedora 32 was branched from Rawhide on 2020-02-12 and Rawhide
became future Fedora 33.
=> Add Fedora 33 CPEs

docs/developer/developer.adoc, src/OVAL/probes/independent/textfilecontent54_probe.c, src/OVAL/probes/independent/textfilecontent_probe.c, src/common/util.c, src/common/util.h, tests/probes/textfilecontent54/30-ospp-v42.rules, tests/probes/textfilecontent54/CMakeLists.txt, tests/probes/textfilecontent54/test_recursion_limit.oval.xml, tests/probes/textfilecontent54/test_recursion_limit.sh
When a complex unanchored regular expression is provided in OVAL textfilecontent54_object, the pcre_exec might recurse internally many times which can cause a segmenatation fault. A reproducer of this situation is provided as a test. We will prevent the segmentation fault by setting a maximal recursion limit.
Since a similar code existed in 2 probes I decided to unify the code first, and then apply the limit only at 1 place.
Resolves: RHBZ#1686467
=> Prevent crashes when complicated regexes are executed

src/XCCDF/benchmark.c, src/XCCDF/item.h, src/XCCDF/public/xccdf_session.h, src/XCCDF/xccdf_session.c, tests/API/XCCDF/tailoring/all.sh, utils/oscap-xccdf.c, utils/oscap.8
If we use a tailoring file we can't apply XSLT directly to source
datastream file or to source XCCDF file, because we need to
resolve tailoring and add the custom profile.
The way that I propose is to load the XCCDF session first, similar
way as we do in `xccdf generate fix module`. That will resolve
resolve the tailoring automatically. Then export XCCDF benchmark
into DOM and apply XSLT on the generated tree in-memory.
The problem is that the current design doesn't add the tailoring
profiles to xccdf_benchmark profiles, but there is a separate hash
table. It would require more refactoring.
I have discovered that --hide-profile-info option doesn't do anything
because the functionality was removed 6 years ago, so I changed
documentation for it.
Resolves: RHBZ#1743835
=> Generate HTML guide using tailoring file

schemas/sds/1.3/scap-source-data-stream_1.3.xsd
This PR changes how oscap validates 1.3 datastreams - now it will use the `5.11.3` development OVAL schemas further expanded by us to include the `yamlfilecontent` family.
Related to: https://github.com/OpenSCAP/openscap/pull/1482
=> Use the latest 5.11.3 OVAL when validating the 1.3 datastreams

utils/oscap-xccdf.c, utils/oscap.8
This introduces the `urn:xccdf:fix:script:kubernetes` fix type which
will get added to the `system` entry in the `xccdf:fix` element. Similar
to the `urn:xccdf:fix:script:ignition`, this is initially meant for
OpenShift, however, the intent is to make these fixes more general and
applicable to other Kubernetes distributions.
This is a superset of the `urn:xccdf:fix:script:ignition` type, so it'll
eventually replace it.
=> xccdf: Introduce 'urn:xccdf:fix:script:kubernetes' fix type

CMakeLists.txt
Fixes #1516  - if PCRE is installed in non-default directory, the directory needs to be included
=> fix CMakeList.txt - include PCRE_INCLUDE_DIRS

xsl/xccdf-guide-impl.xsl, xsl/xccdf-report-impl.xsl, xsl/xccdf-share.xsl
This patch will ensure that rule severity changed by refine-rule element
will be correctly displayed in HTML guide and HTML report.  Before this
patch, the refine-rule element was ignored and severity defined in the
Rule element has been shown instead.
This patch still doesn't support refine-rule from parent profile if the
given profile extends another profile. But, the whole XSLT doesn't
support extended profiles and requires fully resolved benchmark as an
input. Therefore I think it doesn't make sense to implement it only
for this particular value.
Fixes: #1512
=> Use rule severity refinement

Dockerfiles/mitre_tests
update docker image to fedora 31 as current 29 is EOL as of 30th November 2019
=> update docker image to fedora 31

src/DS/rds.c, src/OVAL/probes/independent/system_info_probe.c, src/XCCDF/result.c, src/common/util.c, src/common/util.h, xsl/xccdf-report-impl.xsl
OSCAP_EVALUATION_TARGET is now stored in `target-facts` as `xccdf:fact:identifier` and `target` is always a hostname (with offline support).
ARF result is always valid.
Network entities are not collected in offline mode.
Identity entities are not collected in offline mode.
=> Fixes for Evaluation Characteristics

src/OVAL/probes/independent/environmentvariable58_probe.c, tests/probes/environmentvariable58/test_probes_environmentvariable58_offline_mode.sh
Force the scanner to account only for variables passed via
OSCAP_CONTAINER_VARIABLES (only if it is not empty).
=> probes/environmentvariable58: Fix regression in container variables

CMakeLists.txt
This is in reference to #1073 in order to support cross-compiling OpenSCAP. See the build output attached for the issue. 
I also tested this change to ensure appveyor build was not affected as well.
[cross-compile-build-log.txt](https://github.com/OpenSCAP/openscap/files/4782392/cross-compile-build-log.txt)
=> Fixing pthreads config missing when X-compiling

src/OVAL/probes/unix/xinetd_probe.c
It is recommended that applications use  readdir(3)  instead  of  read‐
dir_r().   Furthermore,  since  version  2.24,  glibc  deprecates read‐
dir_r(). The reasons are as follows:
*  On systems where NAME_MAX is undefined, calling readdir_r()  may  be
unsafe  because  the  interface does not allow the caller to specify
the length of the buffer used for the returned directory entry.
*  On some systems, readdir_r() can't read directory entries with  very
long  names.   When the glibc implementation encounters such a name,
readdir_r() fails with the error ENAMETOOLONG after the final direc‐
tory  entry  has  been read.  On some other systems, readdir_r() may
return a success status, but the returned d_name field  may  not  be
null terminated or may be truncated.
*  In  the  current POSIX.1 …
=> probes/xinetd: Replace deprecated readdir_r call with readdir

docs/developer/developer.adoc, src/OVAL/probes/oval_fts.c, tests/probes/file/CMakeLists.txt, tests/probes/file/test_probes_file_multiple_file_paths.sh, tests/probes/file/test_probes_file_multiple_file_paths.xml
There is a non-optimal behavior of file probe. It happens when file path
is specified using a variable with 2 values with `operation="equals"`
and `var_check="all"`. The probe recurses into a file system tree even
if it's obvious that it won't find any match. If one of values is a big
tree (for example `/`) it eventually runs out of memory and crashes. The
OVAL doesn't make sense because it's impossible that a single file would
have 2 different paths. But despite that it's a valid OVAL document.
We can fix this in oval_fts module. If the path is specified with operation "equals" we know that once we compared the given path with the OVAL object we don't have to continue examining the file system hierachy and we can decide right away.
This PR also adds a test.
Fixes: RHBZ#1686370
=> Prevent unwanted recursion in file probe

xsl/xccdf-branding.xsl, xsl/xccdf-guide-impl.xsl, xsl/xccdf-guide.xsl, xsl/xccdf-references.xsl, xsl/xccdf-report-impl.xsl, xsl/xccdf-report-oval-details.xsl, xsl/xccdf-report.xsl, xsl/xccdf-share.xsl
The HTML reports and guides were invalid. The main problem was the confusing namespace. The HTML output is HTML 5 according to doctype and according to its contents but the elements used the XHTML namespace. But, the HTML reports and guides aren't parseable as XML.
Also, there were some unpaired elements and elements that aren't allowed in the given context.
I managed to reduce the errors reported by W3C validator significantly. But, there remains error 
`CSS: Deprecated media feature max-device-width.`.
For more details, please see the commit message of each commit.
Fixes: #1540
=> Make the HTML output valid

src/common/oscap_acquire.c
When fetching remote resources, some servers/CDNs may be able to serve us
compressed http response even in cases when the original file is not compressed
XML. libcurl is able to process encoded html for us with no added maintenance
costs.
Attached please find a CURL log of fetching plain XML file from Red Hat CDN:
```
Downloading: https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml
...
*   Trying 104.90.105.254:443...
* Connected to www.redhat.com (104.90.105.254) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
CApath: none
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: …
```
=> Make a use of HTTP header content-encoding: gzip if available

tests/API/XCCDF/applicability/all.sh, tests/API/XCCDF/applicability/test_platform_inheritance.cpe.xml, tests/API/XCCDF/applicability/test_platform_inheritance.oval.xml, tests/API/XCCDF/applicability/test_platform_inheritance.sh, tests/API/XCCDF/applicability/test_platform_inheritance.xccdf.xml
This test aims to check scanner behavior of inherited `xccdf:platform` elements.
=> Add tests for xccdf:platform inheritance

src/common/oscap_acquire.c
Further improvement of #1557.
Adds a request for compressed Transfer Encoding in the outgoing
HTTP request. If the server supports this and so desires, it can
respond with the HTTP response sent using a compressed
Transfer-Encoding that will be automatically uncompressed by
libcurl on reception.
The CURLOPT_DEBUGFUNCTION callback is used for printing headers and
connection information on VERBOSE level (dD).
=> Add CURLOPT_TRANSFER_ENCODING, enable CURLOPT_VERBOSE with CURLOPT_DEBUGFUNCTION

tests/probes/password/test_probes_password.xml.sh
The `_apt:x:977:972:APT account for owning persistent & cache data:/var/lib/apt:/sbin/nologin`
entry in the /etc/passwd file generates an error:
```
145: Entity: line 863: parser error : xmlParseEntityRef: no name
145:       <gcos>APT account for owning persistent & cache data</gcos>
```
=> Fix test for password probe

utils/oscap-podman
In some cases there are errors printed by `oscap-podman` script, it
reports about failure to remove certain paths related to a container
that is spawned by it. This seems as a race condition in `oscap-podman`
where the `podman-rm` is called right after the `podman-umount` - this
might cause that system is not fully finished with unmounting and we
request it to remove the container without waiting for the unmount of
its filesystem. This commit removes `podman-umount` command and adds
`-f` option to `podman-rm` which should take care about both, unmounting
and removing of the temporary container.
This issue is hard to reproduce (it mostly occurs on slower machines) and TBH I am not 100% sure if this PR fixes it in all cases.
Example of stderr output:
```
time="2020-05-19T08:10:25-04:00" …
```
=> utils/oscap-podman: force umount and removal of temporary container

src/OVAL/probes/unix/linux/rpmverifyfile_probe.c
This aims to refactor rpmverifyfile probe to reduce complexity and fix some memory leaks.
I admit this is harder to review. It should be easier to review if you check each commit separately and read commit messages of every commit. Also, check the newly introduced functions.
The memory leaks can be checked eg. by running `build/run valgrind --leak-check=full build/utils/oscap oval eval tests/probes/rpm/rpmverifyfile/test_probes_rpmverifyfile.xml`
The biggest leak that was addressed is:
```
==495238==    at 0x483A809: malloc (vg_replace_malloc.c:307)           
==495238==    by 0x51F1386: realpath@@GLIBC_2.3 (in /usr/lib64/libc-2.31.so)
==495238==    by 0x489F8CA: oscap_realpath (util.c:251)                                        
==495238==    by 0x495E6EF: rpmverify_collect …
```
=> Refactoring rpmverifyfile probe and fix memory leaks

src/OVAL/probes/unix/linux/rpminfo_probe.c
When `rpmdbNextIterator()` in `rpminfo_probe` returns NULL due to a potentially corrupt rpm database, `(*rep) + i` will not be correctly initialized, and could cause segmentation fault.  When this happens, its back trace is as below:
```
(gdb) bt
#0  0x00007fe079cc0d07 in __strlen_avx2 () from target:/lib64/libc.so.6
#1  0x00007fe079bb560f in vfprintf () from target:/lib64/libc.so.6
#2  0x00007fe079bdceb4 in vsnprintf () from target:/lib64/libc.so.6
#3  0x00007fe07c173a21 in SEXP_string_newf_rv () from target:
#4  0x00007fe07c17288b in SEXP_string_newf () from target:
#5  0x00007fe07c18460a in rpminfo_probe_main () from target:
#6  0x00007fe07c16a4b4 in probe_worker () from target:
#7  0x00007fe07c169e80 in probe_worker_runfn () from target:
#8  0x00007fe07b1e32de in start_thread () from …
```
=> Initialize rpminfo_rep to avoid crash

src/OVAL/probes/fsdev.c
The previous way was unreliable because some remote file systems were
detected as local. For example, the SMB mounts that used paths with
backslashes were not recognized as remote file systems.  The `getmntent`
function returns a file system type, so we can use it for detection of
remote file systems.
The new solution is inspired by systemd, function `fstype_is_network`:
https://github.com/systemd/systemd/blob/21fd6bc263f49b57867d90d2e1f9f255e5509134/src/basic/mountpoint-util.c#L290
It also handles FUSE file systems. Also, we are cancelling the TODO idea
of providing the data at the build time and removing the dead code (if
0).
GPFS is also treated as remote system because we have multiple reports that GPFS shouldn't be scanned.
Resolves: RHBZ#1869195, RHBZ#1870087, RHBZ#1840575, …
=> Change local and remote file system detection

configure.ac, src/common/oscap_acquire.c, tests/Makefile.am, tests/curl/Makefile.am, tests/curl/ds.xml, tests/curl/test_curl_encoding.sh
This is port of #1557, #1561 and #1564 to the maint-1.2 branch.
=> Enable compressed feeds, and ability to debug them for 1.2

src/OVAL/probes/unix/fileextendedattribute_probe.c, src/OVAL/probes/unix/interface_probe.c, src/OVAL/probes/unix/sysctl_probe.c, src/common/memusage.c, tests/probes/system_info/test_probes_system_info.sh, tests/probes/system_info/test_probes_system_info_offline_mode.sh
This PR primarily consists of whitespace fixes along with two functional changes:
1. In the extended attribute probe, FreeBSD's `file_cb()` has an erroneous `return` statement which is now removed.
2. For the system_info tests, check for `/etc/os-release` so that the tests are skipped on systems that do not have the file. This is done to avoid test failure on older versions of FreeBSD (12.1-RELEASE and earlier).
This has been tested on:
Fedora 32
FreeBSD 12.1-RELEASE
FreeBSD 12.1-STABLE
FreeBSD 13-CURRENT
Ubuntu 18.04
=> FreeBSD support fixes

src/CPE/cpedict.c
When cpe_dict_detect_version_priv fails and returns NULL it
frees the reader and then the reader is freed again in the caller
function oscap_source_get_schema_version (oscap_source.c:405).
=> Remove superfluous free

src/OVAL/oval_probe_ext.c, src/OVAL/oval_probe_handler.c, src/OVAL/probes/SEAP/generic/bitmap.c, src/OVAL/probes/SEAP/generic/spb.c, src/OVAL/probes/SEAP/generic/strbuf.c, src/OVAL/probes/SEAP/seap-message.c, src/OVAL/probes/SEAP/seap-packet.c, src/OVAL/probes/SEAP/sexp-manip.c, src/OVAL/probes/fsdev.c, src/OVAL/probes/independent/environmentvariable58_probe.c, src/OVAL/probes/independent/textfilecontent54_probe.c, src/OVAL/probes/probe/icache.c, src/OVAL/probes/probe/ncache.c, src/OVAL/probes/probe/probe_main.c, src/OVAL/probes/unix/fileextendedattribute_probe.c, src/OVAL/probes/unix/linux/partition_probe.c, src/OVAL/probes/unix/linux/rpminfo_probe.c, src/OVAL/probes/unix/process58_probe.c, src/OVAL/probes/unix/xinetd_probe.c, src/SCE/sce_engine.c, src/XCCDF/xccdf_session.c, src/XCCDF_POLICY/xccdf_policy_remediate.c, src/common/oscap_buffer.c
And clean up the old handle wherever deems necessary.
While I tried to mitigate improper `realloc` handling this patch won't bring much to memory management of the project. The only real benefit: it will prevent some memory leaks under memory pressure.
The whole approach of the project is to crash and burn when memory could not be allocated. It seems to be stemming from the Linux idea of overcommitting allocator, where checks of the result of the `malloc` are futile and the whole end-game of memory hungry application is OOM onslaught. 
Windows (for example) does not have this behaviour, and even Linux's allocator could be configured to behave differently (`ulimit`, `cgroups` you name it). But for proper memory handling in these scenarios one would have to fix *all* memory allocations, and …
=> Fix realloc calls to account for a possible NULL result

.travis.yml
Hi,
I had added ppc64le(Linux on Power) support on travis-ci in the branch and looks like its been successfully added. I believe it is ready for the final review and merge. The travis ci build logs can be verified from the link below.
https://travis-ci.com/github/ujjwalsh/openscap/builds/182709409
Please have a look.
Regards,
ujjwal
=> Added support on Linux on power

src/OVAL/probes/fsdev.c
`__fsdev_init()` for FreeBSD does not declare the variable `e`, which
generates a compiler error. Fix this by declaring `e` before using it.
Fixes: bc36258ac ("Merge pull request #1584 from evgenyz/fix-reallocs")
=> Fix build failure on FreeBSD

src/OVAL/probes/probe-api.c
We should free the replaced list element, returned from the `..._replace` function, not the soft reference to it.
Fixes #1588.
=> Fix memory leak

src/DS/rds.c, src/DS/rds_priv.h, src/DS/sds.c, src/DS/sds_priv.h, src/XCCDF/public/xccdf_session.h, src/XCCDF/xccdf_session.c, src/source/oscap_source.c, src/source/oscap_source_priv.h, utils/oscap-xccdf.c
This is an attempt to solve the problem that when evaluating a datastream and generating ARF results the document tree of input source datastream is loaded in memory multiple times due to generating ARF results.
ARF results contain a copy of the source datastream document. This is done by using [xmlDOMWrapCloneNode](http://www.xmlsoft.org/html/libxml-tree.html#xmlDOMWrapCloneNode). I tried to replace its usage by its sibling [xmlDOMWrapAdoptNode](http://www.xmlsoft.org/html/libxml-tree.html#xmlDOMWrapAdoptNode). These functions aren't well documented, so it's only a guess that it could help.
In order to do the change, I had to refactor the logic so that the source datastream isn't reused within the XCCDF session after the ARF generation finishes as I was afraid of double frees.
When …
=> Prevent cloning source datastream in memory when generating ARF results

src/DS/rds.c, src/DS/sds.c, src/OVAL/probes/independent/yamlfilecontent_probe.c, src/OVAL/probes/unix/linux/partition_probe.c, src/OVAL/probes/unix/linux/systemdunitproperty_probe.c, src/OVAL/probes/unix/sysctl_probe.c, src/XCCDF/xccdf_session.c
Fixes some of the leaks (the easy ones) discovered by running valgrind inside upstream test suite:
https://jenkins.complianceascode.io/job/openscap-maint-1.3-valgrind-test/7/artifact/build/tests/valgrind_test.log
For more information, please read commit messages of each commit.
=> Memory leaks wave

src/XCCDF/xccdf_session.c, tests/API/SEAP/test_api_seap_concurency.c
Ensure that in `xccdf_session_extract_arf_source()` the variable `tailoring_doc_timestamp` is always initialized before attempting to free it. Previously, the function could jump to the `cleanup` label before `tailoring_doc_timestamp` was initialized and would then attempt to free the it. Fix this by initializing the variable before the function can go to `cleanup`.
Also check if `malloc()` succeeds when later allocating memory for `tailoring_doc_timestamp`.
Glibc's `pthread_t` is an `unsigned long int` [1], and FreeBSD's libc defines it as a pointer to a `struct pthread`[2].
In both cases we do not want to potentially truncate this value by casting it to an `unsigned int`. Fix this by casting the return value of `pthread_self()` to a `uintptr_t`.
[1] …
=> Fix some compiler warnings

docs/manual/manual.adoc
This PR replaces an outdated page anchor link in the user manual with a link to the developer documentation for compilation instructions.
Fixes #1599
=> Fix link to compilation instructions

tests/probes/file/test_probes_file_multiple_file_paths.sh
Use `truss(1)` rather than `strace(1)` on FreeBSD to trace system calls. This change allows FreeBSD systems to successfully run this test case. `truss(1)` is included in FreeBSD's base system, whereas `strace(1)` is Linux-specific.
=> Make test_probes_file_multiple_file_paths work on FreeBSD.

.github/workflows/main.yml
It seems that we don't need to remove Python2 anymore.
Fixes the GitHub actions Error message on Mac OS X.
Error: No installed keg or cask with the name "python@2"
Error: Process completed with exit code 1.
=> Remove removing Python 2

tests/memory/cgroup_test.sh
Cgroup will be created and deleted by the Jenkins configutaion job
to avoid need to run the whole test under sudo.
=> Remove cgroup setup

.travis.yml
There is not much sense in running CI on this arch as there are
no code paths specific to it, it only prolongs PR gating procedure.
=> Remove ppc64le from Travis CI

src/OVAL/probes/fsdev.c, src/OVAL/probes/independent/yamlfilecontent_probe.c, src/OVAL/probes/unix/fileextendedattribute_probe.c, src/OVAL/probes/unix/linux/partition_probe.c, src/OVAL/probes/unix/xinetd_probe.c, src/XCCDF/xccdf_session.c, utils/oscap-tool.c, utils/oscap-xccdf.c
Fixes for:
```
openscap-1.3.4/src/OVAL/probes/independent/yamlfilecontent_probe.c:317: uninit_use: Using uninitialized value "event_type". 
openscap-1.3.4/src/XCCDF/xccdf_session.c:291: overwrite_var: Overwriting "tm_mtime" in "tm_mtime = localtime_r(&file_stat.st_mtim.tv_sec, tm_mtime)" leaks the storage that "tm_mtime" points to. 
openscap-1.3.4/src/OVAL/probes/unix/xinetd_probe.c:570: dereference: Dereferencing "xiconf->cfile", which is known to be "NULL". 
openscap-1.3.4/utils/oscap-tool.c:319: dereference: Dereferencing "eargv", which is known to be "NULL". 
openscap-1.3.4/utils/oscap-xccdf.c:613: dead_error_line: Execution cannot reach the expression "0f" inside this statement: "syslog(priority, "Evaluatio...". 
openscap-1.3.4/src/OVAL/probes/unix/fileextendedattribute_probe.c:306: …
```
=> Covscan fixes

src/common/oscap_acquire.c
Addressing multiple Coverity defects similar to this one:
Defect type: CHECKED_RETURN
check_return: Calling "curl_easy_setopt(curl, _curl_opt, _curl_trace)"
without checking return value. This library function may fail and return
an error code.
=> Fix Coverity warnings

src/OVAL/probes/independent/yamlfilecontent_probe.c, tests/probes/yamlfilecontent/openshift-logging.yaml, tests/probes/yamlfilecontent/test_probes_yamlfilecontent_array.sh, tests/probes/yamlfilecontent/test_probes_yamlfilecontent_array.xml, tests/probes/yamlfilecontent/test_probes_yamlfilecontent_key.sh, tests/probes/yamlfilecontent/test_probes_yamlfilecontent_key.xml
`$.foo[:].bar[:]`, `$.foo[:][:]` and alike.
=> Fix field names for cases where key selection section is followed by a set section (probes/yamfilecontent)

swig/perl/CMakeLists.txt
After commit 69b9b1519 ("Changing hardcoded libperl path for FindPerlLibs method"), OpenSCAP no longer builds on FreeBSD.
Running `cmake ../` results in the following errors:
```
CMake Error at swig/perl/CMakeLists.txt:22 (install):
install TARGETS given no LIBRARY DESTINATION for module target
"openscap_pm".
CMake Error at swig/perl/CMakeLists.txt:24 (install):
install PROGRAMS given no DESTINATION!
```
This is due to cmake on FreeBSD not defining `PERL_VENDORLIB` and `PERL_VENDORARCH`. To workaround this issue, I have added FreeBSD to use the same case as macOS, which falls back to the previous hard-coded paths. After this change OpenSCAP successfully builds on FreeBSD and passes all known-working tests.
=> Fix the build for FreeBSD.

src/OVAL/probes/SEAP/_sexp-value.h, src/OVAL/probes/SEAP/sexp-value.c
We can't assume that size of a structure is a sum of sizes of its
members because padding and alignment can be involved. In fact,
we need to allocate more bytes for the structure than the
sum of sizes of its members.
The wrong assumption caused invalid writes and invalid reads
which can be discovered by valgrind. Moreover, when run with
MALLOC_CHECK_ environment variable set to non-zero value, the
program aborted.
The memory issue happened only when NDEBUG is defined, eg. when cmake
-DCMAKE_BUILD_TYPE=RelWithDebInfo or Release, it doesn't happen if cmake
-DCMAKE_BUILD_TYPE=Debug which we usually use in Jenkins CI. This is
most likely because in debug mode the struct SEXP contains 2 additional
members which are the magic canaries and therefore is bigger.
This commit wants to fix the …
=> Fix memory allocation

src/OVAL/probes/probe/worker.c
=> Added the missing header for chroot() on macOS

tests/suppressions.supp
When we make the Jenkins job passing it will be easier to detect
freshly introduced memory problems. Until all memory problems
are fixed we risk that new problems will be ignored.
=> Suppress most of the memory errors

tests/API/probes/fake_mtab
Test for commit 1541487 - add GPFS into fake_mtab (which is
utilized by the `test_fsdev_is_local_fs`) to make sure that it
is not detected as a local filesystem.
For more details also see
https://www.ibm.com/developerworks/systems/library/es-gpfs/index.html
=> Extend test_fsdev_is_local_fs to verify GPFS

src/XCCDF/rule.c, tests/API/XCCDF/parser/xccdf11-results.xml, tests/API/XCCDF/parser/xccdf11.xml, tests/API/XCCDF/parser/xccdf12.xml, tests/DS/test_sds_eval.sh
Adds severity and role attributes to rule-result elements in XCCDF
results. These attributes are optional in XCCDF 1.2 specification but if
the XCCDF is used in ARF the attributes are mandatory.  See SCAP 1.3
specification Section 4.5 item 10. We didn't create these attributes if
the input XCCDF didn't contain them. We can fix it by assuming the
default values. According to XCCDF 1.2 specification, the default value
of role element is "full" and the default value of severity element is
"unknown". The presence of role, weight and severity attributes is
checked by SCAPVAL. We had weight attribute but missing role and
severity caused error RES-392.
Fixes: #1630
=> Add severity and role attributes

tests/suppressions.supp
Extends suppression file to make the Jenkins job
`openscap-maint-1.3-valgrind-test` green. It's a follow up on
https://github.com/OpenSCAP/openscap/pull/1615
=> Hide even more problems

src/OVAL/probes/probe/entcmp.c, src/OVAL/results/oval_cmp.c, src/OVAL/results/oval_cmp_evr_string.c, src/OVAL/results/oval_cmp_evr_string_impl.h
This commit move away from using rpm version comparison algorithm for
debian based distros and at the same time fixes false positives that
happen when the revision of a package contains a '~'.
I've based it on maint-1.3, but this could certainly go to master and even maint-1.2.
=> Add dpkg version comparison algorithm

src/DS/ds_sds_session.c, src/DS/ds_sds_session_priv.h, src/DS/public/ds_sds_session.h, src/DS/sds.c, src/XCCDF/item.c, src/XCCDF/xccdf_session.c, tests/DS/test_ds_misc.sh
Make the href attribute an URI according to SCAP specification Section
4.5. This should fix SCAPVAL error RES-253-2 which occured when
validating ARFs by SCAPVAL. See #1629 for the problem description.
Also, it fixes a problem that xccdf_benchmark_item_clone didn't create
the clusters_dict hash table.
The existing tests are extended to test this property, the
function test_sds_external_xccdf has been split into 2 functions.
Fixes: #1629
=> Fix TestResult/benchmark/@href attribute

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
With the CentOS stream effort, the centos-relase RPM package is no
longer available. While CentOS 8.2.2004 features centos-release RPM
package, the CentOS 8.3.2011 features centos-linux-release RPM and
CentOS Stream features centos-stream-release RPM package. We have
decided to parse /etc/os-release file instead which is often present and
doesn't require librpm to be present.
Fixes: #1661
=> Fix CentOS 8 CPE

src/OVAL/results/oval_cmp_evr_string.c
The function verrevcmp can return any positive or negative number as a comparison result, not just 1 or -1.
@dodys LMK if there's an issue.
=> Fix oval_debian_evr_string_cmp

src/XCCDF/result.c, src/XCCDF/xccdf_session.c, tests/API/XCCDF/unittests/test_single_rule.xccdf.xml, tests/API/XCCDF/unittests/test_single_rule_stigw.sh
This PR aims to fix 2 segfaults in the code creating the XML output for DISA STIG Viewer.
The first segmentation fault is a new problem. It has been caused by a mistake in 9b40767967e533bdb340ca4c91f2fd1192694820. This segmentation fault occurs any time an user uses `--stig-viewer`. For example: `oscap xccdf eval --profile ospp --stig-viewer /tmp/xxx /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml`. 
Unfortunately, the problem hasn't been discovered by CI, because the test https://github.com/OpenSCAP/openscap/blob/maint-1.3/tests/API/XCCDF/unittests/test_single_rule_stigw.sh is wrong. https://github.com/OpenSCAP/openscap/blob/1ccdd3bb31b2f1d4da5c7e9b6018597454e879cd/tests/API/XCCDF/unittests/test_single_rule_stigw.sh#L22
This condition ignores any fail in the `oscap` command. A similar …
=> Fix multiple segfaults and broken test in --stig-viewer feature

src/OVAL/results/oval_cmp_evr_string.c
This pull request fixes some new warnings found by building with LLVM/clang on FreeBSD. I do not believe these changes fix real bugs, however I think it is good to silence compiler warnings whenever possible as it increases the visibility of future warnings that could be actual problems.
**Changes:**
1. Fix a missing prototype warning by making ``dpkg_version_compare()`` static. The function is not called outside of its file as its only caller is ``oval_debian_evr_string_cmp()``. 
2. Silence an un-handled enumeration value warning in ``oval_debian_evr_string_cmp()`` by adding a default case in the switch statement, and explicitly calling ``oscap_seterr()`` there. Previously the function would set an error for unhandled values immediately after leaving the switch statement, so the behavior …
=> Silence some compiler warnings found with LLVM/clang

tests/probes/file/CMakeLists.txt, tests/probes/file/test_probes_file_behaviour.sh, tests/probes/file/test_probes_file_behaviour.xml
This test case is based on `RHEL-datastream.xml` from NIST's
SCAP1.3ValidationTestContent_1-3/combinedDataStreams_1-3 test suite.
Test is failing right now, but according to the test suite it should not.
=> Add behaviour test for unix/file probe

src/OVAL/oval_probe_ext.c
The code was updated in accordance with how empty messages (with sexp == NULL) are encoded in:
https://github.com/OpenSCAP/openscap/blob/d05a0e8f382f758820c7623deabdd0ea2dd28b03/src/OVAL/probes/SEAP/seap-packet.c#L256
Fixes annoying warning `Obtrusive data from probe!`.
Fixes: #1632.
=> Fix how oval_probe_ext_eval checks absence of the response from the probe

docs/manual/manual.adoc, utils/oscap.8
The documentation of --stig-viewer option wasn't sufficient and
confused multiple users, for example RHBZ#1896957.
This change tries to describe the use case in which --stig-viewer
option is used in a greater detail.
The commit removes the information about --stig-viewer not working
with DISA STIG Viewer newer than 2.6 because it works fine with
version 2.11. The source of this information is unclear, probably
a confusion due to difference between using DISA benchmark and SSG.
Fixes: RHBZ#1918759
=> Improve documentation about --stig-viewer option

src/DS/ds_sds_session.c
It is not a problem, but - just in case there would be some strange data stream - we are moving it to the INFO level.
Fixes #1642 .
=> DS: Remove warning for repeating component sources

docs/manual/manual.adoc
This commit wants to improve OpenSCAP user manual, make it
up-to-date and more understandable for the readers.
- update for SCAP 1.3
- fix broken links
- improve document structure
- remove duplicate information
- remove outdated information
- document oscap-podman
- promote using data streams over separate XCCDF and OVAL files
- fix adoc syntax
- fix style
- fix some grammar
- use more real or currently used examples
- fixed misleading information about oscap xccdf generate fix
- added generating Ansible Playbooks
Reviewers, please, I know it's tempting to check just for typos and grammar. But try to change your mind and focus on the content instead. Check on the documented facts. It's really important to avoid misleading information and make sure that there aren't wrong or not working …
=> Refresh OpenSCAP user manual

src/DS/sds.c
Allow to clamp mtime to `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
Without this patch, openSUSE's `scap-security-guide` package had variations in `/usr/share/xml/scap/ssg/content/ssg-opensuse-ds-1.2.xml` for every build:
```
<ds:component id="scap_org.open-scap_comp_ssg-opensuse-oval.xml" timestamp="2
021-02-23T09:58:15">
```
as it was created by `oscap ds sds-compose ...`
=> Allow to clamp mtime to SOURCE_DATE_EPOCH

tests/DS/test_ds_misc.sh
This test checks if the SOURCE_DATE_EPOCH is used in the
oscap ds sds-compose command as a datastream component timestamp.
Related to https://github.com/OpenSCAP/openscap/pull/1699/
=> Add a simple test for SOURCE_DATE_EPOCH

tests/test_common.sh.in
Due to the change in `getcap` (or, to be precise, in `cap_to_text`) response format the check is not valid anymore.
=> tests: Fix chrootable binary capabilities check

tests/probes/sysctl/test_sysctl_probe_all.sh
This problem manifests in the Travis CI environment: https://travis-ci.org/github/OpenSCAP/openscap/jobs/763932418.
`E: oscap:     An error ocured when reading from "/proc/sys/kernel/spl/hostid" (fp=0xaaaaea9d6cf0): l=0, 14, Bad address`.
=> Ignore "Bad address" errors from the sysctl probe

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
That CPE can already be encountered in Fedora CI. Although we aim to get rid of the CPE dictionary, we don't have the new major version, and Fedora 35 already technically exists. Therefore, let's kick the ball one step further.
=> Add the Fedora 35 CPE

src/OVAL/probes/unix/linux/selinuxsecuritycontext_probe.c, src/OVAL/probes/unix/process58_probe.c
It's defined in selinux.h as a char *.
Addressing:
/home/jcerny/work/git/openscap/src/OVAL/probes/unix/process58_probe.c:249:2: warning: ‘security_context_t’ is deprecated [-Wdeprecated-declarations]
249 |  security_context_t pid_context;
|  ^~~~~~~~~~~~~~~~~~
/home/jcerny/work/git/openscap/src/OVAL/probes/unix/linux/selinuxsecuritycontext_probe.c:170:2: warning: ‘security_context_t’ is deprecated [-Wdeprecated-declarations]
170 |  security_context_t pid_context;
|  ^~~~~~~~~~~~~~~~~~
/home/jcerny/work/git/openscap/src/OVAL/probes/unix/linux/selinuxsecuritycontext_probe.c:239:2: warning: ‘security_context_t’ is deprecated [-Wdeprecated-declarations]
239 |  security_context_t file_context;
|  ^~~~~~~~~~~~~~~~~~
=> Do not use deprecated type security_context_t

tests/curl/test_curl_encoding.sh, tests/test_common.sh.in
- Introduce `die` helper functions.
- Report what exactly could have gone wrong if the test went wrong.
Background: This test fails on the Fedora 34 CI, and it's difficult to tell why.
=> Improve the curl test

schemas/sds/1.3/source-data-stream-1.3.sch, schemas/sds/1.3/source-data-stream-1.3.sch.original, schemas/sds/1.3/source-data-stream-1.3.xsl, schemas/xccdf/1.2/xccdf_1.2-schematron.xsl, src/common/oscapxml.c, src/source/oscap_source.c, src/source/schematron.c, src/source/schematron_priv.h, tests/DS/CMakeLists.txt, tests/DS/schematron/CMakeLists.txt, tests/DS/schematron/schematron.sh, tests/DS/schematron/simple_ds.xml
This PR attempts to convert SCAP 1.3 source data stream XML schematron to use XPath 1.0 expressions. The original schematron contains XPath 2.0 but libxml can't process them. So this PR tries to workaround the lack of support for it.
We probably won't be able to convert all of the assertions to XPath 1.0, but let's try at least something.
The original schematron is located in `schemas/sds/1.3/source-data-stream-1.3.sch.original`.
The rules are added step-by step into `schemas/sds/1.3/source-data-stream-1.3.sch`.
~At this moment, please generate the XSLT file yourself! I won't regenerate it and commit the generated code after each change in the schematron file. When the PR will be ready for review we will of course generate the XSLT and commit it.~
=> Add SCAP 1.3 source data stream schematron

schemas/oval/5.11.3/independent-definitions-schema.xsd, schemas/oval/5.11.3/independent-system-characteristics-schema.xsd, src/OVAL/probes/independent/yamlfilecontent_probe.c, tests/probes/yamlfilecontent/CMakeLists.txt, tests/probes/yamlfilecontent/test_probes_yamlfilecontent_content.sh, tests/probes/yamlfilecontent/test_probes_yamlfilecontent_content.xml
The `<ind-def:content>` entity is used to represent a YAML document embedded into the data stream or captured in a variable. These entities, `<content>`, `<file>` + `<path>` and `<filepath>` are mutually exclusive.
=> OVAL/yamlfilecontent: Add <content> entity support

docs/manual/manual.adoc, src/OVAL/probes/fsdev.c, tests/API/probes/fake_mtab, tests/API/probes/test_fsdev_is_local_fs.c
More recently, we've come to use the -l switch in the df command to identify the "local" filesystems. We feel this is probably a better reflection of the intention behind the local attribute value.
The df utility considers 'proc' and 'sysfs' as "dummy" and does not produce results for them.
=> OVAL/probes: Make 'proc' and 'sysfs' filesystems non-local

src/source/signature.c, tests/DS/signed/all.sh
According to the Quick guide for using consolidated datastream page 24
the test procedure which is used to test the signature validation
capability SCAP.T.900.2 says this: The tested SHALL provide evidence
indicating the digital of the signed content was validated.
=> Add a message that signature is valid

src/source/oscap_source.c
This adds the same error message as in oscap_source_validate.
If the document ins ivalid accrding to schematron and schematron
validation has been requested by the user, an error should be
reported.
=> Add error message

src/XCCDF/profile.c
By default the value of role member of struct xccdf_refine_rule was set
to zero when created which happened usually when parsing a
xccdf:refine-rule element. But the value of 0 doesn't map to the default
value of the role attribute of xccdf:refine-rule element. The default
value of this attribute is "full" according to the XCCDF specification.
As a result when creating XCDF results or ARF results the role attribute
of xccdf:rule-result hasn't been created. That's a problem according to
scapval.
Fixes: #1729
=> Set the default value of role attribute

src/source/schematron.c, tests/DS/schematron/schematron.sh, tests/DS/schematron/simple_ds_xccdf_schematron_error.xml
In the XCCDF 1.2 schematron there are warnings and errors.
Warnings will be displayed but they won't cause the validation
to fail, but errors will render the document invalid.
=> Distinguish between warnings and errors in XCCDF schematron

src/OVAL/probes/oval_fts.c
The recurse_file_system="local" doesn’t work with file_object and
textfilecontent54_object where <filepath> element is used to define the
file path and operation=”equals” is used on filepath.  As of OVAL
specification of FileBehaviors element:
https://oval.mitre.org/language/version5.10/ovaldefinition/documentation/unix-definitions-schema.html#FileBehaviors
"'recurse_file_system' defines the file system limitation of any
searching and applies to all operations as specified on the path or
filepath entity." Notice the words “any searching” and notice the words
“all operations”. We can solve this bug by performing a similar check
as we do in oval_fts_read_recurse_path.
=> Check local filesystems when using 'filepath' element

tests/DS/schematron/schematron.sh, tests/DS/schematron/simple_ds_xccdf_schematron_error.xml
The test introduced by #1732 doesn't pass because the
tests/DS/schematron/simple_ds_xccdf_schematron_error.xml wan't invalid
only according to schematron but also according to XSD. We can fix it by
creating a different problem in the data stream which will pass XSD
validation but fail schematron validation.
=> Fix a test

.travis.yml
Due to lack of proper unit tests in our project it would not
produce useful results.
=> Remove codecov.io

tests/probes/sysctl/test_sysctl_probe_all.sh
The known issue has been reported in
https://bugzilla.redhat.com/show_bug.cgi?id=1642995
This modification is currently applied as a patch applied during setup
phase of Sanity/smoke-test in Fedora CI gating.
https://src.fedoraproject.org/tests/openscap/blob/main/f/Sanity/smoke-test
The patched file got changed recetly so the patch doesn't apply anymore
which causes the Rawhide gating to fail.
We have decided to propose the change to upstream to avoid the need
for modifying the patch in the tests and to prevent similar problems
in the future.
=> Waive the known issue with hugepages on ppc64/ppc64le

utils/oscap.8
The `--enforce-signature` option was not indented properly in man page under `generate guide` and `generate fix`.
=> utils/oscap.8: fix indentation of --enforce-signature option in man page

tests/DS/signed/all.sh
Add more tests for signature validation feature to cover also `generate guide` and `generate fix` XCCDF operations.
=> Add additional tests for signature validation

src/OVAL/probes/independent/yamlfilecontent_probe.c, tests/probes/yamlfilecontent/test_probes_yamlfilecontent_types.sh, tests/probes/yamlfilecontent/test_probes_yamlfilecontent_types.xml, tests/probes/yamlfilecontent/types.yaml
For now null values would be represented as string '(null)' as record's field could not be attributed as nil="true" yet.
=> oval/yamlfilecontent: Add 'null' values handling

CMakeLists.txt
See: https://docs.fedoraproject.org/en-US/packaging-guidelines/#_beware_of_rpath
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1967200
=> Do not set Rpath

src/OVAL/probes/independent/system_info_probe.c
In offline mode when scanning a cointainer based on UBI 9 the
system_info probe failed because the function `_offline_get_hname` which
reads from `/etc/hostname` returns an empty string which causes
`__sysinfo_saneval(hname)` check to return zero which in turn causes the
probe returns an error. We can prevent this situation by replacing the
empty string by `"Unknown"`, which we already do when the `hname` is
`NULL`.
Addressing:
W: oscap: Can't receive message: 125, Operation canceled.
E: oscap: Recv: retry limit (0) reached.
OpenSCAP Error: Probe at sd=32 (system_info) reported an error: Invalid type, value or format [/home/jcerny/work/git/openscap/src/OVAL/oval_probe_ext.c:383]
Unable to receive a message from probe [/home/jcerny/work/git/openscap/src/OVAL/oval_probe_ext.c:572]
Resolves: …
=> Fix UBI 9 scan

xsl/oval-results-report.xsl
rpminspect produces this problem:
```
xml-files:
----------
1) File /usr/share/openscap/xsl/oval-results-report.xsl is a malformed XML file on x86_64
Result: VERIFY
Waiver Authorization: Anyone
Details:
No declaration for element stylesheet
Suggested Remedy: Correct the reported errors in the XML document
```
I assume that it's caused by mixing the DTD and schema - it probably
expects that the DTD will contain a declaration of the root element
as well. The workaround simply expands both entities by substituting
them by their contents.
=> Workaround rpminspect problem

tests/API/XCCDF/unittests/test_profile_selection_by_suffix.sh
The test fails becuse the OVAL content in
`test_remediation_simple.oval.xml` used in rule
`xccdf_moc.elpmaxe.www_rule_1` in
`test_profile_selection_by_suffix.xccdf.xml` expects that a file named
`test_file` exists in the current working directory.
This test doesn't fail when executed as a part of complete test suite
run. I guess that it's because some other test creates the `test_file`
file and doesn't delete it. Unfortunately, I can't find which test
creates it. There are many test cases that use a file `test_file`
and it is also created often by remediation executed in some tests.
=> Fix failing test

Dockerfiles/test_suite
The new Dockerfile might be useful for debugging purposes or just for
running the test suite isolated from a host system. It runs the test suite
exactly the same as in GH action and it can be parametrized to run
for a specific GitHub PR.
=> Add new Dockerfile which can run test suite for PRs

src/OVAL/oval_probe_session.c, src/OVAL/probes/independent/filehash58_probe.c, src/OVAL/probes/independent/filehash_probe.c, src/OVAL/probes/independent/filemd5_probe.c
The function `crapi_init` calls `gcry_check_version` which must be
called before any other function from the Libgcrypt library. That might
be violated when multiple threads executing multiple probes are running.
The mitigation proposed in this PR is to call `crapi_init` only once
when the session is initialized which means before any threads are
spawned.
See also: https://www.gnupg.org/documentation/manuals/gcrypt/Multi_002dThreading.html#Multi_002dThreading
Resolves: RHBZ#1959570
=> Initialize crypto API only once

tests/probes/filehash58/CMakeLists.txt, tests/probes/filehash58/rhbz1959570_segfault.sh, tests/probes/filehash58/rhbz1959570_segfault_reproducer.xml
The bug was a segmentation fault in filehash58 probe which happened
in openscap-1.3.3-6.el8_3.
The bug was fixed by https://github.com/OpenSCAP/openscap/pull/1779
and this patch adds a very small test.
=> Add a regression test for rhbz#1959570

src/OVAL/oval_probe_session.c
This function is void so it shouldn't return anything.
=> Fix return NULL

src/OVAL/probes/unix/password_probe.c, src/XCCDF/result.c, tests/API/XCCDF/default_cpe/test_cpe_applicability.sh, tests/API/XCCDF/unittests/test_report_check_with_empty_selector.sh, tests/API/XCCDF/unittests/test_xccdf_results_arf_asset.sh
This pull request contains both fixes that allow OpenSCAP to be built on FreeBSD (tested on 13.0-RELEASE), as well as some trivial test compatibility fixes. If it is better to split these into two separate pull requests just let me know.
**Compilation fixes:**
1. The changes to the password probe are due to FreeBSD not supporting the same functions as glibc (e.g. `fgetpwent()`). Now FreeBSD uses separate `read_password()` and `_freebsd_process_struct_passwd()` instead. I believe this should also help avoid future breakages in the future.
2. In `XCCDF/result.c` switch to using `getpwuid(getuid())` instead of `cuserid()`. This was done for two reasons, the first is that macOS and FreeBSD do not support this by default, and the second is that glibc recommends not using the function. From the …
=> FreeBSD build and test fixes

docs/manual/manual.adoc, src/OVAL/probes/probe/icache.c, src/OVAL/probes/probe/probe.h, src/OVAL/probes/probe/worker.c, src/common/memusage.c
This patch attempts to mitigate problems caused by a large amount of
collected objects such as rhbz#1932833.
Specifically, these changes are made:
- Lower the threshold so that the amount of used memory is checked when
only 1000 items are collected for the given OVAL object. That's
because 32768 items (the original value) is already a large amount which
occupies a lot of memory during further processing.
- Lower the memory usage ratio limit for the probe to 10 %. We have
found experimentally that giving the probe 15 % or more will cause the
oscap process to be killed when processing the collected data and
generating results.
- In the calling function probe_item_collect, distinguish between return
codes which means different behavior when there is insufficient memory
than when the memory …
=> Lower memory limits and improve their checking

docs/manual/manual.adoc
The footer contains the date of the last build.
Different date can cause this problem of rpmdeplint:
Undeclared file conflicts:
openscap-1.3.5-8.el8.i686 provides /usr/share/doc/openscap/manual/manual.html which is also provided by openscap-1.3.5-8.el8.x86_64
openscap-1.3.5-8.el8.x86_64 provides /usr/share/doc/openscap/manual/manual.html which is also provided by openscap-1.3.5-8.el8.i686
We can avoid it by simply removing the date.
=> Do not put footer to the user manual

src/DS/sds.c, tests/DS/test_ds_use_local_remote_resources.sh
This will explicitely display users that they're using local
files instead of the remote resource.
See https://bugzilla.redhat.com/show_bug.cgi?id=1970529#c6
=> Print warning for local files

src/XCCDF_POLICY/xccdf_policy_remediate.c
This PR fixes some issues found by Coverity scan. 
Addressing:
openscap-1.3.5/src/XCCDF_POLICY/xccdf_policy_remediate.c:115:38: warning[-Wanalyzer-possible-null-argument]: use of possibly-NULL 'current' where non-null expected
=> Fix coverity issues

src/OVAL/probes/probe/worker.c
After some testing we decided that this ratio is more usable in real-world cases.
=> Change default value for OSCAP_PROBE_MEMORY_USAGE_RATIO to 0.33

tests/DS/test_ds_misc.sh
The SOURCE_DATE_EPOCH environment variable is effective only when it's
set to a value that's older than mtime of the processed file.  See the
implementation in ds_sds_compose_add_component_internal in src/DS/sds.c.
However, the file in our test suite has originally been created before
(in 2019) and this mtime can be used when a tarball is produced. To
avoid the test failing, we can modify the mtime using the touch command
just before we run the tests.
=> Prevent fails of test_ds_misc.sh

src/common/elements.c, src/common/util.c, src/common/util.h, src/source/xslt.c, tests/API/XCCDF/unittests/CMakeLists.txt, tests/API/XCCDF/unittests/test_oscap_common.c
The sysctl setting `fs.protected_regular` doesn't allow `O_CREAT` open
on regular files that we don't own in world writable sticky directories
(think `/tmp`). This causes permission denied error when writing HTML
report to a temporary files created by the `mktemp` command executed as
a normal user and then executing `sudo oscap`.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2048571
If OpenSCAP fails to open the file because of permissions, it will retry
to open the file without O_CREAT flag.
Supersedes #1845 .
=> Prevent file permissions errors

docs/manual/manual.adoc
It's misleading, we don't generate a plain report thanks to
https://serverfault.com/questions/1099675/generating-plain-text-report-in-openscap
=> Remove information about plain text report

.packit.yaml
EPEL build targets are redundant as we now have CentOS Stream
build targets.
=> Remove EPEL build targets from Packit

openscap.spec
If the `source_date_epoch_from_changelog` is set to true,
the `SOURCE_DATE_EPOCH` environment variable is set to the timestamp
of the topmost changelog entry. As we do not have a changelog
in the upstream spec file we auto generate it.
=> Packit: fix build issue on Fedora Rawhide

src/common/memusage.c
While debugging https://github.com/OpenSCAP/openscap/issues/1858, I see that strtoll was being called before resetting errno. In some cases, it can result in false positives.
=> Reset errno before call to strtoll

utils/scap-as-rpm, utils/scap-as-rpm.8
Update whatis entry and add some commas to fix grammar.
Replaced deprecated .HP macro with .TP.
=> Minor fix in man-page scap-as-rpm.8

tests/API/probes/CMakeLists.txt, tests/API/probes/test_memusage.c, tests/API/probes/test_memusage.sh
The unit test will cover the missing set errno
to 0 which was the root cause of:
https://github.com/OpenSCAP/openscap/issues/1867
Therefore, this test can be used during verification of:
https://bugzilla.redhat.com/show_bug.cgi?id=2109485
=> Add unit test for read_common_sizet function

src/OVAL/probes/independent/sql57_probe.c, src/OVAL/probes/independent/sql_probe.c, src/OVAL/probes/oval_fts.c, src/OVAL/probes/unix/xinetd_probe.c
This sets errno to 0 before strotol calls after which the errno
is being checked.
Per man 3 strtol:
Since  strtol()  can  legitimately  return 0, LONG_MAX, or
LONG_MIN (LLONG_MAX or LLONG_MIN for strtoll()) on both success and
failure, the calling program should set errno to 0 before the call, and
then determine if an error occurred by checking whether errno has a
nonzero value after the call.
This is inspired by https://github.com/OpenSCAP/openscap/pull/1861.
=> Reset errno before strtol

CMakeLists.txt, utils/CMakeLists.txt
This patch introduces a new CMake build option
ENABLE_OSCAP_REMEDIATE_SERVICE which can be used to disable the
installation of the files related to the oscap-remediate systemd
service. Downstream packagers can use this option to disable shipping
the oscap-remediate service in their RPM spec files.
Resolves: rhbz#2111358
Resolves: rhbz#2111360
=> Add CMake option to disable oscap-remediate service

src/OVAL/probes/SEAP/sexp-value.c
The lblk pointer is affected by 2-bit LSB magic SEAP uses for reference-counting. On 32-bit platforms it requires extra alignment.
Fixes #1852.
Now it passes all the tests in the test suite on RPi (32-bit, ARMv7).
=> OVAL/SEAP: Allocate aligned memory in SEXP_rawval_lblk_new

openscap.spec
According to Fedora packaging guidelines
https://fedoraproject.org/wiki/Packaging:Systemd#Filesystem_locations in order for the %{_unitdir} macro to exist, our package must have BuildRequires: systemd.
Addressing:
error: File not found: /builddir/build/BUILDROOT/openscap-1.3.7-0.20220830091921540256.pr1882.62.g2bc28fe27.fc38.x86_64/usr/libexec/oscap-remediate
error: File must begin with "/": %{_unitdir}/oscap-remediate.service
error: File must begin with "/": %{_unitdir}/system-update.target.wants/
File not found: /builddir/build/BUILDROOT/openscap-1.3.7-0.20220830091921540256.pr1882.62.g2bc28fe27.fc38.x86_64/usr/libexec/oscap-remediate
File must begin with "/": %{_unitdir}/oscap-remediate.service
File must begin with "/": %{_unitdir}/system-update.target.wants/
=> Fix build due to unresolved unitdir

src/common/util.c
Sometimes the string that we perform the regular expression match
on can be very long, for example the whole contents of the
/var/log/messages. We need to set a limit and show only some
part of the string when the string is very long to prevent pollution
of various logs and outputs.
=> Truncate string in error message

src/OVAL/probes/SEAP/MurmurHash3.c, src/OVAL/probes/independent/xmlfilecontent_probe.c, src/OVAL/probes/unix/interface_probe.c, src/OVAL/probes/unix/linux/iflisteners_probe.c, src/OVAL/probes/unix/xinetd_probe.c, src/common/memusage.c, utils/oscap-ds.c
Assortment of changes I saw after I enabled ASAN and UBSAN.
Target here was for me to enable sanitizers and see that ctest passes and then see that my tailored DS passes too. I was not able to make ASAN to work with some plugins so I needed to modify testing etc to skip those.
=> ASAN, UBSAN, compiler warning fixes

openscap.spec
This avoids this problem in the CentOS Stream 8 build in Packit.
```
error: %changelog entries must start with *
```
Most likely, the reason would be that the `%autochangelog` macro isn't supported on CS8.
=> Remove changelog from SPEC

tests/probes/process58/command_line_extra.sh
Use correct command line, on some systems, the zombied process isn't "bash" but it can be "sleep" so we need to check for both these names.
Fixes: #1897
=> Fix stuck test command_line_extra.sh

utils/oscap-ssh
The original name was misleading, as the ssh manual shows.
=> Rename master socket to control socket

release_tools/naming.sh, src/OVAL/adt/oval_smc_iterator.c
This PR aims to make the code and comments more expressive - check out individual commits for more information.
- Fix naming of private iterators
- Reformulate a comment in a deduplication database
=> Improve naming and clarify comments

tests/codestyle/all.sh, tests/probes/sysctl/test_sysctl_probe_all.sh
Rename misleading `whitelisted` variable in `tests/codestyle/all.sh`.
Rename `SYSCTL_BLACKLIST*` variables in `tests/probes/sysctl/test_sysctl_probe_all.sh`
=> Rename blacklist in tests

.github/workflows/build.yml
The DEB package lua50 isn't available in Ubuntu 22.04.
This fixes the broken CI gating on Ubuntu machines.
=> Update Lua to a newer version

tests/probes/sysctl/test_sysctl_probe_all.sh
This sysctl setting seems to be a new feature in kernel 6.2 and we don't process it.
This fixes the broken CI gating job testing farm on Rawhide.
Addressing:
230/265 Test #230: probes/sysctl/test_sysctl_probe_all.sh .............................................***Failed    0.81 sec
Result file: test_sysctl_probe_all.res.out.ADW5oP
Our names file: test_sysctl_probe_all.our.out.gW7nKh
Sysctl names file: test_sysctl_probe_all.sysctl.out.PMtj7U
Errors file: test_sysctl_probe_all.err.out.oDjUwy
Diff (sysctlNames / ourNames): ------
23d22
< dev.tty.legacy_tiocsti
=> Add dev.tty.legacy_tiocsti to skiplist

src/OVAL/probes/independent/xmlfilecontent_probe.c, tests/probes/xmlfilecontent/test_xmlfilecontent_probe.sh, tests/probes/xmlfilecontent/test_xmlfilecontent_probe.xml
This commit fixes the behavior of the xmlfilecontent probe in situation when the XPath query in xmlfilecontent_object doesn't match any node in the given XML file and the query returns an empty node set. Currently, in this situation, we emit an item in which we add an empty value_of element. However, this value_of element has its datatype attribute set to an empty string, which is invalid according to the OVAL schema. When we try to make the OVAL results valid, we face the problem that it isn't clear what should be the value of the datatype attribute for empty elements. But as we can realize the XPath doesn't match anything means that the requested object doesn't exist on the system, so a better behavior would be to not produce a xmlfilecontent54_item.  That is consistent with eg. …
=> Don't emit items if XPath doesn't match

release_tools/README.adoc
According to https://github.com/OpenSCAP/openscap/blob/maint-1.3/docs/windows.md we don't produce release builds.
=> Remove Windows from release Guide

.github/workflows/build.yml
Inspired by:
https://github.com/drogue-iot/drogue-cloud/commit/b31e2baa482f5458541a29c991d2d3109085a0c6
Great thanks to @ggbecker for suggestion!
Addressing:
Error: The `brew link` step did not complete successfully The formula built, but is not symlinked into /usr/local Could not symlink bin/2to3-3.11
Target /usr/local/bin/2to3-3.11
already exists. You may want to remove it:
rm '/usr/local/bin/2to3-3.11'
=> Workaround OS X GitHub Actions CI problems

release_tools/README.adoc
These information are generally useful. It's better to have every information releated to the release in a single place.
=> Move release guide to upstream

docs/contribute/testing.adoc, docs/developer/developer.adoc, docs/manual/manual.adoc
Fixes a few typographical errors across the docs:
- `affraid` -> `afraid`
- `direcotory` -> `directory`
- `usefull` -> `useful`
- `additonal` -> `additional`
- `utilitize` -> `utilize`
- `runing` -> `running`
=> Fix typos in docs

src/OVAL/probes/independent/xmlfilecontent_probe.c, utils/oscap-ds.c
Coverity has discovered 3 new issues in OpenSCAP 1.3.7 release.
For more details, please read commit messages of every commit.
=> Fix Coverity issues found in the 1.3.7 release

swig/openscap.i
openscapPYTHON_wrap.c:3734:14: error: incompatible integer to pointer conversion returning 'int' from a function with result type 'char *' [-Wint-conversion]
return 1;
^
It seems like return 1 is a copy-and-paste error and the function should return NULL here.  It's possible this function (sub_callback_wrapper) is unused and can be deleted but I wasn't sure.
=> Fix -Wint-conversion error building with clang

src/XCCDF/xccdf_session.c
The list skip_rules is allocated in xccdf_session_new_from_source, but was not freed in xccdf_session_free.
=> Fix leak of session->skip_rules

src/OVAL/probes/unix/linux/dpkginfo-helper.cxx
The arch, epoch, releasem version and evr strings are allocated in dpkginfo_get_by_name, but were not freed in dpkginfo_free_reply.
=> Fix leak of dpkginfo_reply_t fields

src/OVAL/probes/unix/linux/partition_probe.c
PROC_CHECK is not defined anymore, since the removal of automake.
=> Remove reference to PROC_CHECK

tests/API/probes/CMakeLists.txt
=> enable test_memusage only if OS_LINUX is defined

tests/API/probes/CMakeLists.txt
Actually this should be fixed in a different way, by adding `if defined (OS_SOLARIS)` to the internal implementation of the function. See: https://github.com/OpenSCAP/openscap/pull/1941
Reverts OpenSCAP/openscap#1946
=> Revert "enable test_memusage only if OS_LINUX is defined"

release_tools/README.adoc
During the OpenSCAP 1.3.7 upstream release process I noticed that some of the text in the release guide is outdated, inconsistent or missing. In this patch we update the release guide so that it will be easier to perform the next release.
=> Update release guide

CMakeLists.txt, src/common/memusage.c
Now that FreeBSD has imported LLVM15, new errors are flagged.
Ideally the code that implicily converts integers should be fixed but a first step is to use a compiler option that ignores the errors like prior versions of LLVM and GCC do.
Additionaly, as in Linux, read_common_sizet() is also undefined in FreeBSD.
=> Fix build on FreeBSD.

.github/workflows/build.yml, .github/workflows/codeql.yml
GH Actions: Bump actions/checkout to version 3
Version 2 is based on Node.js 12 and is deprecated. Version 3 is based
on Node.js 16. There are some minor changes but none that affects
OpenSCAP. The action for 'CodeQL' already uses version 3.
---
GH Actions: Stop upgrading packages on Ubuntu
Don't upgrade packages before we install new ones. This patch also
replaces an environment variable for a command line option for the
'apt-get' command.
=> GH Actions: Fix deprecation warnings and build on Ubuntu

src/OVAL/probes/unix/linux/rpminfo_probe.c, src/OVAL/probes/unix/linux/rpmverify_probe.c, src/OVAL/probes/unix/linux/rpmverifyfile_probe.c, src/OVAL/probes/unix/linux/rpmverifypackage_probe.c, tests/DS/test_ds_misc.sh, tests/DS/test_sds_eval.sh, tests/probes/rpm/rpm_common.sh
Fedora >=36 changed the default dbpath in librpm from /var/lib/rpm to /usr/lib/sysimage/rpm Therefore, when running openscap on a Fedora >=36 system scanning another systems (such as RHEL, SLES, Fedora<36) openscap's librpm will try to read the rpm db from /usr/lib/sysimage/rpm which doesn't exist and therefore won't work. In implementing this change, /var/lib/rpm is still a symlink to /usr/lib/sysimage/rpm so /var/lib/rpm still works. So /var/lib/rpm is a dbpath that will work on all systems. Therefore, set the dbpath to be /var/lib/rpm, allow openscap running on any system to scan any system.
See: https://fedoraproject.org/wiki/Changes/RelocateRPMToUsr
Fixes: https://github.com/OpenSCAP/openscap/issues/1942
`cd build && cmake ../ && make -j4 && ctest` shows all tests as passing on my …
=> Always use /var/lib/rpm as rpm dbpath

src/OVAL/oval_component.c
component_colls are allocated in _oval_component_evaluate_CONCAT, but were not freed when not_finished is null.
=> Fix leak of component_colls in _oval_component_evaluate_CONCAT

src/OVAL/probes/fsdev.c
Auristor is a commercial version of the AFS filesystem and has type of 'auristorfs'.  Add it to the list of network fileystems so it is excluded when the scan is restricted to local filesystems.
=> Add 'auristorfs' to list of network fileystems

CMakeLists.txt, src/OVAL/probes/unix/linux/rpm-helper.h
The function 'rpmFreeCrypto' is implicitly declared. This will be forbidden in future versions of GCC (the `-Werror=implicit-function-declaration` behaviour will be enforced).
On top of that, as an anti-regression measure, the flag `-Werror=implicit-function-declaration` is now part of the CMake config.
Follow-up on #1922. Kudos @tstellar and @fweimer-rh.
=> Fix implicitly declared function

src/XCCDF/xccdf_session.c, src/source/oscap_source.c, src/source/public/oscap_source.h
When calling the xccdf_session_load_(xccdf|cpe|oval) functions, the session->source structure is recopied to
session->ds.session->component_sources, including the source->xml.doc field, which contains the XML DOM.
This change adds a new oscap_source_free_xmlDoc function to the OSCAP source API and call it at the end of the xccdf_session_load function, so session->source->xml.doc is freed when it's not used anymore.
=> Free xmlDoc structure at the end of xccdf_session_load

.github/workflows/build.yml, docs/developer/developer.adoc, openscap.spec
* Using openscap to scan a system that use apt (such as Debian or Ubuntu) returns incomplete results. This warning is logged: OVAL object 'dpkginfo_object' is not supported.
The problem is that openscap is built without apt support.
The fix, implemented in this commit, is to add apt as a build requirement.
=> apt-devel to BuildRequires; apt-libs to Requires

src/common/debug.c
Prevent data race on the static `indent` variable. The __oscap_dlprintf function is called from multiple threads, which means multiple threads can modify the `ident` static variable.
There is already a mutex (`__debuglog_mutex`) used in this code. We only need to move the manipulation with the ident variable between the lock and unlock operation on this mutex.
=> Prevent data race

src/CPE/cpelang_priv.c, src/OVAL/oval_object.c, src/OVAL/oval_sysInfo.c, src/OVAL/probes/probe-api.c
The existence of these variables trigger CLang warnings about unused variables.
=> Remove unused variables

src/OVAL/probes/probe-table.c, src/OVAL/probes/unix/sysctl_probe.c, src/OVAL/probes/unix/sysctl_probe.h, tests/probes/sysctl/CMakeLists.txt, tests/probes/sysctl/test_sysctl_probe_offline_mode.sh
Although the probe collects the data from `/proc/sys/...` filesystem it is useful for the so-called hybrid mode (OCP, etc).
Note: There are a lot of changes to the indentation, but they all are concentrated in the first commit, it makes sense to review just the second.
=> Add offline capabilities to the sysctl OVAL probe

src/OVAL/probes/probe/icache.c
This change fixes leak of `item` in `probe_item_collect` when `probe_cobj_memcheck` didn't return `0` (error or when memory contraints are reached).
=> Fix leak of item in probe_item_collect

utils/oscap-podman
grep: warning: stray \ before -
is printed by GNU grep 3.11. This can be fixed by terminating the argument parsing before by using ' -- ' which then avoids the quoting alltogether.
=> Avoid grep warning on oscap-podman invocation

src/OVAL/oval_agent.c
This change fixes leak of `ag_sess->filename` in `oval_agent_new_session` when `oval_probe_query_sysinfo` returned `!= 0`.
=> Fix leak of filename in oval_agent_new_session

CMakeLists.txt
Variables PREFERRED_PYTHON_PATH and PYTHON3_PATH are set with ${PYTHON_EXECUTABLE}. For cross compile, ${PYTHON_EXECUTABLE} may point to other path rather than standard dir such as /usr/bin. Then the generated library file contains such path which should NOT. Update to make variables PREFERRED_PYTHON_PATH and PYTHON3_PATH configurable to avoid such issue.
v2:
* change variables' types to `PATH` and update docstring
=> v2: CMakeLists.txt: make 2 variables configurable

xsl/xccdf-report-impl.xsl
I was making some openembedded patches and I saw this:
so I made a patch for that too.
=> fix un-expanded variable in xccdf report output

src/OVAL/probes/unix/sysctl_probe.c, tests/probes/sysctl/test_sysctl_probe_offline_mode.sh
The initial implementation was buggy: after correctly traversing prefixed PREFIX/proc/sys directory tree it would incorrectly read the data from the non-prefixed directory tree.
=> OVAL/sysctl: Fix offline mode

src/OVAL/probes/unix/linux/dpkginfo-helper.cxx, src/OVAL/probes/unix/linux/dpkginfo_probe.c
In the dpkginfo probe, the dpkg cache was allocated in dpkginfo_init. However, dpkginfo_init can be called multiple times, leading the cgCache pointer to be overridden and leaking the dpkg cache.
=> Fix leak of dpkg cache when dpkginfo_init is called multiple times

release_tools/release.sh
We don't need it for tests to pass.
=> Remove sendmail from prerequisites of release_tools

docs/developer/developer.adoc
The package apt-devel isn't present in RHEL systems.
=> Update build dependencies in Developer guide

src/XCCDF/public/xccdf_session.h, src/XCCDF/xccdf_session.c
This change adds a new public `xccdf_session_get_rule_results` function to the XCCDF session API.
This function returns rule results.
Results could be iterated using the `xccdf_rule_result_iterator_has_more` function from the XCCDF benchmark API.
=> Implement xccdf_session_get_rule_results function in XCCDF session API

src/OVAL/probes/unix/linux/partition_probe.c, tests/probes/partition/test_probes_partition.sh, tests/probes/partition/test_probes_partition.xml
The pcre_exec function can return a positive number or zero, zero is returned if the buffer isn't large enough. Therefore, we should allow also positive number return code.
The commit also extends the test to cover the bug situation.
Fixes: #2026
=> Fix partition probe for PCRE2

src/OVAL/probes/SEAP/seap-packetq.c, src/OVAL/probes/probe/icache.c
This change fixes deadlocks reported by Coverity.
=> Fix deadlocks reported by Coverity

src/OVAL/probes/probe/worker.c
This change fixes out-of-bounds access reported by Coverity.
=> Fix out-of-bounds access reported by Coverity

src/CPE/cpe_session.c
When using `oscap xccdf eval --oval-results` command, the oval result file is not expected one (`openscap-cpe-oval.xml.result.xml`), but `%2Fusr%2Fshare%2Fopenscap%2Fcpe%2Fopenscap-cpe-oval.xml.result.xml`.
This patch fixes the issue.
=> Fix incorrect openscap-cpe-oval result filename

src/OVAL/oval_agent.c, src/OVAL/public/oval_agent_api.h, src/XCCDF/public/xccdf_session.h, src/XCCDF/xccdf_session.c
This change adds a new public `xccdf_session_result_reset` function to the XCCDF session API.
This function resets XCCDF session results, so `xccdf_session_evaluate` could be called again from a clean state, without having to call `xccdf_session_free`, which would imply to parse the XCCDF file again.
This function resets XCCDF policies, session rules, skipped rules, OVAL system characteristics and OVAL results.
=> Implement xccdf_session_result_reset function in XCCDF session API

src/OVAL/probes/SEAP/generic/strto.c, src/OVAL/probes/independent/sql57_probe.c, src/OVAL/probes/independent/sql_probe.c
This change fixes incorrect expressions reported by Coverity.
=> Fix incorrect expressions reported by Coverity

tests/probes/sysctl/test_sysctl_probe_all.sh
Fixes failing CI on Ubuntu and Fedora caused by new sysctl options.
Addressing:
```
239/278 Test #239: probes/sysctl/test_sysctl_probe_all.sh .............................................***Failed    0.48 sec
Result file: test_sysctl_probe_all.res.out.49w9xN
Our names file: test_sysctl_probe_all.our.out.o4wjUZ
Sysctl names file: test_sysctl_probe_all.sysctl.out.3nEoMb
Errors file: test_sysctl_probe_all.err.out.YeCCxH
Diff (sysctlNames / ourNames): ------
56,58d55
< kernel.apparmor_restrict_unprivileged_userns
< kernel.apparmor_restrict_unprivileged_userns_complain
< kernel.apparmor_restrict_unprivileged_userns_force
```
=> Add AppArmor sysctl entries to exception list

docs/manual/manual.adoc, utils/autotailor.8
- Refresh User Manual
- Add missing Synopsis and Options sections to the man page
The goal of this activity is to make sure `autotailor` is documented. Fortunately, there is already a great section "Tailoring" in the User Manual that covers `autotailor` well.
=> Update documentation of autotailor

src/OVAL/oval_sexp.c, src/OVAL/probes/probe/worker.c, src/OVAL/probes/unix/linux/inetlisteningservers_probe.c, src/OVAL/probes/unix/linux/rpmverifypackage_probe.c
This change fixes various issues reported by Coverity :
- oval_sexp_to_sysitem: null pointer derefrence
- probe_worker: insecure chroot
- inetlisteningservers_probe_main: uninitialized memory
- rpmverifypackage_additem: invalid type in argument to printf format specifier
=> Fix various issues reported by Coverity

src/OVAL/probes/probe/probe_main.c
The probe_reset function didn't work properly, because its second argument was always NULL.
This changes fixes the probe_reset function by passing the probe as the second argument.
This change also call probe_ncache_clear to clear the ncache instead of calling probe_ncache_free and probe_ncache_new, like it was done in change 057873ac7c816b5e067c49442bd4f55b77121e9c.
=> Fix probe_reset

swig/openscap_api.py
Python 3.12 got `imp` module removed: https://docs.python.org/3/whatsnew/3.12.html#imp
The workaround is based on `importlib` module. Python 2 branch is removed because we don't care about Python 2 anymore.
=> Fix removal of imp module in Python 3.12

tests/probes/sysctl/test_sysctl_probe_all.sh
The test will now automatically adapt to the list of readable variables and won't break every time a new root-readable variable is introduced in kernel.
Fixes: #2049
=> Fix tests/probes/sysctl_all

src/OVAL/probes/unix/linux/dpkginfo-helper.c
This change fixes a mistake made during a last-minute change
in 557ddeed1e3e234a655ad77a691869554064b293.
The parsing the Status was incorrect and all
packages were considered as deinstalled.
Sorry for that.
=> Fix parsing of Status in dpkginfo probe

xsl/xccdf-report-oval-details.xsl
With this update it is clearer when a test fails due to a few objects from many collected
Attaching some examples to show the suggested change in action, and how can it be useful:
Note:
If there is a cleaner way and it is preferable let me know. I'm not quite familiarized with xsl
=> Update html report with oval details

src/common/xml_iterate.c
this would show of on gcc 3.13 + -Werror
```
[ 10%] Building C object src/common/CMakeFiles/common_object.dir/xml_iterate.c.o
cd /builddir/build/BUILD/openscap-1.3.9/redhat-linux-build/src/common && /usr/bin/gcc -DHAVE_CONFIG_H -DOSCAP_BUILD_SHARED -DXMLSEC_CRYPTO_OPENSSL=1 -DXMLSEC_DL_LIBLTDL=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_SIZE_T -D__XMLSEC_FUNCTION__=__func__ -I/builddir/build/BUILD/openscap-1.3.9/compat -I/builddir/build/BUILD/openscap-1.3.9/src -I/builddir/build/BUILD/openscap-1.3.9/src/common -I/builddir/build/BUILD/openscap-1.3.9/src/common/public -I/builddir/build/BUILD/openscap-1.3.9/src/CPE/public -I/builddir/build/BUILD/openscap-1.3.9/src/CVE/public -I/builddir/build/BUILD/openscap-1.3.9/src/CVRF/public …
```
=> fix implicit declaration

tests/probes/systemdunitproperty/test_probes_systemdunitproperty.xml, tests/probes/systemdunitproperty/test_probes_systemdunitproperty_offline_mode.xml
The current test of the `systemdunitproperty` probe is relying on the assumption that the `systemd-journald.service` unit doesn't have the `Conflicts` property set. In Rawhide, this assumption is no longer true, because `Conflicts` is now set to `soft-reboot.target` by default. This change breaks our test. In this commit, we will make the test less dependent on actual property value. Instead, we will check a dummy property that is unlikely to occur.
Fixes: #2066
=> Make systemdunitproperty probe test more independent

.github/workflows/build.yml
Add GitHub Actions to build Windows version and will upload the artifact so it can be used elsewhere.
=> Build Windows on GitHub Actions

src/source/validate.c, swig/openscap.i
Without these changes, compilation with GCC 14 will fail due to type errors.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
=> GCC 14 compatibility fixes

xsl/xccdf-guide-impl.xsl, xsl/xccdf-references.xsl, xsl/xccdf-report-impl.xsl, xsl/xccdf-share.xsl
In this commit we will leverage the reference URI-to-title mapping within the `xccdf:Benchmark` element to visually improve the references in HTML guide and report.
This improvements needs SCAP content to contain reference URI-to-title mapping within the `xccdf:Benchmark` element to work nicely.  The ComplianceAsCode content upstream project started to provide this mapping in the SCAP content recently, starting from 62513c391dc5a3fafd12741bd02565ca0e1e8db2.
However, the enhancement is compatible with SCAP content that doesn't contain the reference URI-to-title mapping. If this mapping isn't present, URIs are shown instead of titles in the HTML guides and report. But it still provides a singificant UX improvement.
Moreover, the `Group by` dropdown feature will now also use the URI-to-title …
=> Improve references in HTML guides and reports

docs/manual/manual.adoc, src/common/debug.c, src/common/public/oscap_debug.h, utils/oscap-tool.c
If OpenSCAP is executed with verbosity level INFO or DEVEL all environment variable values that can affect OpenSCAP behavior will be listed at the beginning of the log.
Fixes: #2063
=> Print environment variables

src/OVAL/probes/probe/icache.c, src/OVAL/probes/probe/probe.h, src/OVAL/probes/probe/worker.c
The function SEXP_list_length turns out to be an unreliable provider of information about the length of the list of the collected items. It is unclear what this function returns. Instead of using SEXP_list_length we will have a counter variable that will count the amount of collected items by the probe.
Fixes: #2076
=> Improve counting collected items

xsl/xccdf-guide-impl.xsl
Finishing off the last part #1743.
This adds remarks to the guide HTML.
=> First try at adding remarks to the guide

src/CPE/cpe_session.c, src/OVAL/probes/independent/yamlfilecontent_probe.c, src/OVAL/probes/unix/xinetd_probe.c, src/OVAL/results/oval_cmp_evr_string.c, src/XCCDF/item.c, src/XCCDF/item.h, src/XCCDF/public/xccdf_benchmark.h, src/XCCDF/rule.c, swig/python3/CMakeLists.txt
Fixes https://github.com/OpenSCAP/openscap/issues/1992.
Fixes warnings:
```
/__w/openscap/openscap/src/CPE/cpe_session.c: In function 'cpe_session_lookup_oval_session':
/__w/openscap/openscap/src/CPE/cpe_session.c:117:50: warning: passing argument 1 of 'oscap_basename' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
117 |                 char *base_name = oscap_basename(prefixed_href);
|                                                  ^~~~~~~~~~~~~
In file included from /__w/openscap/openscap/src/CPE/cpe_session.c:37:
/__w/openscap/openscap/src/common/public/oscap_helpers.h:52:38: note: expected 'char *' but argument is of type 'const char *'
52 | OSCAP_API char *oscap_basename(char *path);
|                                ~~~~~~^~~~
```
``` …
```
=> Fix `requires` and warnings

src/XCCDF_POLICY/xccdf_policy_remediate.c, tests/API/XCCDF/unittests/test_remediation_blueprint.toml
Now the generated Blueprint file will be ready-to-use right after generation unless a custom data stream is used for hardening.
There are also instructions on how to adapt the Blueprint for a custom data stream.
=> Fix Blueprint template to be self-contained

src/XCCDF_POLICY/xccdf_policy_remediate.c, tests/API/XCCDF/unittests/test_remediation_blueprint.toml, tests/API/XCCDF/unittests/test_remediation_blueprint.xccdf.xml
This will now be properly parsed and organized:
```toml
[customizations.services]
masked = ["service"]
```
=> Support Blueprint services customization for masking

CMakeLists.txt
Accidentally, the GitHub CI started to build Perl bindings on Windows because the dependencies become available. However, the build fails because our code isn't ready to be built on Windows.  This change will ensure the Perl bindings are kept disabled on Windows.
See: https://github.com/OpenSCAP/openscap/actions/runs/8879756994/job/24378248762?pr=2104
=> Disable Perl bindings on Windows

src/DS/rds.c, tests/API/XCCDF/tailoring/all.sh, tests/API/XCCDF/tailoring/xlink-test-simple-ds.xml
If the document doesn't contain the xlink namespace, we need to define it before we create the `xlink:href` attribute.
This situation happens if the `data-stream-collection` root element of the input SCAP source data stream doesn't have the xlink namespace defined.
Resolves: RHEL-34104
=> Ensure xlink namespace exists

.github/workflows/build.yml, .github/workflows/codeql.yml, src/CPE/cpedict_priv.c, src/CPE/public/cpe_dict.h, src/OVAL/probes/independent/filehash58_probe.c, src/OVAL/probes/independent/filehash_probe.c, src/common/util.h
=> Fix last remaining warning and enable CMAKE_COMPILE_WARNING_AS_ERROR in Gating CI jobs (Fedora/Ubuntu)

src/OVAL/results/oval_cmp_ip_address.c, src/common/_error.h, src/common/error.c, src/source/bz2.c
These compiler warnings appeared with latest GCC on F40 (gcc-14.1.1-4.fc40.x86_64).
This should solve the failing "Build, Test on Fedora Latest" CI job.
For more details, please read commit messages of each commit.
=> Fix new compiler warnings

CMakeLists.txt
By default, we will build OpenSCAP without MD5 and SHA1 hash functions. As a result, filehash probe won't be built by default.
Fixes: #1784
=> Disable MD5 and SHA-1 by default

src/source/oscap_source.c, src/source/public/oscap_source.h, src/source/schematron.c, src/source/schematron_priv.h, utils/oscap-oval.c, utils/oscap-xccdf.c
The function `oscap_source_validate_schematron` is always called with the second parameter `outfile` set to NULL, therefore this parameter isn't needed and we can decide that the output will be printed to stdout. That allows further simplification of static functions in schematron.c.
Fixes: #1720
=> Simplify oscap_source_validate_schematron

swig/openscap.i
Use PyObject instead of PyEval for python 3.13 compatibility
=> Python 3.13 compatibility

docs/manual/manual.adoc, src/XCCDF_POLICY/xccdf_policy_remediate.c, tests/API/XCCDF/unittests/test_remediation_kickstart.ds.xml, tests/API/XCCDF/unittests/test_remediation_kickstart_expected.cfg
In this commit, we will add option for managing firewall rules
during the installation:
* `firewall enable service_name` - adds `service_name` to list in the
`--service=` option in the `firewall` command in commands section in
the kickstart
* `firewall disable service_name` - adds `service_name` to list in the
`--remove-service=` option in the `firewall` command in commands
section in the kickstart
Also, the test will be extended for these new commands.
Related to:
https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#firewall
=> Add firewall command to Kickstart remediation

tests/utils/autotailor_integration_test.sh, tests/utils/custom.json, tests/utils/test_autotailor.py, utils/autotailor, utils/autotailor.8
The script will now accept multiple profiles in JSON Tailorings and also will use command-line options to update existing profiles or will create a new profile in the XCCDF tailoring.
Also, I've added a synonym option `--tailoring-profile-id` for the existing rather confusing option `--new-profile-id`.
I've tried to keep backward-compatibility both in logic and in the CLI API.
=> Enable autotailor to process multi-profile JSON Tailorings

src/OVAL/probes/independent/textfilecontent_probe.c, src/XCCDF_POLICY/xccdf_policy_remediate.c
For more details, please read commit messages of all commits.
=> Fix issues reported by OpenScanHub after 1.4.0 release

src/OVAL/probes/crapi/digest.c
The size_t is implementation-dependent data type, it shouldn't be cast to unsigned int.
Fixes failing test probes/filehash58/test_probes_filehash58.sh on s390x architecture.
=> Fix a cast

CMakeLists.txt, cmake/FindPythonModule.cmake, tests/utils/CMakeLists.txt
We will run autotailor unit tests only if pytest is installed on the system. CMake will check for the presence of pytest and enable or disable the unit tests test accordingly.
Fixes: #2153
=> Check autotailor unit test dependencies

.github/workflows/build.yml, .github/workflows/codeql.yml, .packit.yaml
We don't need fresh Fedoras or Ubuntus. We keep that version only for older RHELs and Ubuntu LTSes.
I've also removed MacOS X.
=> Cleanup CI for maint-1.3 branch

src/OVAL/probes/unix/linux/rpm-helper.c, src/OVAL/probes/unix/linux/rpm-helper.h, src/OVAL/probes/unix/linux/rpminfo_probe.c, src/OVAL/probes/unix/linux/rpmverify_probe.c, src/OVAL/probes/unix/linux/rpmverifyfile_probe.c, src/OVAL/probes/unix/linux/rpmverifypackage_probe.c, tests/probes/rpm/rpm_common.sh, tests/probes/rpm/rpmverifypackage/rpmverifypackage_common.sh
The assumption that /var/lib/rpm is always a symlink to /usr/lib/sysimage/rpm was wrong. In bootc images, it isn't the case. As a result, all rules were evaluated as notapplicable when scanning a bootc image or container.
We will fix it the following way: We will first try if the "new" location /usr/lib/sysimage/rpm exists, and use it only if it exists.  If it doesn't exist, we will fall back to the "old" location /var/lib/rpm.
Fixes: https://issues.redhat.com/browse/RHEL-55251
Fixes: https://github.com/OpenSCAP/openscap/issues/2151
This would be a first step to get OpenSCAP ready for  bootc experience.
First, reproduce the problem and verify that we fixed it.
sudo podman pull quay.io/centos-bootc/centos-bootc:stream9
sudo oscap-podman quay.io/centos-bootc/centos-bootc:stream9 oval eval …
=> Improve RPM database path in RPM probes

src/OVAL/oval_session.c
With new libxml2 version it's missing limits.h on Solaris.
=> fix missing declaration of PATH_MAX on Solaris

src/OVAL/probes/probe/worker.c
Currently the `oscap_split` will alter the environ string of "OSCAP_PROBE_IGNORE_PATHS". This leads to "OSCAP_PROBE_IGNORE_PATHS" does not work as expected in subsequent use. The small patch fixed this issue.
=> Make a copy before spliting.

utils/oscap-bootc
Some SCE checks which are used instead of OVAL checks when building a bootable container require additional packages. This commit introduces `install_sce_dependencies` function in `oscap-bootc` script which will handle their installation.
This is related to https://github.com/ComplianceAsCode/content/pull/12564
Marking it as a draft as I am not sure if this is the best solution. Maybe it would be better to make packages which are required by SCE checks as dependencies of `openscap-utils` RPM or even `scap-security-guide` RPM.
=> Extend oscap-bootc to install SCE dependencies

.packit.yaml
This change will cause automatic building of COPR builds after committing to `maint-1.3` branch. The `maint-1.3` branch isn't the project default branch. Without specifying the branch, Packit builds after committing only to the project's default branch, which is the `main` branch at this moment. The `maint-1.3` branch used to be default branch, but after we switched the default branch to main, the COPR builds on maint-1.3 stopped to be built.
Related documentation:
https://packit.dev/docs/configuration/upstream/copr_build
=> Build COPR builds for maint-1.3

.packit.yaml
The current configuration makes build Fedora builds on commit to the maint-1.3 branch.
https://copr.fedorainfracloud.org/coprs/packit/OpenSCAP-openscap-maint-1.3/ But, we wanted to have CentOS Stream builds instead.
=> Request CentOS Stream builds explicitly

swig/openscap_api.py
- Update link for reporting possible bugs in openscap_api.py
At the bottom of the man page for the `oscap tool`, the following text appears:
```
REPORTING BUGS
Please report bugs using https://github.com/OpenSCAP/openscap/issues
Make sure you include the full output of `oscap --v` in the bug report.
```
This change ensures consistency by directing users to the same location for reporting issues
=> Update bug report link in openscap_api.py

utils/oscap_docker_python/oscap_docker_util.py
The API call to create a docker image (e.g. the docker command `docker create`) does not support creating a non-running container with no entrypoint or command specified. This will cause `oscap-docker` to fail with the HTTP 400 error from the Docker service:
```
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.45/containers/create: Bad Request 
("no command specified")
```
To solve this, for scanning purposes only, pass a null character as the explicit command for all containers.
An example Dockerfile for a container with no command is below. It is more common for container images designed to be used as a base container to have no command as they are not intended to be run directly.
```dockerfile
FROM scratch
COPY . /
```
=> Add support for containers with no entrypoint/cmd

openscap.spec, utils/oscap-bootc
The script is updated to first verify that it runs in a bootable container environment - `bootc` package must be installed and `/run/.containerenv` file must exist which indicates we are running inside a container. If it is not running inside a bootable container environment it informs user and exits.
Another change is that installation of `openscap-engine-sce` package has been moved from specfile into the script as the script already installs other requirements which are needed by SCE checks from CaC/content.
=> Update oscap-bootc to verify it runs in bootable container env

utils/oscap-bootc
Closes #2186 
This should allow runs inside bootc to download remote content.
=> Allow oscap-bootc to download remote resources

src/OVAL/probes/independent/textfilecontent_probe.c, src/XCCDF_POLICY/xccdf_policy_remediate.c
This PR will fix problems in the 1.4.1 release reported by OpenScanHub after downstreaming the release.
For more details, please read commit messages of all commits.
=> Fix problems reported by OpenScanHub

.packit.yaml
By default the COPR projects are deleted 60 days after creation. The preserve_project option should prevent the deletion.
https://packit.dev/docs/configuration/upstream/copr_build#optional-parameters
=> Avoid deleting COPR repository

src/OVAL/probes/unix/linux/rpminfo_probe.c
Fix rpminfo probe to correctly obtain `signature_keyid` in OL9, and possibly RHEL9
With existing maint1.3 code the key isn't obtained in OL9:
```
$ ./oscap_wrapper xccdf eval --profile stig --rule xccdf_org.ssgproject.content_rule_set_password_hashing_min_rounds_logindefs --oval-results /usr/share/xml/scap/ssg/content/ssg-ol9-ds.xml
$ grep signature_keyid ssg-ol9-cpe-oval.xml.result.xml 
<lin-sys:signature_keyid>0</lin-sys:signature_keyid>
```
Applying this change this information is correctly filled:
```
$ grep signature_keyid ssg-ol9-cpe-oval.xml.result.xml 
<lin-sys:signature_keyid>bc4d06a08d8b756f</lin-sys:signature_keyid>
```
=> Fix signature obtaining in rpm_info probe

CMakeLists.txt
This PR adds some more include dirs, in case the dependencies aren't all found in the same folder as the other ones
=> CMakeLists: add missing include dirs

src/XCCDF/xccdf_session.c, utils/oscap-xccdf.c
OpenSCAP remediation is supposed to be used only at bootc container image build. Deployed bootc system is immutable, it can't be remediated with OpenSCAP and trying to do so would result in errors and bad user experience.
We will update OpenSCAP to print error message for users in case they try to run remediation on an already deployed bootc system, informing them that it is not possible and that the openscap remediation must be performed during container build.
=> OPENSCAP-5235: Block remediation on deployed bootc system

CMakeLists.txt, src/OVAL/probes/SEAP/seap-command.c, src/OVAL/probes/SEAP/seap-packet.c, src/OVAL/probes/probe/icache.c, src/OVAL/probes/probe/icache.h, src/OVAL/probes/probe/input_handler.c, src/OVAL/probes/probe/probe.h, src/OVAL/probes/probe/probe_main.c, src/OVAL/probes/probe/worker.c, src/common/oscap_pcre.c
This PR contain a set of commits with fixes to thread synchronization and memory handling.
See individual commits for details.
=> Fix thread syncronization problems

utils/oscap-im
This commit will cause that oscap-im will exit with exit code 1 if any of the called oscap calls will fail. This means that building hardened bootable container images will terminate if oscap crashes or doesn't work.
Resolves: https://issues.redhat.com/browse/OPENSCAP-5415
=> Exit oscap-im if oscap fails

tests/API/OVAL/skip_paths/test_skip_paths.sh, tests/API/OVAL/skip_paths/test_skip_paths.xml
Modify the test so it could catch the regression
with environment variable modified during execution. See #2168.
=> tests: OVAL/API/skip_paths

compat/dev_to_tty.c, src/OVAL/probes/SEAP/generic/xbase64.c
Add more space for `low_density_name` elements in `compat/dev_to_tty.c`
```
dev_to_tty.c:170:71: error: initializer-string for array of 'char'
truncates NUL terminator but destination lacks 'nonstring' attribute
(7 chars into 6 available)
[-Werror=unterminated-string-initialization].
```
Add more space for `xbase64.c` alphabets
```
xbase64.c:155:42: error: initializer-string for array of 'char'
truncates NUL terminator but destination lacks 'nonstring' attribute
(65 chars into 64 available)
[-Werror=unterminated-string-initialization]
```
=> Fix `unterminated-string-initialization` errors

src/OVAL/probes/probe/worker.c
This change handles errors returned by msg_handler. It prevents the probe_worker_runfn function from crashing, when msg_handler returns NULL and the probe_res pointer is dereferenced.
For example, the probe_worker function could return NULL when calling chroot without root privileges.
=> Handle errors returned by msg_handler

CODEOWNERS
Brings https://github.com/OpenSCAP/openscap/pull/2225 also to `main` branch.
=> Introduce CODEOWNERS and add owners of the tests directory

.github/workflows/codeql.yml
See https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/
=> Fully move to codeql v3

src/XCCDF_POLICY/xccdf_policy_remediate.c
Fixes this:
```
3. openscap-1.4.2/src/XCCDF_POLICY/xccdf_policy_remediate.c:719:4: freed_arg: "oscap_pcre_err_free" frees "err".
5. openscap-1.4.2/src/common/oscap_pcre.c:239:3: freed_arg: "free" frees parameter "err".
7. openscap-1.4.2/src/XCCDF_POLICY/xccdf_policy_remediate.c:761:2: double_free: Calling "oscap_pcre_err_free" frees pointer "err" which has already been freed.
9. openscap-1.4.2/src/common/oscap_pcre.c:239:3: freed_arg: "free" frees parameter "err".
```
=> Fix double-free in xccdf_policy_remediate.c

src/source/signature.c
The default behaviour of xmlsec1 has changed int 1.3.x versions. It is now the response of the application to explicitly allow loading keys from KeyValue elements of the document.
Fixes: https://github.com/OpenSCAP/openscap/issues/2241.
=> Explicitly allow xmlsec1 to load key data from KeyValue

docs/contribute/contribute.adoc
Indeed the default branch is `main` now.
=> Fix the default branch note in contribution guide

.github/workflows/codeql.yml
So that codeql can run on the 1.3 branch.
=> Fix codeql on 1.3

src/XCCDF/result.c, xsl/xccdf-references.xsl
=> Add new STIG URL
