OpenSCAP/openscap

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
- Add Scientific Linux CPEs to inbuilt OpenSCAP CPE
- Part of https://github.com/openscap/scap-security-guide/pull/571
=> [Enhancement] add Scientific Linux CPEs

xsl/xccdf-guide-impl.xsl
The table of contents now contains only selected groups.
=> trac#482: Fixed table of contents in HTML guide.

src/common/Makefile.am, src/common/oscap_buffer.c, src/common/oscap_buffer.h, src/common/oscap_string.c
Move body of oscap_string to oscap_buffer.
oscap_buffer will offer some extra features.
=> oscap_string & oscap_buffer

schemas/sds/1.2/scap-source-data-stream_1.2.xsd, src/OVAL/oval_agent_api_impl.h, tests/DS/Makefile.am, tests/DS/sds_simple_5_11_1/simple_oval.xml, tests/DS/sds_simple_5_11_1/simple_xccdf.xml, tests/DS/test_ds.sh
Resolves issue https://github.com/OpenSCAP/openscap/issues/118
Blocked by pull request https://github.com/OpenSCAP/openscap/pull/125
=> Maint 1.2 sds schema

src/common/oscap_acquire.c, src/common/oscap_string.c, src/common/oscap_string.h
=> oscap_acquire use oscap_buffer

ac_probes/configure.ac.tpl, configure.ac, src/OVAL/oval_version.c, src/OVAL/probes/probe/option.c, src/XCCDF_POLICY/xccdf_policy_resolve.c, src/common/err_queue.c, tests/Makefile.am, tests/sources/Makefile.am, tests/sources/all.sh
https://fedorahosted.org/openscap/ticket/485
=> Test: Checking .c sources for #include config.h

src/SCE/sce_engine.c, tests/sce/Makefile.am, tests/sce/test_passing_vars.sh, tests/sce/test_passing_vars_sce.sh, tests/sce/test_passing_vars_xccdf.xml
This is a fix for an issue which was reported by Jacob Varughese.
See: https://fedorahosted.org/openscap/ticket/498
=> Use a value specified by <set-value> element

src/common/oscap_string.c, src/common/oscap_string.h
Add functions to oscap_string
Please merge to maint-1.2
=> Maint 1.0 string func

src/OVAL/probes/independent/environmentvariable58.c
I am looking into this code due to random errors during tests, so I have to refactor this...
=> environmentvariable58 refactoring

tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/test_xccdf_resolve.sh, tests/API/XCCDF/unittests/test_xccdf_resolve.xccdf.xml
Add simple test for "oscap xccdf resolve"
=> tests: add test to oscap xccdf resolve

docs/contribute/versioning.adoc
Replaces https://github.com/OpenSCAP/openscap/pull/181
=> Add versioning document

tests/probes/process58/command_line.sh
This test sometimes randomly fails. I would like to know more
when it will happen next time.
=> Add set -x to a test

src/OVAL/oval_probe.c
This wants to improve information presented in verbose log file. It may help us to see a "story" in the log.
=> Add debugging messages to oval_probe.c

src/OVAL/oval_agent.c
This will make the log file more understandable.
=> Add new debugging messages to OVAL agent.

docs/manual/manual.adoc
=> Update MS Windows Instructions

src/OVAL/probes/unix/linux/rpmverifyfile.c
When we were investigating issue #212, we found that there are some
invalid reads from memory in the rpmverifyfile_probe.
This commit fixes the valgrind warning, however it does not fix
the issue.
Addressing:
```
Invalid read of size 1
at 0x4C2BC22: strlen (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
by 0x4E9D9E5: probe_item_create (probe-api.c:1431)
by 0x405BAB: rpmverify_additem (rpmverifyfile.c:352)
by 0x405BAB: rpmverify_collect (rpmverifyfile.c:297)
by 0x405BAB: probe_main (rpmverifyfile.c:472)
by 0x40761F: probe_worker (worker.c:951)
by 0x407242: probe_worker_runfn (worker.c:54)
by 0x715F554: start_thread (pthread_create.c:333)
by 0x767EB9C: clone (clone.S:109)
Address 0xc933bc0 is 0 bytes inside a block of size 37 free'd
at 0x4C29D6A: free (in …
```
=> Fix valgrind warning in rpmverifyfile probe

src/OVAL/probes/SEAP/seap-message.c
Information about freeing memory is interesting only for a C developer.
=> Change category of a message

src/OVAL/probes/SEAP/seap-command.c
Pointers and values of some variables are interesting only for a developer.
=> Change category of messges in SEAP command function

src/OVAL/probes/SEAP/seap-packet.c
These messages were not suitable be in info category.
=> Change category of messages

docs/manual/manual.adoc
Describe new verbose mode and update the manual. Also typo fixes.
=> Issue #238: Mention verbose mode in user manual

src/XCCDF_POLICY/xccdf_policy.c
This commit gives user basic understanding of XCCDF evaluation process.
=> Add info messages to xccdf_policy.c

src/OVAL/oval_probe.c
This pull request wants to remove one of two same words.
=> Fix a typo

src/OVAL/probes/unix/file.c
Adding a missing end of line and change wording of this message.
=> Improve a warning

src/OVAL/oval_variable.c
If an OVAL definition contains objects indirectly referenced by
a local variable, it is useful to see the values of this variable
after the referenced object has been evaluated.
=> Write values of referenced variables to log

ac_probes/configure.ac.tpl, configure.ac, tests/probes/Makefile.am, tests/probes/sysctl/Makefile.am, tests/probes/sysctl/all.sh, tests/probes/sysctl/test_sysctl_probe.oval.xml, tests/probes/sysctl/test_sysctl_probe.sh
This is a very simple test for sysctl probe.
We haven't had test the probe yet.
=> Add a test for sysctl probe

utils/oscap-vm
SC2155: Declare and assign separately to avoid masking return values
=> Fix shellcheck warning

src/OVAL/oval_session.c, tests/API/OVAL/unittests/Makefile.am, tests/API/OVAL/unittests/all.sh, tests/API/OVAL/unittests/test_directives.sh, tests/API/OVAL/unittests/test_directives.xml
@jan-cerny found a bug in OVAL session described in PR #270. 
First commit adds fixes SIGSEGV which is caused when some OVAL Directives is used and second commit adds test catching this issue.
=> Create dir model

src/OVAL/probes/independent/textfilecontent54.c
The textfilecontent54 probe currrently works only with UTF8 strings.
It is unable to assess files in different encodings (eg. ISO 8859-1),
because pcre_exec returns an error code. However, the probe reports
that assessed file does not exist. This commit fixes this wrong
behavior in a way that the probe will report an error message
in OVAL results and set the object flag to error when regular
expression matching failed and pcre_exec() returned an error code.
=> RHBZ#1285757: OpenSCAP pattern match test wrongly results with pass

tests/sce/Makefile.am
This commit adds missing files to the EXTRA_DIST section of makefile.
=> Fix SCE tests

utils/oscap_docker_python/get_cve_input.py
Fix case sensitivity issue while getting HTTP header dict.
+ refactoring
+ add "warning" before message
https://github.com/OpenSCAP/openscap/issues/304
I will test it later.
[SKIP_CI]
=> oscap docker http header fix

utils/oscap-docker.8
The tool is called oscap-docker, not docker-oscap.
=> Fix manual page for oscap-docker

src/OVAL/probes/unix/linux/partition.c, src/OVAL/probes/unix/password.c, src/OVAL/probes/unix/shadow.c
Should fix also
https://github.com/OpenSCAP/openscap/issues/292
=> Enable offline scan of some probes 

src/OVAL/probes/unix/linux/rpmverify.c, src/OVAL/probes/unix/linux/rpmverifypackage.c
Related to: https://github.com/OpenSCAP/openscap/pull/350
@jan-cerny probably oversight these probes
=> rpm* another probes fix

src/source/oscap_source.c, tests/sce/Makefile.am, tests/sce/test_sce_parse_errors-invalid-oval.xml, tests/sce/test_sce_parse_errors.sh, tests/sce/test_sce_parse_errors_load_corrupted_xml.xccdf.xml, tests/sce/test_sce_parse_errors_load_script.xccdf.xml, tests/sce/test_sce_parse_errors_script.sh, tests/sce/test_sce_parse_errors_stub-oval.xml
Should fix https://github.com/OpenSCAP/openscap/issues/230
Feedback is welcome.
=> Stop printing of XML errors during SCE loading

tests/sce/Makefile.am, tests/sce/test_sce_in_ds.sh, tests/sce/test_sce_in_ds.xml
Test for SCE in DS, will FAIL in maint-1.2 branch.
Wais for https://github.com/OpenSCAP/openscap/pull/349
=> tests/sce: Add test for SCE in DS

tests/sce/Makefile.am
=> tests/sce_parse_errors: Add test to Makefile.am

tests/sce/Makefile.am
I forgot to append test to 
Append forgotten test
=> tests/sce-in-ds: Add to Makefile.am

src/DS/ds_sds_session.c, src/DS/sds.c, src/DS/sds_priv.h, src/SCE/module_entry.c, src/XCCDF/xccdf_session.c, src/XCCDF_POLICY/xccdf_policy.c
Should fix:
- fix https://github.com/OpenSCAP/openscap/issues/295
- refactoring/don't create temp directory for SCE when we don't have any SCE
=> SDS SCE fix

utils/oscap_docker_python/oscap_docker_util.py
https://github.com/OpenSCAP/openscap/issues/329
If no directory to mount is passed, it create temporary directory before mount and remove it after operation is done.
=> oscap-docker: Mount in safe temporary container

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
Merge CPE oval from maint-1.2.
After this commit should be these files same - byte by byte.
=> openscap-cpe-*.xml: update from maint-1.2

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
=> Revert "openscap-cpe-*.xml: update from maint-1.2"

src/OVAL/results/oval_resultDefinition.c, src/OVAL/results/oval_resultTest.c, src/common/debug.c, src/common/debug_priv.h
This commit adds two functions that either increase or
decrease indent of messages in verbose log.
=> Indent messages in verbose log

src/OVAL/probes/probe/icache.c, tests/probes/file/Makefile.am, tests/probes/file/test_probes_file.sh
We have often randomly failed file probe test.
It should help us to find the issue
=> probes/file: Add debug output & modify test

tests/probes/process58/command_line.sh
Part of solution of https://github.com/OpenSCAP/openscap/issues/461.
=> tests/process58: Use specified xpath

xsl/xccdf-share.xsl
https://github.com/OpenSCAP/openscap/issues/460
=> Fix dotted remediation scripts

src/DS/rds.c
Fix (maybe only part of) https://github.com/OpenSCAP/openscap/issues/479
=> rds: Move free after usage

src/OVAL/probes/unix/sysctl.c
=> probes/sysctl.c: Fix typo

src/OVAL/probes/probe/icache.c
I have replaced goto -> do{}while without fixing of indentation. I expect more our changes and don't want make conflicts.
=> call signal in mutex

src/OVAL/probes/probe/icache.c
Only moving/renaming of commands, logic should be same.
=> icache.c: refactoring

tests/probes/process58/command_line.sh
I have opened the file due to failing test, but it probably will not fix anything
=> tests/process58: some minor patches

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml, src/OVAL/probes/unix/runlevel.c
Signed-off-by: T.O. Radzy Radzykewycz <radzy@windriver.com>
=> Initial Wind River Linux support

docs/manual/manual.adoc
Cherry-pick of to maint-1.0
https://github.com/OpenSCAP/openscap/pull/515
=> update repository name

src/XCCDF_POLICY/xccdf_policy_remediate.c
Example of usage:
```
$ myoscap xccdf generate fix --template urn:xccdf:fix:script:ansible /tmp/res.xml | tee  /tmp/ansible.yml
---
- hosts: localhost # set required host
tasks:
- name: Ensure aide is installed
package:
name="{{item}}"
state=present
with_items:
- aide
- name: Ensure vsftpd is installed
package:
name="{{item}}"
state=present
with_items:
- vsftpd
```
```
$ sudo ansible-playbook /tmp/ansible.yml 
[sudo] password for zmoravec: 
[WARNING]: provided hosts list is empty, only localhost is available
PLAY [localhost] ***************************************************************
TASK [setup] *******************************************************************
ok: [localhost]
TASK [Ensure aide is installed] ************************************************
changed: [localhost] => …
```
=> ansible generate fix - add header & indentation 

src/DS/ds_sds_session.c, src/DS/ds_sds_session_priv.h, src/DS/sds.c, tests/DS/Makefile.am, tests/DS/sds_external_xccdf/sds.ds.xml, tests/DS/sds_external_xccdf/xccdf.sds.xml, tests/DS/sds_external_xccdf/xccdf.xml, tests/DS/test_ds.sh
I've decided to split part of my changes to loading external components.
This should make working such references
```
xlink:href="file:xccdf.sds.xml#scap_1_comp_xccdf.xml"
```
```
xlink:href="file:xccdf.xml"
```
=> Loading of external components

docs/manual/manual.adoc
It is here for revision.
Before merge I will check that everything is working with maint-1.0, too.
**Criticism is welcome!**
=> Add missing manual sections

dist/bash_completion.d/oscap, src/DS/ds_sds_session.c, src/DS/ds_sds_session_priv.h, src/DS/public/ds_sds_session.h, src/DS/sds.c, src/XCCDF/public/xccdf_session.h, src/XCCDF/xccdf_session.c, src/common/Makefile.am, src/common/oscap_acquire.c, src/common/public/xccdf_download_cb.h, utils/oscap-ds.c, utils/oscap-info.c, utils/oscap.8
https://github.com/OpenSCAP/openscap/issues/526
=> Add support for external (http) components

xsl/xccdf-share.xsl
Do you have a better idea how to show it?
https://github.com/OpenSCAP/openscap/issues/541
=> xccdf report: Add fix attributes

dist/bash_completion.d/oscap, src/DS/ds_sds_session.c, src/DS/public/ds_sds_session.h, src/OVAL/oval_session.c, src/OVAL/public/oval_session.h, src/XCCDF/public/xccdf_session.h, src/common/Makefile.am, src/common/public/oscap_download_cb.h, utils/oscap-ds.c, utils/oscap-info.c, utils/oscap-oval.c, utils/oscap-tool.c, utils/oscap-tool.h, utils/oscap-xccdf.c, utils/oscap.8
Related to https://github.com/OpenSCAP/openscap/pull/534
=> enable oscap oval eval --fetch-remote-resources + cleanup

src/XCCDF/xccdf_session.c
This pull request allows user to evaluate a tailoring within datastream that customizes benchmarks located in other datastream in on other datastream collection in an other separate file.
=> Add support for tailoring of external datastreams

src/OVAL/probes/independent/system_info.c
to feed system_info for chroot/vm scans, it currently relies
on the use of grub2.
Small change in system_info probe logic, it doesn't fail if
it was not possible to collect system_info, it reports as
"Unknown" OS name/version/arch and hostname.
=> Temporary fix to remove the need of environment variables

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
Adding definitions to openscap-shipped CPE dictionary.
Related to rhbz#1311054.
=> RHEL 6 ComputeNode CPE and RHEL 7 ComputeNode CPE

src/OVAL/probes/unix/runlevel.c
Instead of checking the presence of /etc/wrlinux-release, we open
/etc/os-release and check for the CPE_NAME entry.
Signed-off-by: T.O. Radzy Radzykewycz radzy@windriver.com
=> Update is_wrlinux to check /etc/os-release

src/OVAL/probes/independent/system_info.c
Fixed RESOURCE_LEAK, CHECKED_RETURN, COMPILER_WARNING and STRING_NULL.
Defect type REVERSE_INULL in #590 looks false-positive to me.
=> Fixed some warnings reported by Coverity in #590.

utils/oscap-ds.c
Added --verbose and --verbose-log-file to 'oscap ds rds-validate'.
=> Added --verbose and --verbose-log-file to 'oscap ds rds-validate'.

utils/oscap-ssh, utils/oscap-vm
Minor improvements to our util scripts to get rid of some `ShellCheck` warnings. There are more to fix but this PR fixes everything in #431 except false positives listed in the ticket.
=> ShellCheck warnings mostly fixed in our utils scripts

src/SCE/sce_engine.c
The fcntl function manipulates file descriptors. It may fail.
On error, it returns -1. We should check for the return value,
and if it fails, cancel the operation and display an error
message.
=> Issue #681: Check for return value of fcntl

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
=> Issue #692: Add Fedora 26 and Fedora 27 CPEs

utils/oscap-xccdf.c
=> Added verbose support for `oscap xccdf remediate` module

docs/manual/manual.adoc
This adds a few paragraphs into OpenSCAP User Manual, however I didn't want to copy everything from man pages.
=> Issue #249: Mention oscap-ssh, oscap-docker in User's manual

utils/oscap_docker_python/oscap_docker_util.py
This will enable to see all the issues reported by oscap,
eg. remote resources suggestion, and all the other warnings
that are produced by the oscap tool.
=> Issue #713: Copy stderr produced by oscap to stderr of oscap-docker

src/OVAL/adt/oval_string_map.c, src/OVAL/oval_agent.c, src/OVAL/oval_sexp.c, src/OVAL/probes/unix/linux/rpminfo.c
These messages are disturibing, moreover there is no way
how a user can mitigate them.
=> Change the category of messages

src/CPE/cpedict_priv.c, src/CPE/public/cpe_dict.h
Changed cpe_dict_model_add_item() to be a publicly accessible function.
=> Expose cpe_dict_model_add_item()

src/XCCDF_POLICY/xccdf_policy_resolve.c, tests/API/XCCDF/unittests/test_xccdf_refine_rule_refine.sh, tests/API/XCCDF/unittests/test_xccdf_refine_rule_refine.xccdf.xml
Hi Team, this pull request fixes a unit test, creates more asserts and fixes the issue #739.
Each commit has its own description.
=> Fixes #739

README.md
Since you need the tools for running autogen, they should be mentioned first.
=> Change to clarify tools needed for autogen

xsl/xccdf-report-impl.xsl
Added support for shortnames of 800-171 and FBI CJIS.
=> Html report group by improvements (CJIS, 800-171)

README.md
I mainly added packages required for `make check` and the requirement to run sendmail service.
=> Updated 'Compilation' section in README.md

libopenscap.pc.in
https://bugzilla.redhat.com/show_bug.cgi?id=1414777
Merge at your own risk. 😜 
🥞 🐼 🚽 🤙
=> No need to require libpcre when you depend on libopenscap

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
=> Add Fedora 28 CPE

src/OVAL/oval_variable.c, src/OVAL/probes/SEAP/sexp-manip.c
This PR provides fixes for some of the warnings, but there is much more to be fixed.
=> Fix some warnings

.gitignore
tags is a file produced by ctags tool
=> Add tags file to .gitignore

tests/probes/textfilecontent54/Makefile.am, tests/probes/textfilecontent54/test_filecontent_non_utf.iso8859, tests/probes/textfilecontent54/test_filecontent_non_utf.oval.xml, tests/probes/textfilecontent54/test_filecontent_non_utf.sh, tests/probes/textfilecontent54/test_filecontent_non_utf.utf8
Relates to commit https://github.com/OpenSCAP/openscap/commit/abc52f8ba07fb48efcc34228ed394234157b9c9c
=> Test to cover filecontent test of non-utf files

src/DS/sds.c, src/DS/sds_priv.h, src/XCCDF/xccdf_session.c
https://bugzilla.redhat.com/show_bug.cgi?id=1485876
=> RHBZ#1485876: Fix oscap running out of memory

src/common/oscap_acquire.c
Also fix a couple of other minor issues (strdup returned value and error message).
=> Fix for systems that lack POSIX.1-2008 realpath

src/OVAL/probes/unix/process58.c
getpidcon() function returns a value from /proc/<pid>/attr/current but
this interface is used by other LSM's like AppArmor too so the value
could be SELinux unrelated. Therefore we should check if SELinux is
enabled before we try to collect a process label.
=> process58: Do not collect SELinux labels when SELinux is not enabled

src/XCCDF/result.c, utils/oscap-chroot, utils/oscap-vm, utils/oscap_docker_python/oscap_docker_util.py, xsl/xccdf-report-impl.xsl
=> HTML report to report target as container or image, not as host

src/OVAL/probes/unix/file.c
Also fix a 32/64 bit issue in get_size function and clean the code for BSD.
=> Add support for AIX and other legacy Unices

utils/oscap-vm.8
The manual page for oscap-vm is very short. This pull request tries to improve the manual page.
=> update oscap-vm manual page

src/CVSS/cvss.c, src/XCCDF_POLICY/xccdf_policy_remediate.c
This pull request fixes some of new issues reported by Coverity. See commit messages.
=> Coverity fixes 1

src/OVAL/oval_agent.c, src/OVAL/oval_component.c, src/OVAL/oval_sexp.c, src/OVAL/probes/unix/sysctl.c, src/OVAL/probes/unix/xinetd.c
This pull request fixes some of new issues reported by Coverity. See commit messages.
=> Coverity fixes 3

src/OVAL/adt/oval_collection.c, src/XCCDF/xccdf_session.c, src/common/list.c
This pull request fixes some of new issues reported by Coverity. See commit messages.
=> Coverity fixes 4

xsl/xccdf-report-impl.xsl
- Update DISA SRG link for Operating Systems
- Add DISA SRG link for Applications
- Add DISA STIG link for Applications
=> Update and Enhance DISA SRG and STIG links

src/OVAL/probes/unix/file.c
=> Continue the file tree walk in case of lstat error

dist/bash_completion.d/oscap
Just included updated 'info' and 'xccdf eval'.
=> Updated bash completion.

src/CVRF/cvrf_priv.c, src/XCCDF_POLICY/xccdf_policy_remediate.c, utils/oscap-cvrf.c
Coverity scan of 1.2.16 revealed some problems (see #909 ). This PR aims to fix the most harmful ones.
=> Fixed most painful issues found by Coverity scan.

tests/API/XCCDF/unittests/Makefile.am, tests/API/XCCDF/unittests/all.sh, tests/API/XCCDF/unittests/test_remediation_metadata.sh, tests/API/XCCDF/unittests/test_remediation_metadata.xccdf.xml, tests/API/XCCDF/unittests/test_remediation_simple.sh, tests/API/XCCDF/unittests/test_remediation_simple.xccdf.xml
This PR adds tests to check that remediation roles have:
=> Add remediation tests.

src/XCCDF_POLICY/xccdf_policy_remediate.c
- Fixes https://github.com/OpenSCAP/scap-security-guide/issues/2520
=> Fix output of generated bash role missing fix message

AUTHORS, schemas/cve/cve_0.1.xsd
=> Cve numbers

src/CPE/public/cpe_name.h
This is #824 except it targets the master branch. Everything else is the same.
=> Update cpe_name.h (CPE name patch retarget)

xsl/xccdf-guide-impl.xsl, xsl/xccdf-report-impl.xsl
- Remove right leaning content
- Bring rules in line with some of the look and feel of XCCDF HTML Report
=> Update the XCCDF HTML Guide XSLT

.gitignore, cpe/Makefile.am, tests/CPE/all.sh, tests/Makefile.am, tests/mitre/test_mitre.sh, tests/nist/Makefile.am, tests/nist/nist_test.sh, tests/offline_mode/Makefile.am, tests/offline_mode/test_offline_mode_system_info.sh, tests/offline_mode/test_offline_mode_textfilecontent54.sh, tests/oscap_string/test_oscap_string.sh, tests/oval_details/Makefile.am, tests/oval_details/test_oval_details.sh, tests/probes/maskattr/test_object_entity_mask_oval_5_9.sh, tests/probes/sysctl/Makefile.am, tests/probes/sysctl/all.sh, tests/probes/sysctl/test_sysctl_probe.sh, tests/probes/sysctl/test_sysctl_probe_all.sh, tests/sce/test_passing_vars.sh, tests/sce/test_sce_parse_errors.sh, tests/sources/all.sh
The tests will pass when using `VPATH` build and with `sendmail` service not running.
=> Made make check pass on out-of-tree builds.

src/common/oscap_acquire.c
This commit fixes `oscap_acquire_temp_dir` which was broken on Windows.
First issue was that it was not able to create a temp directory if the parent directory didn't exist. The second issue was that it created a directory with always same name.
The commit also provides a Windows implementation of `oscap_acquire_cleanup_dir`, which was completely missing, and which removes the temporary directory created by `oscap_acquire_temp_dir`.
These functions are used when working with SCAP DataStreams.
=> Create and remove temporary directory on Windows

tests/sce/python_is16.py, tests/sce/script_tester.py
This PR changes our Python scripts to work in both Python 2 and 3.
=> Python 3 compatibility fixes

README.md, appveyor.yml
This will add:
* an AppVeyor icon which will show the status of last build on AppVeyor, where we build WIndows builds.
* AppVeyor project configuration in YAML format
=> Add AppVeyor CI badge and configuration

src/DS/sds.c, src/OVAL/oval_entity.c, src/OVAL/results/oval_resultCriteriaNode.c
Trying sonarcloud with some easy fixes.
=> Sonarcloud fixes1

cmake/FindThreads.cmake
It's confusing in the configure output... Is this a debugging leftover, @jan-cerny ?
=> Don't shout about pthread when configuring

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml, release_tools/versions.sh
Fedora 28 has been branched and also released.
=> Add Fedora 29 CPE

.travis.yml
https://codecov.io/gh/OpenSCAP/openscap
=> Added codecov support.

.travis.yml
Prevent harmless or expected failiures to result in failed test run.
=> Make Travis tests less troublesome.

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
I've updated the openSUSE CPEs to match the updated entries inside the official NIST CPE dictionary.
=> openSUSE CPE update

release_tools/release.sh, release_tools/up_to_compliance_check.sh, release_tools/versions.sh
This commit reflects recent changes in master branch, namely CMake
and dropping Python 2.
Fixes #1036 .
=> Update release tools to work in master branch

src/XCCDF_POLICY/xccdf_policy_remediate.c
I use this all the time and it's not obvious to use the -c local
=> Include an example how to apply generated playbook on localhost

.travis.yml, tests/API/OVAL/unittests/test_object_component_type.sh, tests/API/XCCDF/unittests/test_xccdf_transformation.sh, tests/probes/iflisteners/test_probes_iflisteners.sh, tests/probes/maskattr/test_object_entity_mask.sh, tests/probes/maskattr/test_object_entity_mask_oval_5_9.sh, tests/probes/maskattr/test_object_entity_nomask.sh, tests/probes/rpmverify/test_not_equals_operation.sh, tests/probes/sysctl/test_sysctl_probe.sh, tests/probes/sysctl/test_sysctl_probe_all.sh
Fixed bugs in test scripts:
- Fixed unexpected behavior when command doesn't fail (`test_object_component_type.sh`)
- Replaced some exit statements by return statements, so tests skipping is handled properly.
=> Tests fixes

tests/API/CVE/test_api_cve.c, tests/API/CVRF/test_api_cvrf.c, tests/API/OVAL/schema_version/test_schema_version.c, tests/API/XCCDF/unittests/test_oscap_common.c, tests/API/XCCDF/unittests/test_xccdf_overrides.c, tests/API/XCCDF/unittests/test_xccdf_shall_pass.c, tests/API/XCCDF/unittests/unit_helper.c, tests/bz2/test_bz2_memory_source.c, tests/sources/all.sh
=> Config h tests

release_tools/README.adoc
During the last OpenSCAP release I improved a bit README file for the release tools.
=> Update release tools README

xsl/xccdf-report-impl.xsl
=> Show the test system in HTML report

xsl/xccdf-report-impl.xsl
=> Show benchmark version in HTML report if available

CMakeLists.txt
=> Add _DARWIN_C_SOURCE definition for OSX

compat/oscap_platforms.h
Also fixed the copyright date because @redhatrises has just written this, it's not from 2017...
=> Add header guard to oscap_platforms.h

src/OVAL/probes/independent/sql.c, src/OVAL/probes/independent/sql57.c
This PR fixes some of the annoying warnings by compiler.
For more details and addressing, please see the commit messages of specific commits.
=> Fix some warnings in maint-1.2

.travis.yml
- Enable python3 builds and make sure required build deps are installed
=> Update OSX CI builds

utils/oscap.8
=> Fix 2 typos

docs/developer/developer.adoc
=> Developer manual: added cmake command which enables docs building

src/OVAL/probes/independent/textfilecontent54.c
This improves the readability.
=> Remove unused commented code

src/OVAL/probes/probe/worker.c
Add missing `SEXP_free` calls.
=> Add missing 'free' calls to src/OVAL/probes/probe/worker.c (master branch)

src/OVAL/probes/SEAP/seap-packet.c
This will inform us when some of the locks fails.
It can help us with debugging #1199.
=> Check lock return values

src/OVAL/probes/probe-api.c, src/OVAL/results/oval_cmp_ip_address.c
This PR fixes 3 potential leaks that have been found by the Coverity scan. The datives can be found in commit messages.
=> Plug memory leaks

tests/probes/sysctl/test_sysctl_probe_all.sh
Some sysctl options cannot be read until they are set. Sysctl from
procps-ng > 3.3.12 reports an error when reading these options but still
prints them to stdout. On the other hand openscap does not include these
options into results when they are not set. This was introduced in the commit
7b8ca9c and it is causing different results between openscap and sysctl from
procps-ng > 3.3.12. This commit updates the sysctl test to count with these
differences in case that procps-ng > 3.3.12 is installed on the system.
Fixes https://github.com/OpenSCAP/openscap/issues/1152
=> tests/probes/sysctl/test_sysctl_probe_all.sh: updated for procps-ng > 3.3.12

utils/oscap.8
I have reviewed the man page and I have updated it.
=> Update man page

utils/oscap.8
I have reviewed the man page and I have updated it.
=> Update man page (maint-1.3)

Makefile.am
Fixes the upsteam part of https://bugzilla.redhat.com/show_bug.cgi?id=1465661 point No.1
=> Make sure that the manual HTML is built and distributed.

src/OVAL/probes/windows/registry_probe.c
=> Fix a memory leak in registry_probe.c

README.md
Improve the command for installing build dependencies by adding sections
for both Fedora/RHEL and Ubuntu.
=> Improve README documentation.

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
RHEL8 Beta has been announced.
https://www.redhat.com/en/blog/powering-its-future-while-preserving-present-introducing-red-hat-enterprise-linux-8-beta
=> Add RHEL8 CPE to OpenSCAP CPE dictionary

src/OVAL/results/oval_cmp_basic.c
This can help us to resolve problems similar to RHBZ#1655943.
=> Improve error message for pcre_exec fail

xsl/xccdf-guide-impl.xsl
=> Show rule ID in HTML guide

src/OVAL/probes/findfile.c, src/OVAL/probes/fsdev.c, src/OVAL/probes/oval_fts.c, src/OVAL/probes/public/fsdev.h
This patch refactors and removes dead code from FSDEV module.
For more details, please see each of the commit messages.
=> Refactor and remove dead code from FSDEV module

src/DS/rds.c, src/OVAL/oval_defModel.c, src/OVAL/oval_generator.c, src/OVAL/oval_sysModel.c, src/OVAL/probes/SEAP/sexp-manip.c, src/OVAL/probes/probe/input_handler.c, src/OVAL/probes/unix/linux/inetlisteningservers_probe.c, src/OVAL/probes/unix/linux/rpmverify_probe.c, src/OVAL/probes/unix/linux/rpmverifyfile_probe.c, src/XCCDF/benchmark.c, src/XCCDF/item.c, src/XCCDF/resolve.c, src/XCCDF/result.c, src/XCCDF/xccdf_session.c, src/common/err_queue.c, utils/oscap-info.c
This PR aims to fix some of the GCC compiler warnings. Please read the commit messages of each commit.
=> Fix some of compiler warnings

docs/developer/developer.adoc
=> Document creating build directory

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
Add WRLinux 1019 support in CPE directory.
=> Add WRLinux 1019 support

docs/manual/manual.adoc
Add new section and answer to question, why you get "nonchecked" result when you download e.g. STIG checklist.
=> Add FAQ section to User Manual and add question about "nonchecked"

docs/manual/manual.adoc
Added recommendation for using ComplianceAsCode project
=> Improve answer for FAQ about "notchecked" result at documentation

docs/manual/manual.adoc
We get this question many times.
=> Add tailoring profile ID to FAQ

docs/contribute/versioning.adoc, docs/developer/developer.adoc
=> Documentation fixed (build deps, versions)

utils/oscap-docker.8, utils/oscap-vm, utils/oscap-vm.8
This will allow execution of commands like:
./run ../utils/oscap-vm --oscap=utils/oscap image <IMAGE> oval eval probe_test_rpm.oval.xml
=> utils/oscap-vm: Add ability to run uninstalled oscap-vm.

xsl/oval-to-xccdf.xsl
Interestingly, I overlooked this years ago and nobody noticed since then.
=> Remove duplicate case in a switch (xslt:choose)

src/OVAL/probes/independent/environmentvariable58_probe.c, src/OVAL/probes/independent/environmentvariable58_probe.h, src/OVAL/probes/probe-table.c, utils/oscap-podman, utils/oscap-podman.8, utils/oscap_docker_python/oscap_docker_util.py
I have some doubts about importing variables from containers as they are, without prefixing, but I can't put my finger on any case in particular.
=> Offline mode support for environmentvariable58_probe

src/XCCDF_POLICY/xccdf_policy_remediate.c, tests/API/XCCDF/fix/all.sh
And made the corresponding test more informative.
=> Added a shebang to generated bash remediations.

xsl/xccdf-resources/openscap.js
Added a comment into openscap.js not to remove certain attributes because it breaks accessibility of reports and guides
=> added a comment about not removing attributes improving a11y

.travis.yml
Fixes error in Travis build for MacOS due to outdated xcode version
Similar to https://github.com/OpenSCAP/scap-workbench/pull/238
=> Remove old xcode

utils/CMakeLists.txt
so now one can run `sudo make oscap-chrootable` right away without calling `make oscap-chrootable-nocap` first.
=> Fixed oscap-chrootable dependency.

.travis.yml
- Set up the recent Ubuntu as build base.
- Add tests execution as part of the setup.
=> Cleaned the Travis setup up.

release_tools/release.sh, tests/probes/password/test_probes_password_offline.sh
Various fixes related to release scripts
=> Release fixes

release_tools/README.adoc, release_tools/release.sh
Various fixes and update for the release scripts and guide
=> Fixes for the release scripts. Release guide updates.

src/OVAL/probes/fsdev.c, src/XCCDF_POLICY/xccdf_policy_remediate.c, utils/oscap-chroot, utils/oscap-podman, utils/oscap-ssh, utils/oscap-vm
Some fixes for covscan of 1.3.2
=> Covscan fixes

src/XCCDF/xccdf_session.c, swig/openscap.i, swig/openscap_api.py, tests/bindings/python/xccdf_evaluation.py, tests/bindings/python/xccdf_single_evaluation.py, tests/bindings/test_python.sh
Hello,
Some time ago i've signalled a serious issue #1453  in the python binding, the xccdf_session_set_rule was just not working.
Here is a proposal of correction, including two more unit tests which ensure it's working now.
I can understand some technical choices are debatable in this solution but i've to be as clear as possible. If you have a better proposal i'm all ears !
Regards,
Dominique.
=> Fix #1453 pointer lost in Swig API

.travis.yml, docs/developer/developer.adoc, tests/probes/rpm/rpminfo/test_probes_rpminfo.sh, tests/probes/rpm/rpmverify/test_probes_rpmverify_not_equals_operation.sh, tests/probes/rpm/rpmverify/test_probes_rpmverify_not_equals_operation_offline.sh, tests/probes/rpm/rpmverifypackage/rpmverifypackage.xml.sh
This should fix tests on Travis.
=> Fix tests on Travis to not ignore their results

tests/probes/yamlfilecontent/CMakeLists.txt, tests/probes/yamlfilecontent/test_probes_yamlfilecontent_offline_mode.sh, tests/probes/yamlfilecontent/tests_probes_yamlfilecontent_offline_mode.xml
- Add offline mode tests for `yamlfilecontent` probe
- The tests scripts sets up "host" and "chroot" environments
=> Add offline mode test for yamlfilecontent

tests/probes/environmentvariable58/test_probes_environmentvariable58.sh
Test covers PR https://github.com/OpenSCAP/openscap/pull/1487
=> tests/probes/environmentvariable58: add test to cover 7c78b84dd

src/CPE/cpename.c, src/OVAL/probes/SEAP/sexp-value.c, src/OVAL/probes/independent/yamlfilecontent_probe.c, src/OVAL/probes/unix/gconf_probe.c, src/OVAL/probes/unix/linux/rpminfo_probe.c, src/OVAL/probes/unix/linux/systemdshared.h, utils/oscap-tool.h
Fixes for various problems detected by LGTM: https://lgtm.com/projects/g/OpenSCAP/openscap/?mode=list&lang=cpp
=> Fix LGTM warnings

src/OVAL/probes/independent/yamlfilecontent_probe.c
The event created by the yaml_parser_parse should be cleaned
with yaml_event_delete unless the event is used by the emitter.
=> OVAL/probes: Add proper event cleanup for yamlfilecontent probe

tests/probes/rpm/rpmverifyfile/test_probes_rpmverifyfile.sh, tests/probes/rpm/rpmverifyfile/test_probes_rpmverifyfile.xml, tests/probes/rpm/rpmverifyfile/test_probes_rpmverifyfile_older.sh, tests/probes/rpm/rpmverifyfile/test_probes_rpmverifyfile_older.xml
=> Use different subject in tests

src/OVAL/probes/probe/worker.c, utils/oscap-podman
This PR fixes minor problems reported by Coverity. For more details, please read commit messages of every commit.
=> Coverity fixes

utils/oscap-docker.in
For more details, please see the commit messages of each commit.
=> Fix oscap-docker when Atomic is not present

tests/probes/password/test_probes_password.xml.sh
This test ensures that OpenSCAP password probe returns the same data
as defined in `/etc/passwd`. But, the probe doesn't read the
`/etc/passwd` file. It uses `getpwent` function instead, which employs
also other user sources, including systemd-userdb.service. Systemd
245 is affected by a bug that causes that `getpwent` or `getent passwd`
command returns `root` and `nobody` users twice, each time returns
a different login shell. This bug is already fixed upstream, but
occurs on Fedora 32.
See: https://github.com/systemd/systemd/issues/15160
To prevent CI failures we can workaround the test. If an affected
version is present on the system, it won't test the items returned
for the 2 problematic users. All other user items will be still
tested. Since all the items are produced by the same …
=> Workaround systemd bug in password probe test

src/CVRF/cvrf_enumeration.c, src/OVAL/oval_definitions_impl.h, src/OVAL/oval_enumerations.c, src/OVAL/probes/SEAP/_sexp-value.h, src/OVAL/probes/SEAP/generic/redblack.h, src/OVAL/probes/probe-api.c, src/XCCDF/public/xccdf_benchmark.h, src/XCCDF/result.c
This PR aims to fix some of the warnings that appeared with GCC 10. For more details, please see the commit message of each commit.
=> Fix compiler warnings

src/OVAL/probes/unix/linux/dpkginfo-helper.cxx
In libapt-pkg > 6.0 MMap::* considered as a private implementation detail.
This should unblock #1549 and fix #1541.
=> probes/dpkginfo: Use pkgCacheFile instead of manually opening cache

.github/workflows/main.yml, .travis.yml, tests/probes/password/test_probes_password.xml.sh, tests/probes/rpm/rpm_common.sh
Set up GH Actions CI.
Fixed Travis MacOS build.
=> GH Actions

docs/developer/developer.adoc
code has changed in appveyor.yml
install:
- cmd: vcpkg install curl libxml2 libxslt bzip2 pcre pthreads zlib getopt-win32
cache: c:\tools\vcpkg\installed\
before_build:
=> code has changed,but the doc has not changed

tests/suppressions.supp, tests/test_common.sh.in, tests/valgrind_test.sh
Adjust the valgrind wrapper for CMake.
=> Update valgrind test

xsl/xccdf-share.xsl
This will add a specific name to the green button which opens the remediation code.
=> Add Kubernetes remediation to HTML report

swig/perl/CMakeLists.txt
Changing hard coded libperl paths in favor of  FindPerlLibs method.
=> Changing hard coded libperl path in favor of  FindPerlLibs method

cpe/openscap-cpe-dict.xml, cpe/openscap-cpe-oval.xml
Signed-off-by: (GalaxyMaster) <galaxy4public@users.noreply.github.com>
=> Added CentOS 8 CPE

.travis.yml
Based on #1590 by odidev@github.com.
=> Add arm64 and ppc64le architectures to the Travis configuration

src/OVAL/probes/oval_fts.c, src/OVAL/probes/oval_fts.h, tests/probes/file/CMakeLists.txt, tests/probes/file/test_probes_file_behaviour.sh, tests/probes/file/test_probes_file_behaviour.xml
This is the fix for failing test from PR #1667. Fixes #1668.
=> File probe behaviour fix

docs/manual/manual.adoc
=> Describe SWID tags detection

src/OVAL/oval_probe_ext.c
=> Add proper resource management to the handler of empty messages from a probe

.github/workflows/main.yml
Should fix problem with CI in #1680. Sigh.
=> Fix "ERROR: The EULA was not accepted. Installation aborted." for 25-msodbcsql17_17.7.1.1-1_amd64.deb

utils/autotailor, utils/autotailor.8, utils/oscap-ds.c, utils/oscap-info.c, utils/oscap-oval.c, utils/oscap-ssh, utils/oscap-ssh.8, utils/oscap-vm.8, utils/oscap-xccdf.c, utils/oscap.8, utils/oscap.c
Minor formatting and factual fixes in our man pages and help texts and
outputs. Often fixes incorrect usage of "data stream".
=> Update man page and help texts

compat/dev_to_tty.c, src/DS/ds_common.c, src/OVAL/probes/SEAP/seap.c, src/XCCDF_POLICY/xccdf_policy.c
To get some information please read commit messages of every commit.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1938830
=> Fix some of the coverity warnings

docs/manual/manual.adoc
=> Document used environment variables

src/source/schematron.c
We need to check if the pointers are NULL.
Fixes: #1735
Also fixes similar occurences of XMLXPath(Node)Eval.
=> Fix a segmentation fault

xsl/xccdf-report-impl.xsl
This PR adds remark under a select of a profile as discussed in #1743.
Willing to fix any issues you all might find.
Big thanks to @cipherboy for pointing me to this issue.
=> Added remark under a select of a profile to the HTML XCCDF report

tests/probes/process58/CMakeLists.txt, tests/probes/process58/command_line.oval.xml, tests/probes/process58/command_line.sh, tests/probes/process58/command_line_extra.oval.xml, tests/probes/process58/command_line_extra.sh, tests/probes/process58/dev_to_tty.oval.xml, tests/probes/process58/dev_to_tty.sh, tests/probes/process58/loginuid.oval.xml, tests/probes/process58/loginuid.sh, tests/probes/process58/stopped_process.sh
This fix would allow us to execute the test suite inside a container. Look into individual commit messages for details.
=> Fix process58 tests

src/OVAL/probes/independent/yamlfilecontent_probe.c, src/source/schematron.c
=> Fix covscan-reported issues in yamlfilecontent probe and schematron

src/DS/rds_index.c, src/OVAL/oval_component.c, src/OVAL/oval_criteriaNode.c, src/OVAL/probes/independent/system_info_probe.c, src/OVAL/probes/unix/xinetd_probe.c, src/OVAL/results/oval_cmp_evr_string.c, src/XCCDF/xccdf_session.c, src/source/xslt.c, utils/oscap-tool.c
For detailed information please read commit messages of every commit.
=> Fix issues reported by Coverity

src/OVAL/probes/probe-table.c, src/OVAL/probes/unix/password_probe.c, src/OVAL/probes/unix/password_probe.h, tests/probes/password/test_probes_password_offline.sh
This will allow us to use OVAL password_test in offline mode.
Fixes: #1783
=> Add offline mode for password probe

utils/oscap-ssh.8
Related to: https://github.com/OpenSCAP/openscap/pull/1769
Thanks @ggbecker for pointing this out.
=> Document problems with --local-files in oscap-ssh

src/OVAL/results/oval_cmp_evr_string.c, tests/API/crypt/test_crapi_digest.c
Addressing some covscan issues in RHEL9. See the commit messages for details.
=> Fix covscan issues

src/common/oscap_acquire.c, tests/DS/test_ds_misc.sh
When the HTTP server returns status code greater than or equal 400,
the download will fail.
Resolves: rhbz#2002733
=> Fail download on HTTP errors

docs/manual/manual.adoc, src/OVAL/probes/probe/icache.c, src/OVAL/probes/probe/probe.h, src/OVAL/probes/probe/worker.c, src/common/memusage.c
Port patch "Lowering the memory limit " from PR #1803 to maint-1.3
Resolves: rhbz#2021851
=> Include memory limits patch to maint-1.3

src/DS/sds.c, src/XCCDF_POLICY/xccdf_policy_remediate.c
This PR will fix some minor coverity problems that can be fixed later.
For more details, please read every commit message of every commit.
=> Fix coverity issues

.packit.yaml, openscap.spec
Add epel-9 target
Disable propose_downstream job
Fix a typo in spec file
=> Infrastructure fixes: packit, spec file

src/XCCDF_POLICY/xccdf_policy.c, swig/openscap.i, utils/oscap-remediate
This PR fixes the new problems found by Coverity in OpenSCAP 1.3.6.
For more information, read commit messages of every commit.
=> Fixing coverity problems

README.md, docs/windows.md
There are no developers who are eager to maintain and support Windows compatibility.
=> Officially deprecate Windows support

tests/DS/test_ds_misc.sh, tests/curl/test_curl_encoding.sh, tests/probes/partition/test_probes_partition.sh, tests/probes/process58/selinux_domain_label.sh, tests/probes/sysctl/test_sysctl_probe_all.sh, tests/probes/systemdunitdependency/test_probes_systemdunitdependency.sh, tests/probes/systemdunitproperty/test_probes_systemdunitproperty.sh, tests/test_common.sh.in
Skip / tune tests
- if no internet access
- if no full systemd environment
- if chroot
- check SELinux using selinuxenabled
=> Test case skipping if setup is not full vm

.packit.yaml
For more details see
https://packit.dev/posts/copr-srpms/#deployment-phases
=> Define srpm_build_deps in packit configuration

src/XCCDF/result.c
=> fixes include of netdb.h in src/XCCDF/result.c

src/OVAL/probes/unix/linux/fwupdsecattr_probe.c, tests/probes/fwupdsecattr/test_probes_fwupdsecattr_mock.sh, tests/test_common.sh.in
This should make our CI happy.
=> Fix D-Bus mock init/cleanup and fwupdsecattr probe initialization

src/XCCDF_POLICY/xccdf_policy.c
=> Fix typo I made 12 years ago

src/OVAL/probes/probe-table.c, src/OVAL/probes/unix/shadow_probe.c, src/OVAL/probes/unix/shadow_probe.h, tests/probes/shadow/CMakeLists.txt, tests/probes/shadow/test_probes_shadow_offline.sh, tests/probes/shadow/test_probes_shadow_offline.xml
This change adds offline capabilities to the shadow probe.
=> Add offline capabilities to the shadow OVAL probe

utils/autotailor
If the autotailor will produce pretty output it will work around issue #1817.
=> Produce pretty output by autotailor

src/OVAL/probes/unix/runlevel_probe.c
These changes are adding support for OpenEmbedded and Poky distributions.
=> Adding OpenEmbedded and Poky  Distros

CMakeLists.txt, openscap.spec
It seems we have no real use-cases for it ATM.
=> Disable offline remediation service by default

src/DS/sds.c, src/OVAL/oval_component.c, src/OVAL/probes/independent/textfilecontent_probe.c, src/OVAL/probes/oval_fts.c, src/OVAL/probes/probe/input_handler.c, src/OVAL/probes/unix/linux/dpkginfo_probe.c, src/OVAL/probes/unix/linux/fwupdsecattr_probe.c, src/XCCDF/item.c, src/XCCDF_POLICY/xccdf_policy_remediate.c
This change fixes memory leaks reported by Coverity.
=> Fix memory leaks reported by Coverity

docs/developer/developer.adoc, swig/python3/CMakeLists.txt, utils/CMakeLists.txt
Fixes problems in rawhide like https://bugzilla.redhat.com/show_bug.cgi?id=2259525
=> Replace `distutils.sysconfig` with `sysconfig`

docs/developer/developer.adoc
=> Document that you can't use -j for ctest

Dockerfiles/test_suite, README.md, docs/manual/manual.adoc, release_tools/README.adoc
=> Fix references to the development branch (main)

CMakeLists.txt, openscap.spec, tests/API/OVAL/unittests/test_xsinil_envv58_pid.sh, tests/API/OVAL/validate/all.sh, tests/API/XCCDF/applicability/test_remediate_fix_processing_ds.sh, tests/API/XCCDF/variable_instance/all.sh, tests/CPE/all.sh, tests/DS/schematron/schematron.sh, tests/probes/sql57/unsupported_engine.sh, tests/probes/systemdunitdependency/test_probes_systemdunitdependency_validation.sh, tests/sce/CMakeLists.txt, utils/oscap-oval.c, utils/oscap-xccdf.c
See individual commit messages.
Closes: https://github.com/OpenSCAP/openscap/issues/1731
Closes: https://github.com/OpenSCAP/openscap/issues/2096
=> Cleanup 1.4

utils/oscap_docker_python/oscap_docker_util.py
=> Fix multiple tags for an image

src/OVAL/probes/probe/worker.c
https://github.com/OpenSCAP/openscap/pull/2168
=> Backport of #2168

.github/workflows/codeql.yml
The codeql job was failing due to dependencies not installing. Hopefully this should fix it.
=> Fix codeql dependencies
